// Generated by GitHub Copilot
/**
 * DEPRECATED — This module has been replaced by ./azure/repository.js
 *
 * The application now uses Azure Blob Storage (via @azure/storage-blob) as the
 * primary data store instead of the Azure DevOps Git API.
 *
 * This file is kept only to surface a helpful error if any older integrations
 * still reference it. It will throw immediately on require() so the problem is
 * surfaced at startup rather than silently at runtime.
 */
throw new Error(
    '[azureDevOpsStorage] This module is deprecated. ' +
    "Use require('./azure/repository') instead. " +
    'Data is now persisted to Azure Blob Storage.'
);

/**
 * (Original) Azure DevOps Git repository storage adapter.
 *
 * Stores all Weekend Support Tracker data as a single JSON file
 * (weekend-support-data.json) in the configured ADO Git repository.
 *
 * Authentication: Personal Access Token stored in AZURE_DEVOPS_PAT env var.
 * The PAT needs at minimum "Code (Read & Write)" scope on the target repo.
 *
 * Environment variables:
 *   AZURE_DEVOPS_PAT      – (required) Personal Access Token
 *   AZURE_DEVOPS_ORG      – ADO organisation (default: accenturecio08)
 *   AZURE_DEVOPS_PROJECT  – ADO project name (default: AutomationProcess_29697)
 *   AZURE_DEVOPS_REPO     – Repository name  (default: AutomationProcess_29697)
 *   AZURE_DEVOPS_BRANCH   – Target branch    (default: main)
 */
const https = require('https');
const { Buffer } = require('buffer');

const ORG = process.env.AZURE_DEVOPS_ORG || 'accenturecio08';
const PROJECT = process.env.AZURE_DEVOPS_PROJECT || 'AutomationProcess_29697';
const REPO = process.env.AZURE_DEVOPS_REPO || 'AutomationProcess_29697';
const BRANCH = process.env.AZURE_DEVOPS_BRANCH || 'main';
const DATA_PATH = '/weekend-support-data.json';
const API_VERSION = '7.0';

/**
 * Returns true when the AZURE_DEVOPS_PAT environment variable is set.
 * ADO storage is silently skipped when unconfigured (local dev fallback applies).
 * @returns {boolean}
 */
function isConfigured() {
    return !!(process.env.AZURE_DEVOPS_PAT);
}

/** Build a Basic-auth header from the PAT. The username is intentionally empty. */
function getAuthHeader() {
    return 'Basic ' + Buffer.from(`:${process.env.AZURE_DEVOPS_PAT}`, 'utf-8').toString('base64');
}

/**
 * Low-level HTTPS request helper for the Azure DevOps REST API.
 * Automatically serialises request body to JSON and parses the response body.
 *
 * @param {'GET'|'POST'} method
 * @param {string} urlPath  - path (and query string) portion of the URL
 * @param {object|null} body - request body — serialised as JSON when not null
 * @returns {Promise<{status: number, body: any}>}
 */
function adoRequest(method, urlPath, body) {
    return new Promise((resolve, reject) => {
        const bodyStr = body ? JSON.stringify(body) : null;
        const headers = {
            Authorization: getAuthHeader(),
            'Content-Type': 'application/json',
            Accept: 'application/json',
        };
        if (bodyStr) headers['Content-Length'] = Buffer.byteLength(bodyStr).toString();

        const req = https.request(
            { hostname: 'dev.azure.com', path: urlPath, method, headers },
            (res) => {
                let raw = '';
                res.on('data', (chunk) => { raw += chunk; });
                res.on('end', () => {
                    try {
                        resolve({ status: res.statusCode, body: raw ? JSON.parse(raw) : null });
                    } catch {
                        resolve({ status: res.statusCode, body: raw });
                    }
                });
            }
        );
        req.on('error', reject);
        if (bodyStr) req.write(bodyStr);
        req.end();
    });
}

/**
 * Fetch the current HEAD commit SHA for the configured branch.
 * This is required as the `oldObjectId` when pushing an update.
 * @returns {Promise<string>} commit objectId (40-char SHA)
 */
async function getLatestCommitId() {
    const urlPath =
        `/${ORG}/${encodeURIComponent(PROJECT)}/_apis/git/repositories/${encodeURIComponent(REPO)}` +
        `/refs?filter=heads%2F${encodeURIComponent(BRANCH)}&api-version=${API_VERSION}`;
    const result = await adoRequest('GET', urlPath, null);
    if (result.status !== 200 || !result.body?.value?.[0]) {
        throw new Error(`ADO getLatestCommitId failed HTTP ${result.status}: ${JSON.stringify(result.body)}`);
    }
    return result.body.value[0].objectId;
}

// Cached flag so we know whether to use 'add' or 'edit' on the next push
let _fileExistsInRepo = false;

/**
 * Load app data from the Azure DevOps repository.
 * Returns null (not an error) when the file has not been created yet.
 *
 * @returns {Promise<object|null>} parsed data object, or null if unavailable
 */
async function loadData() {
    if (!isConfigured()) {
        console.log('Azure DevOps PAT not set — ADO storage skipped');
        return null;
    }
    try {
        const urlPath =
            `/${ORG}/${encodeURIComponent(PROJECT)}/_apis/git/repositories/${encodeURIComponent(REPO)}` +
            `/items?path=${encodeURIComponent(DATA_PATH)}&includeContent=true&api-version=${API_VERSION}`;
        const result = await adoRequest('GET', urlPath, null);

        if (result.status === 404) {
            console.log('Azure DevOps: data file not found — will create on first save');
            _fileExistsInRepo = false;
            return null;
        }
        if (result.status !== 200) {
            console.error(`Azure DevOps loadData: HTTP ${result.status} — ${JSON.stringify(result.body)}`);
            return null;
        }

        _fileExistsInRepo = true;

        // The items API with includeContent=true returns the file text in the 'content' field
        const rawContent = result.body?.content;
        if (!rawContent) {
            console.error('Azure DevOps loadData: no content field in response — check path and PAT scope');
            return null;
        }

        const parsed = JSON.parse(rawContent);
        console.log(
            `Azure DevOps: loaded ${Object.keys(parsed.entries || {}).length} entries, ` +
            `${(parsed.employees || []).length} employees`
        );
        return parsed;
    } catch (err) {
        console.error('Azure DevOps loadData error:', err.message);
        return null;
    }
}

/**
 * Save app data to the Azure DevOps repository.
 *
 * Each call creates one Git commit.  To avoid excessive commits from rapid
 * sequential writes, callers should debounce this function (see server.js).
 *
 * On a 409 push conflict (concurrent write), automatically retries once
 * with a fresh commit id.
 *
 * @param {object} data - full in-memory data snapshot to persist
 * @returns {Promise<boolean>} true on success, false on failure
 */
async function saveData(data) {
    if (!isConfigured()) return false;
    try {
        const content = Buffer.from(JSON.stringify(data, null, 2), 'utf-8').toString('base64');
        const commitId = await getLatestCommitId();

        const buildPushBody = (objectId, changeType) => ({
            refUpdates: [{ name: `refs/heads/${BRANCH}`, oldObjectId: objectId }],
            commits: [{
                comment: `Weekend Support Tracker: data update ${new Date().toISOString()}`,
                changes: [{
                    changeType,
                    item: { path: DATA_PATH },
                    newContent: { content, contentType: 'base64Encoded' },
                }],
            }],
        });

        const pushPath =
            `/${ORG}/${encodeURIComponent(PROJECT)}/_apis/git/repositories/${encodeURIComponent(REPO)}` +
            `/pushes?api-version=${API_VERSION}`;

        let result = await adoRequest('POST', pushPath, buildPushBody(commitId, _fileExistsInRepo ? 'edit' : 'add'));

        if (result.status === 201) {
            _fileExistsInRepo = true;
            return true;
        }

        // 409 = concurrent push conflict — retry once with a fresh commit id
        if (result.status === 409) {
            console.warn('Azure DevOps: push conflict — retrying with fresh commit id');
            const freshId = await getLatestCommitId();
            result = await adoRequest('POST', pushPath, buildPushBody(freshId, 'edit'));
            if (result.status === 201) {
                _fileExistsInRepo = true;
                return true;
            }
        }

        console.error(`Azure DevOps saveData failed: HTTP ${result.status} — ${JSON.stringify(result.body)}`);
        return false;
    } catch (err) {
        console.error('Azure DevOps saveData error:', err.message);
        return false;
    }
}

module.exports = { isConfigured, loadData, saveData };
