// Generated by GitHub Copilot
const express = require('express');
const cors = require('cors');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');

const app = express();
const PORT = process.env.PORT || 5000;

// ── Middleware ────────────────────────────────────────────────
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));

// ── File Upload ──────────────────────────────────────────────
const uploadsDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir);

const storage = multer.diskStorage({
    destination: (_req, _file, cb) => cb(null, uploadsDir),
    filename: (_req, file, cb) => cb(null, `${Date.now()}-${file.originalname}`),
});
const upload = multer({
    storage,
    limits: { fileSize: 10 * 1024 * 1024 },
    fileFilter: (_req, file, cb) => {
        const allowed = /xlsx|xls|csv|pdf/;
        const ext = path.extname(file.originalname).toLowerCase().replace('.', '');
        cb(null, allowed.test(ext));
    },
});

// ── In-Memory Store ──────────────────────────────────────────
let entries = {};
let deletedItems = []; // { id, type:'entry'|'team'|'lineItem', data, deletedAt, parentInfo }

// Allowed users whitelist – only these enterprise IDs can sign in
const allowedUsers = [
    'arun.thangapandian', 'priya.sharma', 'rahul.verma',
    'sneha.patel', 'vikram.singh', 'amit.roy', 'neha.gupta',
    'ravi.shankar', 'sanjay.mehta', 'pooja.reddy',
    'karthik.rajan', 'deepa.nair', 'lakshmi', 'jeba', 'shini',
];

const releaseOwners = [
    { id: 'arun.thangapandian', name: 'Arun Thangapandian' },
    { id: 'priya.sharma', name: 'Priya Sharma' },
    { id: 'rahul.verma', name: 'Rahul Verma' },
    { id: 'sneha.patel', name: 'Sneha Patel' },
    { id: 'vikram.singh', name: 'Vikram Singh' },
];

const careerLevels = [
    'Analyst', 'Senior Analyst', 'Consultant',
    'Manager', 'Senior Manager', 'Associate Director',
];

// Employee directory for career level lookup by enterprise ID or name
const employeeDirectory = [
    { id: 'arun.thangapandian', name: 'Arun Thangapandian', careerLevel: 'Associate Director' },
    { id: 'priya.sharma', name: 'Priya Sharma', careerLevel: 'Senior Manager' },
    { id: 'rahul.verma', name: 'Rahul Verma', careerLevel: 'Manager' },
    { id: 'sneha.patel', name: 'Sneha Patel', careerLevel: 'Consultant' },
    { id: 'vikram.singh', name: 'Vikram Singh', careerLevel: 'Senior Analyst' },
    { id: 'amit.roy', name: 'Amit Roy', careerLevel: 'Senior Analyst' },
    { id: 'neha.gupta', name: 'Neha Gupta', careerLevel: 'Consultant' },
    { id: 'ravi.shankar', name: 'Ravi Shankar', careerLevel: 'Analyst' },
    { id: 'sanjay.mehta', name: 'Sanjay Mehta', careerLevel: 'Manager' },
    { id: 'pooja.reddy', name: 'Pooja Reddy', careerLevel: 'Analyst' },
    { id: 'karthik.rajan', name: 'Karthik Rajan', careerLevel: 'Senior Manager' },
    { id: 'deepa.nair', name: 'Deepa Nair', careerLevel: 'Manager' },
    { id: 'lakshmi', name: 'Lakshmi', careerLevel: 'Senior Analyst' },
    { id: 'jeba', name: 'Jeba', careerLevel: 'Analyst' },
    { id: 'shini', name: 'Shini', careerLevel: 'Consultant' },
];

// No seed data — only user-created entries are displayed

// ══════════════════════════════════════════════════════════════
// ROUTES
// ══════════════════════════════════════════════════════════════

// Auth validation – check if enterprise ID is in the allowed list
app.post('/api/auth/validate', (req, res) => {
    const { empId } = req.body;
    if (!empId) return res.status(400).json({ error: 'Employee ID is required' });
    const id = empId.trim().toLowerCase();
    const allowed = allowedUsers.includes(id);
    if (!allowed) return res.status(403).json({ error: 'Access denied. You are not authorised to access this application.' });
    res.json({ valid: true, empId: id });
});

app.get('/api/options/release-owners', (_r, res) => res.json(releaseOwners));
app.get('/api/options/career-levels', (_r, res) => res.json(careerLevels));

// Employee lookup by ID or name for career level
app.get('/api/options/employee-lookup', (req, res) => {
    const q = (req.query.q || '').trim().toLowerCase();
    if (!q) return res.json(null);
    const match = employeeDirectory.find(e =>
        e.id.toLowerCase() === q || e.name.toLowerCase() === q);
    res.json(match || null);
});
app.get('/api/options/employees', (_r, res) => res.json(employeeDirectory));

// ── Entries ──────────────────────────────────────────────────
app.get('/api/entries', (_r, res) => {
    const list = Object.values(entries)
        .map(e => ({ id: e.id, date: e.date, releaseOwner: e.releaseOwner, createdBy: e.createdBy }))
        .sort((a, b) => new Date(b.date) - new Date(a.date));
    res.json(list);
});

app.get('/api/entries/:id', (req, res) => {
    const e = entries[req.params.id];
    if (!e) return res.status(404).json({ error: 'Entry not found' });
    res.json(e);
});

app.post('/api/entries', upload.single('sanityFile'), (req, res) => {
    const { releaseOwner, date, createdBy } = req.body;
    if (!releaseOwner || !date) return res.status(400).json({ error: 'Release Owner and Date are required' });
    const existing = Object.values(entries).find(e => e.date === date);
    if (existing) return res.status(409).json({ error: 'Entry already exists for this date' });
    const id = uuidv4();
    entries[id] = {
        id, releaseOwner, date, sanityFile: req.file ? req.file.filename : null,
        createdBy: createdBy || 'UNKNOWN', teams: [],
    };
    res.status(201).json(entries[id]);
});

app.delete('/api/entries/:id', (req, res) => {
    if (!entries[req.params.id]) return res.status(404).json({ error: 'Entry not found' });
    // Soft-delete: move to deletedItems
    const entry = entries[req.params.id];
    deletedItems.push({
        id: uuidv4(), type: 'entry', data: JSON.parse(JSON.stringify(entry)),
        deletedAt: new Date().toISOString(), parentInfo: { date: entry.date, releaseOwner: entry.releaseOwner },
    });
    delete entries[req.params.id];
    res.json({ success: true });
});

// ── Teams ────────────────────────────────────────────────────
app.post('/api/entries/:id/teams', (req, res) => {
    const entry = entries[req.params.id];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const { teamName, leadName, totalCount, createdBy } = req.body;
    if (!teamName || !leadName) return res.status(400).json({ error: 'Team Name and Lead Name are required' });
    if (entry.teams.some(t => t.teamName.toLowerCase() === teamName.toLowerCase())) {
        return res.status(409).json({ error: `Team "${teamName}" already exists` });
    }
    const team = {
        id: uuidv4(), teamName, leadName, totalCount: Number(totalCount) || 0,
        createdDate: entry.date, createdBy: createdBy || 'UNKNOWN', lineItems: [],
    };
    entry.teams.push(team);
    res.status(201).json(team);
});

app.put('/api/entries/:eid/teams/:tid', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const idx = entry.teams.findIndex(t => t.id === req.params.tid);
    if (idx === -1) return res.status(404).json({ error: 'Team not found' });
    entry.teams[idx] = { ...entry.teams[idx], ...req.body, id: req.params.tid };
    res.json(entry.teams[idx]);
});

app.delete('/api/entries/:eid/teams/:tid', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (team) {
        deletedItems.push({
            id: uuidv4(), type: 'team', data: JSON.parse(JSON.stringify(team)),
            deletedAt: new Date().toISOString(),
            parentInfo: { entryId: entry.id, date: entry.date, teamName: team.teamName },
        });
    }
    entry.teams = entry.teams.filter(t => t.id !== req.params.tid);
    res.json({ success: true });
});

// ── Line Items ───────────────────────────────────────────────
app.post('/api/entries/:eid/teams/:tid/line-items', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (!team) return res.status(404).json({ error: 'Team not found' });
    const { name, careerLevel, allowanceCompoff } = req.body;
    if (!name) return res.status(400).json({ error: 'Name is required' });
    // Prevent duplicate names (case-insensitive)
    const duplicate = team.lineItems.find(li => li.name.toLowerCase() === name.trim().toLowerCase());
    if (duplicate) return res.status(409).json({ error: `"${name.trim()}" already exists in this team` });
    const item = { id: uuidv4(), name: name.trim(), careerLevel: careerLevel || '', allowanceCompoff: allowanceCompoff || 'Compoff', time: req.body.time || '' };
    team.lineItems.push(item);
    res.status(201).json(item);
});

app.post('/api/entries/:eid/teams/:tid/bulk-line-items', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (!team) return res.status(404).json({ error: 'Team not found' });
    const items = req.body.items;
    if (!Array.isArray(items)) return res.status(400).json({ error: 'items array required' });
    const added = [];
    const updated = [];
    items.forEach(({ name, careerLevel, allowanceCompoff }) => {
        if (!name || !name.trim()) return;
        const trimmedName = name.trim();
        const cl = careerLevel || '';
        const ac = allowanceCompoff || 'Compoff';
        // Check for existing item with same name (case-insensitive)
        const existingIdx = team.lineItems.findIndex(li =>
            li.name.toLowerCase() === trimmedName.toLowerCase());
        if (existingIdx !== -1) {
            // Overwrite existing item
            team.lineItems[existingIdx] = {
                ...team.lineItems[existingIdx],
                name: trimmedName,
                careerLevel: cl || team.lineItems[existingIdx].careerLevel,
                allowanceCompoff: ac,
            };
            updated.push(team.lineItems[existingIdx]);
        } else {
            const item = { id: uuidv4(), name: trimmedName, careerLevel: cl, allowanceCompoff: ac };
            team.lineItems.push(item);
            added.push(item);
        }
    });
    res.status(201).json({ added, updated, all: team.lineItems });
});

app.put('/api/entries/:eid/teams/:tid/line-items/:lid', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (!team) return res.status(404).json({ error: 'Team not found' });
    const idx = team.lineItems.findIndex(li => li.id === req.params.lid);
    if (idx === -1) return res.status(404).json({ error: 'Item not found' });
    team.lineItems[idx] = { ...team.lineItems[idx], ...req.body, id: req.params.lid };
    res.json(team.lineItems[idx]);
});

app.delete('/api/entries/:eid/teams/:tid/line-items/:lid', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (!team) return res.status(404).json({ error: 'Team not found' });
    const item = team.lineItems.find(li => li.id === req.params.lid);
    if (item) {
        deletedItems.push({
            id: uuidv4(), type: 'lineItem', data: JSON.parse(JSON.stringify(item)),
            deletedAt: new Date().toISOString(),
            parentInfo: { entryId: entry.id, teamId: team.id, date: entry.date, teamName: team.teamName, memberName: item.name },
        });
    }
    team.lineItems = team.lineItems.filter(li => li.id !== req.params.lid);
    res.json({ success: true });
});

app.put('/api/entries/:eid/teams/:tid/line-items', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (!team) return res.status(404).json({ error: 'Team not found' });
    const items = req.body.items;
    if (!Array.isArray(items)) return res.status(400).json({ error: 'items array required' });
    team.lineItems = items.map(li => ({
        id: li.id || uuidv4(), name: li.name || '', careerLevel: li.careerLevel || '',
        allowanceCompoff: li.allowanceCompoff || 'Compoff', time: li.time || '',
    }));
    res.json(team.lineItems);
});

// ── Bulk Teams Upload ────────────────────────────────────────
app.post('/api/entries/:id/bulk-teams', (req, res) => {
    const entry = entries[req.params.id];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const teams = req.body.teams;
    if (!Array.isArray(teams)) return res.status(400).json({ error: 'teams array required' });
    const { createdBy } = req.body;
    const added = [];
    const skipped = [];
    teams.forEach(({ teamName, leadName }) => {
        if (!teamName || !teamName.trim()) return;
        const tn = teamName.trim();
        const ln = (leadName || '').trim() || 'TBD';
        if (entry.teams.some(t => t.teamName.toLowerCase() === tn.toLowerCase())) {
            skipped.push(tn);
            return;
        }
        const team = {
            id: uuidv4(), teamName: tn, leadName: ln, totalCount: 0,
            createdDate: entry.date, createdBy: createdBy || 'UNKNOWN', lineItems: [],
        };
        entry.teams.push(team);
        added.push(team);
    });
    res.status(201).json({ added, skipped });
});

// ── Deleted Items ────────────────────────────────────────────
app.get('/api/deleted-items', (_r, res) => {
    res.json(deletedItems.sort((a, b) => new Date(b.deletedAt) - new Date(a.deletedAt)));
});

app.post('/api/deleted-items/:id/recover', (req, res) => {
    const idx = deletedItems.findIndex(d => d.id === req.params.id);
    if (idx === -1) return res.status(404).json({ error: 'Deleted item not found' });
    const item = deletedItems[idx];
    let recovered = false;
    if (item.type === 'entry') {
        // Restore entry
        entries[item.data.id] = JSON.parse(JSON.stringify(item.data));
        recovered = true;
    } else if (item.type === 'team') {
        const entry = entries[item.parentInfo.entryId];
        if (entry) {
            entry.teams.push(JSON.parse(JSON.stringify(item.data)));
            recovered = true;
        } else {
            return res.status(400).json({ error: 'Parent entry no longer exists. Recover the entry first.' });
        }
    } else if (item.type === 'lineItem') {
        const entry = entries[item.parentInfo.entryId];
        if (!entry) return res.status(400).json({ error: 'Parent entry no longer exists.' });
        const team = entry.teams.find(t => t.id === item.parentInfo.teamId);
        if (!team) return res.status(400).json({ error: 'Parent team no longer exists. Recover the team first.' });
        team.lineItems.push(JSON.parse(JSON.stringify(item.data)));
        recovered = true;
    }
    if (recovered) {
        deletedItems.splice(idx, 1);
        return res.json({ success: true });
    }
    res.status(400).json({ error: 'Could not recover item' });
});

app.delete('/api/deleted-items/:id', (req, res) => {
    const idx = deletedItems.findIndex(d => d.id === req.params.id);
    if (idx === -1) return res.status(404).json({ error: 'Deleted item not found' });
    deletedItems.splice(idx, 1);
    res.json({ success: true });
});

app.delete('/api/deleted-items', (_req, res) => {
    deletedItems = [];
    res.json({ success: true });
});

// ── Sanity File Upload for existing entry ────────────────────
app.post('/api/entries/:id/sanity-upload', upload.single('sanityFile'), (req, res) => {
    const entry = entries[req.params.id];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    if (!req.file) return res.status(400).json({ error: 'No file uploaded' });
    entry.sanityFile = req.file.filename;
    res.json({ sanityFile: entry.sanityFile });
});

// Generated by GitHub Copilot
/** Parse time range string and calculate total hours (server-side) */
function calcTotalHoursServer(timeStr) {
    if (!timeStr || !timeStr.includes('-')) return '';
    const parts = timeStr.split('-').map(s => s.trim());
    if (parts.length !== 2) return '';
    const parse12 = (s) => {
        const m = s.match(/^(\d{1,2})(?::(\d{2}))?\s*(AM|PM)$/i);
        if (!m) return NaN;
        let h = parseInt(m[1], 10);
        const min = m[2] ? parseInt(m[2], 10) : 0;
        const period = m[3].toUpperCase();
        if (h === 12) h = 0;
        if (period === 'PM') h += 12;
        return h + min / 60;
    };
    const start = parse12(parts[0]);
    const end = parse12(parts[1]);
    if (isNaN(start) || isNaN(end)) return '';
    let diff = end - start;
    if (diff <= 0) diff += 24;
    return `${diff % 1 === 0 ? diff : diff.toFixed(1)} hrs`;
}

// ── CSV Export (full entry) ──────────────────────────────────
app.get('/api/entries/:id/export', (req, res) => {
    const entry = entries[req.params.id];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const hdr = ['Release Owner', 'Release Date', 'Team Name', 'Lead Name', 'Member Name', 'Compoff/Allowance', 'Time', 'Total Hours', 'Created By'];
    const rows = [hdr];
    entry.teams.forEach(t => {
        if (t.lineItems.length === 0) {
            rows.push([entry.releaseOwner, entry.date, t.teamName, t.leadName, '', '', '', '', t.createdBy]);
        } else {
            t.lineItems.forEach((li, i) => {
                rows.push([
                    i === 0 ? entry.releaseOwner : '', i === 0 ? entry.date : '',
                    i === 0 ? t.teamName : '', i === 0 ? t.leadName : '',
                    li.name, li.allowanceCompoff, li.time || '',
                    calcTotalHoursServer(li.time || ''),
                    i === 0 ? t.createdBy : '',
                ]);
            });
        }
    });
    const csv = rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n');
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="release-${entry.date}.csv"`);
    res.send(csv);
});

// ── CSV Export (single team) ─────────────────────────────────
app.get('/api/entries/:eid/teams/:tid/export', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (!team) return res.status(404).json({ error: 'Team not found' });
    const hdr = ['Name', 'Compoff/Allowance', 'Time', 'Total Hours', 'Lead'];
    const rows = [hdr];
    team.lineItems.forEach(li => rows.push([li.name, li.allowanceCompoff, li.time || '', calcTotalHoursServer(li.time || ''), team.leadName]));
    const csv = rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n');
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="${team.teamName.replace(/\s+/g, '_')}-${entry.date}.csv"`);
    res.send(csv);
});

// Generated by GitHub Copilot
// Serve React production build in production
const frontendBuildPath = path.join(__dirname, '..', 'frontend', 'build');
if (fs.existsSync(frontendBuildPath)) {
    app.use(express.static(frontendBuildPath));
    app.get('*', (req, res) => {
        if (!req.path.startsWith('/api') && !req.path.startsWith('/uploads')) {
            res.sendFile(path.join(frontendBuildPath, 'index.html'));
        }
    });
}

app.listen(PORT, '0.0.0.0', () => console.log(`Backend running → http://0.0.0.0:${PORT}`));
