// Generated by GitHub Copilot
const express = require('express');
const cors = require('cors');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');
const { Pool } = require('pg');
const ExcelJS = require('exceljs');

const app = express();
const PORT = process.env.PORT || 5000;

// ── Middleware ────────────────────────────────────────────────
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));

// ── File Upload ──────────────────────────────────────────────
const uploadsDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir);

const storage = multer.diskStorage({
    destination: (_req, _file, cb) => cb(null, uploadsDir),
    filename: (_req, file, cb) => cb(null, `${Date.now()}-${file.originalname}`),
});
const upload = multer({
    storage,
    limits: { fileSize: 10 * 1024 * 1024 },
    fileFilter: (_req, file, cb) => {
        const allowed = /xlsx|xls|csv|pdf/;
        const ext = path.extname(file.originalname).toLowerCase().replace('.', '');
        cb(null, allowed.test(ext));
    },
});

// ── Persistent Store (PostgreSQL + JSON file fallback) ───────
let pool = null;
if (process.env.DATABASE_URL) {
    pool = new Pool({
        connectionString: process.env.DATABASE_URL,
        ssl: { rejectUnauthorized: false },
    });
    console.log('PostgreSQL configured via DATABASE_URL');
}

const DATA_FILE = path.join(__dirname, 'data.json');

function loadDataFromFile() {
    try {
        if (fs.existsSync(DATA_FILE)) {
            const raw = fs.readFileSync(DATA_FILE, 'utf-8');
            const parsed = JSON.parse(raw);
            return {
                entries: parsed.entries || {},
                deletedItems: parsed.deletedItems || [],
                employees: parsed.employees || null,
                changelogs: parsed.changelogs || {},
                resourceUploadHistory: parsed.resourceUploadHistory || [],
            };
        }
    } catch (err) {
        console.error('Failed to load data.json:', err.message);
    }
    return null;
}

async function loadDataFromDB(retries = 3) {
    if (!pool) return null;
    for (let attempt = 1; attempt <= retries; attempt++) {
        try {
            const res = await pool.query("SELECT key, value FROM app_data WHERE key IN ('entries','deletedItems','employees','changelogs','resourceUploadHistory')");
            const data = { entries: {}, deletedItems: [], employees: null, changelogs: {}, resourceUploadHistory: [] };
            res.rows.forEach(row => { data[row.key] = row.value; });
            console.log(`Loaded ${Object.keys(data.entries).length} entries, ${(data.employees || []).length} employees from PostgreSQL`);
            return data;
        } catch (err) {
            console.error(`PostgreSQL load attempt ${attempt}/${retries} failed:`, err.message);
            if (attempt < retries) await new Promise(r => setTimeout(r, 2000 * attempt));
        }
    }
    return null;
}

function saveData() {
    // File fallback (for local dev)
    try {
        fs.writeFileSync(DATA_FILE, JSON.stringify({ entries, deletedItems, employees, changelogs, resourceUploadHistory }, null, 2), 'utf-8');
    } catch (err) {
        console.error('Failed to save data.json:', err.message);
    }
    // PostgreSQL (async, fire-and-forget)
    if (pool) {
        const upsert = (key, value) =>
            pool.query(
                `INSERT INTO app_data (key, value) VALUES ($1, $2::jsonb) ON CONFLICT (key) DO UPDATE SET value = $2::jsonb`,
                [key, JSON.stringify(value)]
            ).catch(err => console.error(`PG save ${key}:`, err.message));
        upsert('entries', entries);
        upsert('deletedItems', deletedItems);
        upsert('employees', employees);
        upsert('changelogs', changelogs);
        upsert('resourceUploadHistory', resourceUploadHistory);
    }
}

let entries = {};
let deletedItems = [];
let changelogs = {};
let employees = [];
let resourceUploadHistory = [];

// Allowed users whitelist – only these enterprise IDs can sign in
const allowedUsers = [
    'arun.thangapandian', 'priya.sharma', 'rahul.verma',
    'sneha.patel', 'vikram.singh', 'amit.roy', 'neha.gupta',
    'ravi.shankar', 'sanjay.mehta', 'pooja.reddy',
    'karthik.rajan', 'deepa.nair', 'lakshmi', 'jeba', 'shini',
];

const releaseOwners = [
    { id: 'arun.thangapandian', name: 'Arun Thangapandian' },
    { id: 'priya.sharma', name: 'Priya Sharma' },
    { id: 'rahul.verma', name: 'Rahul Verma' },
    { id: 'sneha.patel', name: 'Sneha Patel' },
    { id: 'vikram.singh', name: 'Vikram Singh' },
];

const careerLevels = [
    'Analyst', 'Senior Analyst', 'Consultant',
    'Manager', 'Senior Manager', 'Associate Director',
];

// Employee directory for career level lookup by enterprise ID or name
const employeeDirectory = [
    { id: 'arun.thangapandian', name: 'Arun Thangapandian', careerLevel: 'Associate Director' },
    { id: 'priya.sharma', name: 'Priya Sharma', careerLevel: 'Senior Manager' },
    { id: 'rahul.verma', name: 'Rahul Verma', careerLevel: 'Manager' },
    { id: 'sneha.patel', name: 'Sneha Patel', careerLevel: 'Consultant' },
    { id: 'vikram.singh', name: 'Vikram Singh', careerLevel: 'Senior Analyst' },
    { id: 'amit.roy', name: 'Amit Roy', careerLevel: 'Senior Analyst' },
    { id: 'neha.gupta', name: 'Neha Gupta', careerLevel: 'Consultant' },
    { id: 'ravi.shankar', name: 'Ravi Shankar', careerLevel: 'Analyst' },
    { id: 'sanjay.mehta', name: 'Sanjay Mehta', careerLevel: 'Manager' },
    { id: 'pooja.reddy', name: 'Pooja Reddy', careerLevel: 'Analyst' },
    { id: 'karthik.rajan', name: 'Karthik Rajan', careerLevel: 'Senior Manager' },
    { id: 'deepa.nair', name: 'Deepa Nair', careerLevel: 'Manager' },
    { id: 'lakshmi', name: 'Lakshmi', careerLevel: 'Senior Analyst' },
    { id: 'jeba', name: 'Jeba', careerLevel: 'Analyst' },
    { id: 'shini', name: 'Shini', careerLevel: 'Consultant' },
];

// No seed data — only user-created entries are displayed

// ══════════════════════════════════════════════════════════════
// ROUTES
// ══════════════════════════════════════════════════════════════

// Auth validation – validates enterprise ID and returns career level
app.post('/api/auth/validate', (req, res) => {
    const { empId } = req.body;
    if (!empId) return res.status(400).json({ error: 'Employee ID is required' });
    const id = empId.trim().toLowerCase();
    if (!id) return res.status(400).json({ error: 'Employee ID is required' });

    // Look up career level from the loaded employee list
    const emp = employees.find(e =>
        (e.id || '').toLowerCase() === id || (e.name || '').toLowerCase() === id
    );
    const cl = emp ? parseInt(String(emp.careerLevel || '').replace(/[^0-9]/g, ''), 10) : NaN;

    // Block access for career level 10 and above (or unknown if employees list is loaded)
    if (employees.length > 0 && emp && !isNaN(cl) && cl >= 10) {
        return res.status(403).json({ error: 'Access denied. Career level 9 and below only.' });
    }

    res.json({ valid: true, empId: id, careerLevel: isNaN(cl) ? null : cl });
});

app.get('/api/options/release-owners', (_r, res) => res.json(releaseOwners));
app.get('/api/options/career-levels', (_r, res) => res.json(careerLevels));

// Employee lookup by ID or name for career level — uses the live uploaded list
app.get('/api/options/employee-lookup', (req, res) => {
    const q = (req.query.q || '').trim().toLowerCase();
    if (!q) return res.json(null);
    const match = employees.find(e =>
        (e.id || '').toLowerCase() === q || (e.name || '').toLowerCase() === q);
    res.json(match || null);
});
app.get('/api/options/employees', (_r, res) => res.json(employees));

// Get resource upload history
app.get('/api/options/resource-upload-history', (_r, res) => {
    res.json([...resourceUploadHistory].sort((a, b) => new Date(b.uploadedAt) - new Date(a.uploadedAt)));
});

// Replace employee directory from uploaded resource list (parsed on frontend)
app.post('/api/options/employees', (req, res) => {
    const body = req.body;
    // Accept both array (legacy) and { employees, uploadedBy, filename }
    let list, uploadedBy, filename;
    if (Array.isArray(body)) {
        list = body;
        uploadedBy = 'UNKNOWN';
        filename = 'unknown';
    } else {
        list = body.employees;
        uploadedBy = body.uploadedBy || 'UNKNOWN';
        filename = body.filename || 'unknown';
    }
    if (!Array.isArray(list) || list.length === 0)
        return res.status(400).json({ error: 'Array of employees required' });
    employees = list;
    resourceUploadHistory.push({
        id: uuidv4(),
        uploadedBy,
        filename,
        uploadedAt: new Date().toISOString(),
        count: list.length,
    });
    saveData();
    res.json({ success: true, count: list.length });
});

// ── Entries ──────────────────────────────────────────────────
app.get('/api/entries', (_r, res) => {
    const list = Object.values(entries)
        .map(e => ({ id: e.id, date: e.date, releaseOwner: e.releaseOwner, createdBy: e.createdBy }))
        .sort((a, b) => new Date(b.date) - new Date(a.date));
    res.json(list);
});

app.get('/api/entries/:id', (req, res) => {
    const e = entries[req.params.id];
    if (!e) return res.status(404).json({ error: 'Entry not found' });
    res.json(e);
});

app.post('/api/entries', upload.single('sanityFile'), (req, res) => {
    const { releaseOwner, date, createdBy } = req.body;
    if (!releaseOwner || !date) return res.status(400).json({ error: 'Release Owner and Date are required' });
    const existing = Object.values(entries).find(e => e.date === date);
    if (existing) return res.status(409).json({ error: 'Entry already exists for this date' });
    const id = uuidv4();
    entries[id] = {
        id, releaseOwner, date, sanityFile: req.file ? req.file.filename : null,
        createdBy: createdBy || 'UNKNOWN', teams: [],
    };
    saveData();
    res.status(201).json(entries[id]);
});

// Update entry metadata (releaseOwner, date) — teams/lineItems unchanged
app.put('/api/entries/:id', (req, res) => {
    const entry = entries[req.params.id];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const { releaseOwner, date, changedBy } = req.body;
    const by = (changedBy || 'UNKNOWN').trim();
    if (!changelogs[req.params.id]) changelogs[req.params.id] = [];
    if (releaseOwner !== undefined) {
        if (!releaseOwner.trim()) return res.status(400).json({ error: 'Release Owner cannot be empty' });
        if (entry.releaseOwner !== releaseOwner.trim()) {
            changelogs[req.params.id].push({ id: uuidv4(), type: 'ownerChange', oldValue: entry.releaseOwner, newValue: releaseOwner.trim(), changedBy: by, timestamp: new Date().toISOString() });
        }
        entry.releaseOwner = releaseOwner.trim();
    }
    if (date !== undefined) {
        if (!date.trim()) return res.status(400).json({ error: 'Date cannot be empty' });
        // Check for duplicate date (excluding this entry)
        const dup = Object.values(entries).find(e => e.date === date.trim() && e.id !== entry.id);
        if (dup) return res.status(409).json({ error: 'Another entry already exists for this date' });
        if (entry.date !== date.trim()) {
            changelogs[req.params.id].push({ id: uuidv4(), type: 'dateChange', oldValue: entry.date, newValue: date.trim(), changedBy: by, timestamp: new Date().toISOString() });
        }
        entry.date = date.trim();
    }
    saveData();
    res.json(entry);
});

app.delete('/api/entries/:id', (req, res) => {
    if (!entries[req.params.id]) return res.status(404).json({ error: 'Entry not found' });
    // Soft-delete: move to deletedItems
    const entry = entries[req.params.id];
    deletedItems.push({
        id: uuidv4(), type: 'entry', data: JSON.parse(JSON.stringify(entry)),
        deletedAt: new Date().toISOString(), parentInfo: { date: entry.date, releaseOwner: entry.releaseOwner },
    });
    delete entries[req.params.id];
    saveData();
    res.json({ success: true });
});

// ── Teams ────────────────────────────────────────────────────
app.post('/api/entries/:id/teams', (req, res) => {
    const entry = entries[req.params.id];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const { teamName, leadName, totalCount, createdBy } = req.body;
    if (!teamName || !leadName) return res.status(400).json({ error: 'Team Name and Lead Name are required' });
    if (entry.teams.some(t => t.teamName.toLowerCase() === teamName.toLowerCase())) {
        return res.status(409).json({ error: `Team "${teamName}" already exists` });
    }
    const team = {
        id: uuidv4(), teamName, leadName, totalCount: Number(totalCount) || 0,
        createdDate: entry.date, createdBy: createdBy || 'UNKNOWN', lineItems: [],
    };
    entry.teams.push(team);
    saveData();
    res.status(201).json(team);
});

app.put('/api/entries/:eid/teams/:tid', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const idx = entry.teams.findIndex(t => t.id === req.params.tid);
    if (idx === -1) return res.status(404).json({ error: 'Team not found' });
    entry.teams[idx] = { ...entry.teams[idx], ...req.body, id: req.params.tid };
    saveData();
    res.json(entry.teams[idx]);
});

app.delete('/api/entries/:eid/teams/:tid', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (team) {
        deletedItems.push({
            id: uuidv4(), type: 'team', data: JSON.parse(JSON.stringify(team)),
            deletedAt: new Date().toISOString(),
            parentInfo: { entryId: entry.id, date: entry.date, teamName: team.teamName },
        });
    }
    entry.teams = entry.teams.filter(t => t.id !== req.params.tid);
    saveData();
    res.json({ success: true });
});

// ── Line Items ───────────────────────────────────────────────
app.post('/api/entries/:eid/teams/:tid/line-items', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (!team) return res.status(404).json({ error: 'Team not found' });
    const { name, careerLevel, allowanceCompoff } = req.body;
    if (!name) return res.status(400).json({ error: 'Name is required' });
    // Prevent duplicate names (case-insensitive)
    const duplicate = team.lineItems.find(li => li.name.toLowerCase() === name.trim().toLowerCase());
    if (duplicate) return res.status(409).json({ error: `"${name.trim()}" already exists in this team` });
    const item = { id: uuidv4(), name: name.trim(), careerLevel: careerLevel || '', allowanceCompoff: allowanceCompoff || 'Compoff', time: req.body.time || '' };
    team.lineItems.push(item);
    saveData();
    res.status(201).json(item);
});

app.post('/api/entries/:eid/teams/:tid/bulk-line-items', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (!team) return res.status(404).json({ error: 'Team not found' });
    const items = req.body.items;
    if (!Array.isArray(items)) return res.status(400).json({ error: 'items array required' });
    const added = [];
    const updated = [];
    items.forEach(({ name, careerLevel, supervisor, allowanceCompoff }) => {
        if (!name || !name.trim()) return;
        const trimmedName = name.trim();
        const cl = careerLevel || '';
        const sv = supervisor || '';
        const ac = allowanceCompoff || 'Compoff';
        // Check for existing item with same name (case-insensitive)
        const existingIdx = team.lineItems.findIndex(li =>
            li.name.toLowerCase() === trimmedName.toLowerCase());
        if (existingIdx !== -1) {
            // Overwrite existing item
            team.lineItems[existingIdx] = {
                ...team.lineItems[existingIdx],
                name: trimmedName,
                careerLevel: cl || team.lineItems[existingIdx].careerLevel,
                supervisor: sv || team.lineItems[existingIdx].supervisor || '',
                allowanceCompoff: ac,
            };
            updated.push(team.lineItems[existingIdx]);
        } else {
            const item = { id: uuidv4(), name: trimmedName, careerLevel: cl, supervisor: sv, allowanceCompoff: ac };
            team.lineItems.push(item);
            added.push(item);
        }
    });
    saveData();
    res.status(201).json({ added, updated, all: team.lineItems });
});

app.put('/api/entries/:eid/teams/:tid/line-items/:lid', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (!team) return res.status(404).json({ error: 'Team not found' });
    const idx = team.lineItems.findIndex(li => li.id === req.params.lid);
    if (idx === -1) return res.status(404).json({ error: 'Item not found' });
    team.lineItems[idx] = { ...team.lineItems[idx], ...req.body, id: req.params.lid };
    saveData();
    res.json(team.lineItems[idx]);
});

app.delete('/api/entries/:eid/teams/:tid/line-items/:lid', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (!team) return res.status(404).json({ error: 'Team not found' });
    const item = team.lineItems.find(li => li.id === req.params.lid);
    if (item) {
        deletedItems.push({
            id: uuidv4(), type: 'lineItem', data: JSON.parse(JSON.stringify(item)),
            deletedAt: new Date().toISOString(),
            parentInfo: { entryId: entry.id, teamId: team.id, date: entry.date, teamName: team.teamName, memberName: item.name },
        });
    }
    team.lineItems = team.lineItems.filter(li => li.id !== req.params.lid);
    saveData();
    res.json({ success: true });
});

app.put('/api/entries/:eid/teams/:tid/line-items', (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (!team) return res.status(404).json({ error: 'Team not found' });
    const items = req.body.items;
    if (!Array.isArray(items)) return res.status(400).json({ error: 'items array required' });
    team.lineItems = items.map(li => ({
        id: li.id || uuidv4(), name: li.name || '', careerLevel: li.careerLevel || '',
        supervisor: li.supervisor || '',
        allowanceCompoff: li.allowanceCompoff || 'Compoff', time: li.time || '',
        notes: li.notes || '',
    }));
    saveData();
    res.json(team.lineItems);
});

// ── Bulk Teams Upload ────────────────────────────────────────
app.post('/api/entries/:id/bulk-teams', (req, res) => {
    const entry = entries[req.params.id];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const teams = req.body.teams;
    if (!Array.isArray(teams)) return res.status(400).json({ error: 'teams array required' });
    const { createdBy } = req.body;
    const added = [];
    const skipped = [];
    teams.forEach(({ teamName, leadName }) => {
        if (!teamName || !teamName.trim()) return;
        const tn = teamName.trim();
        const ln = (leadName || '').trim() || 'TBD';
        if (entry.teams.some(t => t.teamName.toLowerCase() === tn.toLowerCase())) {
            skipped.push(tn);
            return;
        }
        const team = {
            id: uuidv4(), teamName: tn, leadName: ln, totalCount: 0,
            createdDate: entry.date, createdBy: createdBy || 'UNKNOWN', lineItems: [],
        };
        entry.teams.push(team);
        added.push(team);
    });
    saveData();
    res.status(201).json({ added, skipped });
});

// ── Deleted Items ────────────────────────────────────────────
app.get('/api/deleted-items', (_r, res) => {
    res.json(deletedItems.sort((a, b) => new Date(b.deletedAt) - new Date(a.deletedAt)));
});

app.post('/api/deleted-items/:id/recover', (req, res) => {
    const idx = deletedItems.findIndex(d => d.id === req.params.id);
    if (idx === -1) return res.status(404).json({ error: 'Deleted item not found' });
    const item = deletedItems[idx];
    let recovered = false;
    if (item.type === 'entry') {
        // Restore entry
        entries[item.data.id] = JSON.parse(JSON.stringify(item.data));
        recovered = true;
    } else if (item.type === 'team') {
        const entry = entries[item.parentInfo.entryId];
        if (entry) {
            entry.teams.push(JSON.parse(JSON.stringify(item.data)));
            recovered = true;
        } else {
            return res.status(400).json({ error: 'Parent entry no longer exists. Recover the entry first.' });
        }
    } else if (item.type === 'lineItem') {
        const entry = entries[item.parentInfo.entryId];
        if (!entry) return res.status(400).json({ error: 'Parent entry no longer exists.' });
        const team = entry.teams.find(t => t.id === item.parentInfo.teamId);
        if (!team) return res.status(400).json({ error: 'Parent team no longer exists. Recover the team first.' });
        team.lineItems.push(JSON.parse(JSON.stringify(item.data)));
        recovered = true;
    }
    if (recovered) {
        deletedItems.splice(idx, 1);
        saveData();
        return res.json({ success: true });
    }
    res.status(400).json({ error: 'Could not recover item' });
});

app.delete('/api/deleted-items/:id', (req, res) => {
    const idx = deletedItems.findIndex(d => d.id === req.params.id);
    if (idx === -1) return res.status(404).json({ error: 'Deleted item not found' });
    deletedItems.splice(idx, 1);
    saveData();
    res.json({ success: true });
});

app.delete('/api/deleted-items', (_req, res) => {
    deletedItems = [];
    saveData();
    res.json({ success: true });
});

// ── Sanity File Upload for existing entry ────────────────────
app.post('/api/entries/:id/sanity-upload', upload.single('sanityFile'), (req, res) => {
    const entry = entries[req.params.id];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    if (!req.file) return res.status(400).json({ error: 'No file uploaded' });
    const by = (req.body && req.body.changedBy || 'UNKNOWN').trim();
    if (!changelogs[req.params.id]) changelogs[req.params.id] = [];
    changelogs[req.params.id].push({ id: uuidv4(), type: 'sanityUpload', oldValue: entry.sanityFile || '', newValue: req.file.filename, changedBy: by, timestamp: new Date().toISOString() });
    entry.sanityFile = req.file.filename;
    saveData();
    res.json({ sanityFile: entry.sanityFile });
});

// ── Change History ───────────────────────────────────────────
app.get('/api/entries/:id/history', (req, res) => {
    if (!entries[req.params.id]) return res.status(404).json({ error: 'Entry not found' });
    const changelog = changelogs[req.params.id] || [];
    // Normalize: support legacy records stored with old/new/date field names
    const normalized = changelog.map(h => ({
        id: h.id,
        type: h.type,
        oldValue: h.oldValue !== undefined ? h.oldValue : (h.old !== undefined ? h.old : ''),
        newValue: h.newValue !== undefined ? h.newValue : (h.new !== undefined ? h.new : ''),
        changedBy: h.changedBy,
        timestamp: h.timestamp || h.date || new Date().toISOString(),
    }));
    res.json(normalized);
});

// Generated by GitHub Copilot
/** Parse time range string and calculate total hours (server-side) */
function calcTotalHoursServer(timeStr) {
    if (!timeStr || !timeStr.includes('-')) return '';
    const parts = timeStr.split('-').map(s => s.trim());
    if (parts.length !== 2) return '';
    const parse12 = (s) => {
        const m = s.match(/^(\d{1,2})(?::(\d{2}))?\s*(AM|PM)$/i);
        if (!m) return NaN;
        let h = parseInt(m[1], 10);
        const min = m[2] ? parseInt(m[2], 10) : 0;
        const period = m[3].toUpperCase();
        if (h === 12) h = 0;
        if (period === 'PM') h += 12;
        return h + min / 60;
    };
    const start = parse12(parts[0]);
    const end = parse12(parts[1]);
    if (isNaN(start) || isNaN(end)) return '';
    let diff = end - start;
    if (diff <= 0) diff += 24;
    return `${diff % 1 === 0 ? diff : diff.toFixed(1)} hrs`;
}

// Generated by GitHub Copilot
/** Determine support type label from total hours string */
function getSupportTypeServer(hrsStr) {
    if (!hrsStr) return '';
    const num = parseFloat(hrsStr);
    if (isNaN(num)) return '';
    if (num >= 6) return 'On Call Primary Support';
    if (num >= 4) return 'On Call Secondary Support';
    return '';
}

// Generated by GitHub Copilot
/** Apply standard header + row styling to a sheet */
function styleExcelSheet(sheet, columns, rowDataList, getRowBg) {
    const HEADER_BG = 'FF3730A3';
    const BORDER = { style: 'thin', color: { argb: 'FF4F46E5' } };
    const ROW_BORDER = { style: 'hair', color: { argb: 'FFD1D5DB' } };

    const headerRow = sheet.getRow(1);
    for (let col = 1; col <= columns.length; col++) {
        const cell = headerRow.getCell(col);
        cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: HEADER_BG } };
        cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
        cell.border = { top: BORDER, bottom: BORDER, left: BORDER, right: BORDER };
    }
    headerRow.height = 22;

    rowDataList.forEach((rowData, idx) => {
        const row = sheet.addRow(rowData);
        const bgColor = getRowBg(rowData, idx);
        row.eachCell({ includeEmpty: true }, cell => {
            cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: bgColor } };
            cell.alignment = { vertical: 'middle', wrapText: false };
            cell.border = { top: ROW_BORDER, bottom: ROW_BORDER, left: ROW_BORDER, right: ROW_BORDER };
        });
        row.height = 18;
    });

    sheet.views = [{ state: 'frozen', ySplit: 1 }];
}

// ── Excel Export (full entry) ────────────────────────────────
app.get('/api/entries/:id/export', async (req, res) => {
    const entry = entries[req.params.id];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });

    const ALLOWANCE_BG = 'FFD1FAE5';
    const COMPOFF_BG = 'FFFEF3C7';
    const ALT = ['FFEEF2FF', 'FFF5F3FF'];

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Weekend Support Tracker';
    const sheet = workbook.addWorksheet('Release');

    const columns = [
        { header: 'Release Owner', key: 'releaseOwner', width: 22 },
        { header: 'Release Date', key: 'releaseDate', width: 14 },
        { header: 'Team Name', key: 'teamName', width: 22 },
        { header: 'Lead Name', key: 'leadName', width: 22 },
        { header: 'Member Name', key: 'memberName', width: 28 },
        { header: 'Login Time', key: 'loginTime', width: 14 },
        { header: 'Logout Time', key: 'logoutTime', width: 14 },
        { header: 'Total Hours', key: 'totalHours', width: 14 },
        { header: 'Compoff/Allowance', key: 'type', width: 20 },
        { header: 'Created By', key: 'createdBy', width: 22 },
    ];
    sheet.columns = columns;

    const rowDataList = [];
    entry.teams.forEach(t => {
        if (t.lineItems.length === 0) {
            rowDataList.push({ releaseOwner: entry.releaseOwner, releaseDate: entry.date, teamName: t.teamName, leadName: t.leadName, memberName: '', loginTime: '', logoutTime: '', totalHours: '', type: '', createdBy: t.createdBy });
        } else {
            t.lineItems.forEach((li, i) => {
                const parts = (li.time || '').split('-').map(s => s.trim());
                rowDataList.push({
                    releaseOwner: i === 0 ? entry.releaseOwner : '',
                    releaseDate: i === 0 ? entry.date : '',
                    teamName: i === 0 ? t.teamName : '',
                    leadName: i === 0 ? t.leadName : '',
                    memberName: li.name,
                    loginTime: parts[0] || '',
                    logoutTime: parts[1] || '',
                    totalHours: calcTotalHoursServer(li.time || ''),
                    type: li.allowanceCompoff || '',
                    createdBy: i === 0 ? t.createdBy : '',
                    _type: li.allowanceCompoff,
                });
            });
        }
    });

    styleExcelSheet(sheet, columns, rowDataList, (rowData, idx) =>
        rowData._type === 'Allowance' ? ALLOWANCE_BG : rowData._type === 'Compoff' ? COMPOFF_BG : ALT[idx % 2]);

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="release-${entry.date}.xlsx"`);
    await workbook.xlsx.write(res);
    res.end();
});

// ── Excel Export (single team) ──────────────────────────────
app.get('/api/entries/:eid/teams/:tid/export', async (req, res) => {
    const entry = entries[req.params.eid];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const team = entry.teams.find(t => t.id === req.params.tid);
    if (!team) return res.status(404).json({ error: 'Team not found' });

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Weekend Support Tracker';
    const sheet = workbook.addWorksheet(team.teamName || 'Team');

    const columns = [
        { header: 'Name', key: 'name', width: 28 },
        { header: 'Career Level', key: 'careerLevel', width: 14 },
        { header: 'Supervisor', key: 'supervisor', width: 22 },
        { header: 'Login Time', key: 'loginTime', width: 14 },
        { header: 'Logout Time', key: 'logoutTime', width: 14 },
        { header: 'Total Hours', key: 'totalHours', width: 14 },
        { header: 'Compoff/Allowance', key: 'type', width: 20 },
        { header: 'Lead', key: 'lead', width: 22 },
    ];
    sheet.columns = columns;

    const ALLOWANCE_BG = 'FFD1FAE5';
    const COMPOFF_BG = 'FFFEF3C7';
    const ALT = ['FFEEF2FF', 'FFF5F3FF'];

    const rowDataList = team.lineItems.map(li => {
        const parts = (li.time || '').split('-').map(s => s.trim());
        return {
            name: li.name || '',
            careerLevel: li.careerLevel || '',
            supervisor: li.supervisor || '',
            loginTime: parts[0] || '',
            logoutTime: parts[1] || '',
            totalHours: calcTotalHoursServer(li.time || ''),
            type: li.allowanceCompoff || '',
            lead: team.leadName || '',
            _type: li.allowanceCompoff,
        };
    });

    styleExcelSheet(sheet, columns, rowDataList, (row, idx) =>
        row._type === 'Allowance' ? ALLOWANCE_BG : row._type === 'Compoff' ? COMPOFF_BG : ALT[idx % 2]);

    const safeName = team.teamName.replace(/[\\/:*?"<>|]/g, '_');
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="${safeName}-${entry.date}.xlsx"`);
    await workbook.xlsx.write(res);
    res.end();
});

// ── Excel Export (summary dialog: allowance / compoff / members / teams) ──
app.get('/api/entries/:id/dialog-export/:type', async (req, res) => {
    const entry = entries[req.params.id];
    if (!entry) return res.status(404).json({ error: 'Entry not found' });
    const exportType = req.params.type;

    const ALLOWANCE_BG = 'FFD1FAE5';
    const COMPOFF_BG = 'FFFEF3C7';
    const ALT = ['FFEEF2FF', 'FFF5F3FF'];

    const teams = entry.teams || [];
    const allItems = teams.flatMap(t => (t.lineItems || []).map(li => ({ ...li, teamName: t.teamName, leadName: t.leadName })));
    const allowanceItems = allItems.filter(li => li.allowanceCompoff === 'Allowance');
    const compoffItems = allItems.filter(li => li.allowanceCompoff === 'Compoff');

    let sheetName, columns, rowDataList, getRowBg;

    if (exportType === 'allowance') {
        sheetName = 'Shift Allowance';
        columns = [
            { header: '#', key: 'num', width: 5 },
            { header: 'Name', key: 'name', width: 28 },
            { header: 'Career Level', key: 'careerLevel', width: 14 },
            { header: 'Supervisor', key: 'supervisor', width: 22 },
            { header: 'Team', key: 'team', width: 20 },
            { header: 'Lead', key: 'lead', width: 22 },
            { header: 'Login Time', key: 'loginTime', width: 14 },
            { header: 'Logout Time', key: 'logoutTime', width: 14 },
            { header: 'Total Hours', key: 'totalHours', width: 14 },
            { header: 'Support type to be charged in myte', key: 'supportType', width: 38 },
        ];
        rowDataList = allowanceItems.map((li, i) => {
            const parts = (li.time || '').split('-').map(s => s.trim());
            const hrs = calcTotalHoursServer(li.time || '');
            return { num: i + 1, name: li.name, careerLevel: li.careerLevel || '', supervisor: li.supervisor || '', team: li.teamName, lead: li.leadName, loginTime: parts[0] || '', logoutTime: parts[1] || '', totalHours: hrs, supportType: getSupportTypeServer(hrs) };
        });
        getRowBg = () => ALLOWANCE_BG;
    } else if (exportType === 'compoff') {
        sheetName = 'Comp-off';
        columns = [
            { header: '#', key: 'num', width: 5 },
            { header: 'Name', key: 'name', width: 28 },
            { header: 'Career Level', key: 'careerLevel', width: 14 },
            { header: 'Supervisor', key: 'supervisor', width: 22 },
            { header: 'Team', key: 'team', width: 20 },
            { header: 'Lead', key: 'lead', width: 22 },
            { header: 'Login Time', key: 'loginTime', width: 14 },
            { header: 'Logout Time', key: 'logoutTime', width: 14 },
            { header: 'Total Hours', key: 'totalHours', width: 14 },
        ];
        rowDataList = compoffItems.map((li, i) => {
            const parts = (li.time || '').split('-').map(s => s.trim());
            const hrs = calcTotalHoursServer(li.time || '');
            return { num: i + 1, name: li.name, careerLevel: li.careerLevel || '', supervisor: li.supervisor || '', team: li.teamName, lead: li.leadName, loginTime: parts[0] || '', logoutTime: parts[1] || '', totalHours: hrs };
        });
        getRowBg = () => COMPOFF_BG;
    } else if (exportType === 'members') {
        sheetName = 'All Members';
        columns = [
            { header: '#', key: 'num', width: 5 },
            { header: 'Name', key: 'name', width: 28 },
            { header: 'Career Level', key: 'careerLevel', width: 14 },
            { header: 'Supervisor', key: 'supervisor', width: 22 },
            { header: 'Team', key: 'team', width: 20 },
            { header: 'Lead', key: 'lead', width: 22 },
            { header: 'Login Time', key: 'loginTime', width: 14 },
            { header: 'Logout Time', key: 'logoutTime', width: 14 },
            { header: 'Total Hours', key: 'totalHours', width: 14 },
            { header: 'Type', key: 'type', width: 16 },
        ];
        rowDataList = allItems.map((li, i) => {
            const parts = (li.time || '').split('-').map(s => s.trim());
            const hrs = calcTotalHoursServer(li.time || '');
            return { num: i + 1, name: li.name, careerLevel: li.careerLevel || '', supervisor: li.supervisor || '', team: li.teamName, lead: li.leadName, loginTime: parts[0] || '', logoutTime: parts[1] || '', totalHours: hrs, type: li.allowanceCompoff || '', _type: li.allowanceCompoff };
        });
        getRowBg = (row, idx) => row._type === 'Allowance' ? ALLOWANCE_BG : row._type === 'Compoff' ? COMPOFF_BG : ALT[idx % 2];
    } else if (exportType === 'teams') {
        sheetName = 'Teams';
        columns = [
            { header: '#', key: 'num', width: 5 },
            { header: 'Team Name', key: 'teamName', width: 28 },
            { header: 'Lead', key: 'lead', width: 22 },
            { header: 'Members', key: 'members', width: 12 },
        ];
        rowDataList = teams.map((t, i) => ({ num: i + 1, teamName: t.teamName, lead: t.leadName, members: (t.lineItems || []).length }));
        getRowBg = (_, idx) => ALT[idx % 2];
    } else {
        return res.status(400).json({ error: 'Unknown export type' });
    }

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Weekend Support Tracker';
    const sheet = workbook.addWorksheet(sheetName);
    sheet.columns = columns;

    styleExcelSheet(sheet, columns, rowDataList, getRowBg);

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="${exportType}-${entry.date}.xlsx"`);
    await workbook.xlsx.write(res);
    res.end();
});

// Generated by GitHub Copilot
// Serve React production build in production
const frontendBuildPath = path.join(__dirname, '..', 'frontend', 'build');
if (fs.existsSync(frontendBuildPath)) {
    app.use(express.static(frontendBuildPath));
    // Catchall: serve index.html for any non-API, non-upload route (SPA routing)
    app.get('*', (req, res, next) => {
        if (req.path.startsWith('/api') || req.path.startsWith('/uploads')) {
            return next();
        }
        res.sendFile(path.join(frontendBuildPath, 'index.html'));
    });
}

// ── Start server with async data load ────────────────────────
async function startServer() {
    // Init PostgreSQL table if available
    if (pool) {
        try {
            await pool.query(`CREATE TABLE IF NOT EXISTS app_data (key TEXT PRIMARY KEY, value JSONB NOT NULL DEFAULT '{}')`);
            console.log('PostgreSQL table ready');
        } catch (err) {
            console.error('PostgreSQL init failed:', err.message);
            pool = null;
        }
    }

    // Load data: prefer PostgreSQL, fallback to file
    const dbData = await loadDataFromDB();
    const fileData = loadDataFromFile();
    const data = dbData || fileData || { entries: {}, deletedItems: [], employees: null, changelogs: {} };

    entries = data.entries || {};
    deletedItems = data.deletedItems || [];
    changelogs = data.changelogs || {};
    employees = data.employees || [];
    resourceUploadHistory = data.resourceUploadHistory || [];

    // If employees is still empty (no resource list uploaded yet), start with empty —
    // do NOT fall back to the hardcoded sample list so uploaded data is never overwritten.

    // If employees are loaded but no upload history exists (e.g. uploaded before history tracking),
    // synthesize a record so the UI shows the currently active list
    if (employees.length > 0 && resourceUploadHistory.length === 0) {
        resourceUploadHistory.push({
            id: uuidv4(),
            uploadedBy: 'system',
            filename: 'Pre-existing resource list',
            uploadedAt: new Date().toISOString(),
            count: employees.length,
        });
        saveData();
    }

    console.log(`Loaded ${Object.keys(entries).length} entries, ${deletedItems.length} deleted items`);

    app.listen(PORT, '0.0.0.0', () => console.log(`Server running on port ${PORT}`));
}

startServer().catch(err => {
    console.error('Failed to start server:', err);
    process.exit(1);
});
