// Generated by GitHub Copilot
/**
 * Azure Blob Storage client factory for Weekend Support Tracker.
 *
 * Authentication (evaluated in priority order):
 *   1. AZURE_STORAGE_CONNECTION_STRING  — full connection string (recommended for Render / local dev)
 *   2. AZURE_STORAGE_ACCOUNT_NAME + AZURE_STORAGE_ACCOUNT_KEY  — explicit account credentials
 *
 * Environment variables:
 *   AZURE_STORAGE_CONNECTION_STRING  — Storage account connection string
 *   AZURE_STORAGE_ACCOUNT_NAME       — Storage account name (alternative auth)
 *   AZURE_STORAGE_ACCOUNT_KEY        — Storage account key (alternative auth)
 *   AZURE_STORAGE_CONTAINER          — Blob container name (default: weekend-support-data)
 *
 * Security note: Never commit secrets to source control. Store them in Render's
 * environment variables panel (encrypted at rest) or Azure Key Vault. The PAT /
 * connection string should only be present in AZURE_STORAGE_CONNECTION_STRING.
 */
const { BlobServiceClient, StorageSharedKeyCredential } = require('@azure/storage-blob');

const CONTAINER_NAME = process.env.AZURE_STORAGE_CONTAINER || 'weekend-support-data';

/** Returns true when Azure Blob Storage is properly configured. */
function isConfigured() {
    return !!(
        process.env.AZURE_STORAGE_CONNECTION_STRING ||
        (process.env.AZURE_STORAGE_ACCOUNT_NAME && process.env.AZURE_STORAGE_ACCOUNT_KEY)
    );
}

/**
 * Build an authenticated BlobServiceClient.
 * @returns {BlobServiceClient}
 * @throws {Error} when credentials are not set
 */
function buildBlobServiceClient() {
    if (process.env.AZURE_STORAGE_CONNECTION_STRING) {
        return BlobServiceClient.fromConnectionString(process.env.AZURE_STORAGE_CONNECTION_STRING);
    }
    if (process.env.AZURE_STORAGE_ACCOUNT_NAME && process.env.AZURE_STORAGE_ACCOUNT_KEY) {
        const cred = new StorageSharedKeyCredential(
            process.env.AZURE_STORAGE_ACCOUNT_NAME,
            process.env.AZURE_STORAGE_ACCOUNT_KEY
        );
        return new BlobServiceClient(
            `https://${process.env.AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net`,
            cred
        );
    }
    throw new Error(
        'Azure Blob Storage credentials not set. ' +
        'Configure AZURE_STORAGE_CONNECTION_STRING or both ' +
        'AZURE_STORAGE_ACCOUNT_NAME and AZURE_STORAGE_ACCOUNT_KEY.'
    );
}

// Singleton container client — initialised lazily on first request
let _containerClient = null;

/**
 * Returns (and lazily creates) an authenticated ContainerClient.
 * Creates the container if it does not already exist.
 * @returns {Promise<import('@azure/storage-blob').ContainerClient>}
 */
async function getContainerClient() {
    if (_containerClient) return _containerClient;
    const serviceClient = buildBlobServiceClient();
    const client = serviceClient.getContainerClient(CONTAINER_NAME);
    await client.createIfNotExists();
    _containerClient = client;
    console.log(`Azure Blob Storage ready — container: ${CONTAINER_NAME}`);
    return _containerClient;
}

/** Reset the cached container client (useful for testing). */
function resetClient() {
    _containerClient = null;
}

module.exports = { isConfigured, getContainerClient, resetClient, CONTAINER_NAME };
