// Generated by GitHub Copilot
/**
 * One-time data migration script — local data.json → Azure Blob Storage
 *
 * Run once after setting up your Azure Storage account to upload any
 * data previously persisted in the local 'data.json' file.
 *
 * Usage:
 *   cd backend
 *   AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;..." node azure/migrate.js
 *
 * Optional flags:
 *   --dry-run   Validate credentials and data shape without actually uploading
 *   --force     Overwrite Azure blob even if it already contains data
 *
 * Environment variables required:
 *   AZURE_STORAGE_CONNECTION_STRING  — Azure Storage connection string
 *   AZURE_STORAGE_CONTAINER          — Container name (default: weekend-support-data)
 *   AZURE_STORAGE_BLOB_NAME          — Blob name (default: data.json)
 */
'use strict';

const fs = require('fs');
const path = require('path');

// Load environment from .env if present (local dev convenience)
const dotenvPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(dotenvPath)) {
    fs.readFileSync(dotenvPath, 'utf-8')
        .split('\n')
        .forEach(line => {
            const [key, ...rest] = line.split('=');
            if (key && rest.length && !process.env[key.trim()]) {
                process.env[key.trim()] = rest.join('=').trim().replace(/^["']|["']$/g, '');
            }
        });
}

const { isConfigured, getContainerClient } = require('./connection');
const BLOB_NAME = process.env.AZURE_STORAGE_BLOB_NAME || 'data.json';
const DATA_FILE = path.join(__dirname, '..', 'data.json');

const isDryRun = process.argv.includes('--dry-run');
const isForce = process.argv.includes('--force');

async function main() {
    console.log('=== Weekend Support Tracker — Azure Blob Storage Migration ===\n');

    // ── Step 1: Check credentials ────────────────────────────────────────────
    if (!isConfigured()) {
        console.error(
            'ERROR: Azure Blob Storage credentials are not configured.\n' +
            'Set AZURE_STORAGE_CONNECTION_STRING (or AZURE_STORAGE_ACCOUNT_NAME + ' +
            'AZURE_STORAGE_ACCOUNT_KEY) and re-run.\n'
        );
        process.exit(1);
    }
    console.log('✓ Azure credentials detected');

    // ── Step 2: Read local data.json ─────────────────────────────────────────
    if (!fs.existsSync(DATA_FILE)) {
        console.log('INFO: No local data.json found — nothing to migrate.');
        console.log('      The application will start with an empty dataset.');
        process.exit(0);
    }

    let localData;
    try {
        localData = JSON.parse(fs.readFileSync(DATA_FILE, 'utf-8'));
    } catch (err) {
        console.error(`ERROR: Could not parse data.json: ${err.message}`);
        process.exit(1);
    }

    const entriesCount = Object.keys(localData.entries || {}).length;
    const employeesCount = (localData.employees || []).length;
    const deletedCount = (localData.deletedItems || []).length;
    console.log(`✓ Local data.json read  — ${entriesCount} entries, ${employeesCount} employees, ${deletedCount} deleted items`);

    if (isDryRun) {
        console.log('\n[DRY RUN] Validation passed. No data was uploaded.');
        console.log('          Re-run without --dry-run to perform the migration.');
        process.exit(0);
    }

    // ── Step 3: Connect to Azure Blob Storage ───────────────────────────────
    let container;
    try {
        container = await getContainerClient();
        console.log('✓ Connected to Azure Blob Storage container');
    } catch (err) {
        console.error(`ERROR: Could not connect to Azure Blob Storage: ${err.message}`);
        process.exit(1);
    }

    // ── Step 4: Check if blob already exists ────────────────────────────────
    const blockBlobClient = container.getBlockBlobClient(BLOB_NAME);
    const alreadyExists = await blockBlobClient.exists();

    if (alreadyExists && !isForce) {
        console.warn(
            '\nWARNING: A data.json blob already exists in Azure Blob Storage.\n' +
            '         Re-run with --force to overwrite it with the local data.\n' +
            '         Aborting to prevent accidental data loss.\n'
        );
        process.exit(1);
    }

    if (alreadyExists && isForce) {
        console.log('⚠  --force flag set — existing blob will be overwritten');
    }

    // ── Step 5: Upload ───────────────────────────────────────────────────────
    console.log('\nUploading data to Azure Blob Storage...');
    const content = Buffer.from(JSON.stringify(localData, null, 2), 'utf-8');
    await blockBlobClient.upload(content, content.length, {
        blobHTTPHeaders: { blobContentType: 'application/json' },
    });

    console.log(`✓ Migration complete — ${content.length} bytes written to ${BLOB_NAME}`);
    console.log('\nNext steps:');
    console.log('  1. Deploy the updated backend with AZURE_STORAGE_CONNECTION_STRING set');
    console.log('  2. Verify the app loads data correctly via /api/entries');
    console.log('  3. (Optional) Remove or archive the local data.json once confirmed\n');
}

main().catch(err => {
    console.error('Unexpected error during migration:', err.message);
    process.exit(1);
});
