// Generated by GitHub Copilot
/**
 * Data models, schema factories, and validation helpers for Weekend Support Tracker.
 *
 * All persisted objects are created through these factory functions so that
 * every field has a guaranteed default value and the shape stays consistent
 * across API routes, the repository layer, and test fixtures.
 */
const { v4: uuidv4 } = require('uuid');

// ── Factories ─────────────────────────────────────────────────────────────────

/**
 * Create a new Entry object with safe defaults.
 * @param {object} fields
 * @returns {object} entry
 */
function createEntry({ id, releaseOwner, date, sanityFile, createdBy } = {}) {
    return {
        id: id || uuidv4(),
        releaseOwner: (releaseOwner || '').trim(),
        date: (date || '').trim(),
        sanityFile: sanityFile || null,
        createdBy: (createdBy || 'UNKNOWN').trim(),
        teams: [],
    };
}

/**
 * Create a new Team object with safe defaults.
 * @param {object} fields
 * @returns {object} team
 */
function createTeam({ id, teamName, leadName, totalCount, createdDate, createdBy } = {}) {
    return {
        id: id || uuidv4(),
        teamName: (teamName || '').trim(),
        leadName: (leadName || '').trim(),
        totalCount: Number(totalCount) || 0,
        createdDate: (createdDate || '').trim(),
        createdBy: (createdBy || 'UNKNOWN').trim(),
        lineItems: [],
    };
}

/**
 * Create a new LineItem object with safe defaults.
 * @param {object} fields
 * @returns {object} lineItem
 */
function createLineItem({ id, name, careerLevel, supervisor, allowanceCompoff, time, notes } = {}) {
    return {
        id: id || uuidv4(),
        name: (name || '').trim(),
        careerLevel: (careerLevel || '').trim(),
        supervisor: (supervisor || '').trim(),
        allowanceCompoff: allowanceCompoff || 'Compoff',
        time: (time || '').trim(),
        notes: (notes || '').trim(),
    };
}

/**
 * Create a changelog event object.
 * @param {object} fields
 * @returns {object} changelogEvent
 */
function createChangelogEvent({ type, oldValue, newValue, changedBy, teamName, leadName } = {}) {
    return {
        id: uuidv4(),
        type: type || 'unknown',
        oldValue: oldValue !== undefined ? oldValue : '',
        newValue: newValue !== undefined ? newValue : '',
        changedBy: (changedBy || 'UNKNOWN').trim(),
        teamName: teamName || '',
        leadName: leadName || '',
        timestamp: new Date().toISOString(),
    };
}

/**
 * Create a deleted-item tombstone record.
 * @param {'entry'|'team'|'lineItem'} itemType
 * @param {object} data - original item data
 * @param {object} parentInfo - contextual metadata
 * @returns {object} tombstone
 */
function createDeletedItem(itemType, data, parentInfo) {
    return {
        id: uuidv4(),
        type: itemType,
        data: JSON.parse(JSON.stringify(data)), // deep-copy
        deletedAt: new Date().toISOString(),
        parentInfo: parentInfo || {},
    };
}

/**
 * Return an empty data snapshot (used when no persisted data exists yet).
 * @returns {object}
 */
function emptyDataSnapshot() {
    return {
        entries: {},
        deletedItems: [],
        employees: [],
        changelogs: {},
        resourceUploadHistory: [],
    };
}

// ── Validation ────────────────────────────────────────────────────────────────

/**
 * Validate a raw entry payload from an API request.
 * @param {object} body
 * @returns {{ valid: boolean, errors: string[] }}
 */
function validateEntry(body) {
    const errors = [];
    if (!body || !(body.releaseOwner || '').trim()) errors.push('releaseOwner is required');
    if (!body || !(body.date || '').trim()) errors.push('date is required');
    return { valid: errors.length === 0, errors };
}

/**
 * Validate a raw team payload from an API request.
 * @param {object} body
 * @returns {{ valid: boolean, errors: string[] }}
 */
function validateTeam(body) {
    const errors = [];
    if (!body || !(body.teamName || '').trim()) errors.push('teamName is required');
    if (!body || !(body.leadName || '').trim()) errors.push('leadName is required');
    return { valid: errors.length === 0, errors };
}

/**
 * Validate a raw line-item payload from an API request.
 * @param {object} body
 * @returns {{ valid: boolean, errors: string[] }}
 */
function validateLineItem(body) {
    const errors = [];
    if (!body || !(body.name || '').trim()) errors.push('name is required');
    return { valid: errors.length === 0, errors };
}

module.exports = {
    createEntry,
    createTeam,
    createLineItem,
    createChangelogEvent,
    createDeletedItem,
    emptyDataSnapshot,
    validateEntry,
    validateTeam,
    validateLineItem,
};
