// Generated by GitHub Copilot
/**
 * Azure Blob Storage data access layer for Weekend Support Tracker.
 *
 * All application data (entries, teams, line items, employees, changelogs,
 * resource upload history, deleted items) is persisted as a single compact
 * JSON document stored in the configured Azure Blob Storage container.
 *
 * Blob name : data.json (configurable via AZURE_STORAGE_BLOB_NAME)
 * Container : weekend-support-data (configurable via AZURE_STORAGE_CONTAINER)
 *
 * Reads  : download the blob → parse JSON → return plain JS object
 * Writes : serialise to JSON → upload/overwrite blob
 *
 * A 2-second debounce in server.js prevents excessive write operations when
 * multiple mutations happen in quick succession (e.g., bulk line-item saves).
 */
const { getContainerClient, isConfigured } = require('./connection');

const BLOB_NAME = process.env.AZURE_STORAGE_BLOB_NAME || 'data.json';

/**
 * Load application data from Azure Blob Storage.
 * Returns null (not an error) when the blob does not yet exist.
 *
 * @returns {Promise<object|null>}
 */
async function loadData() {
    if (!isConfigured()) {
        console.log('Azure Blob Storage not configured — skipping cloud load');
        return null;
    }
    try {
        const container = await getContainerClient();
        const blockBlobClient = container.getBlockBlobClient(BLOB_NAME);

        const exists = await blockBlobClient.exists();
        if (!exists) {
            console.log('Azure Blob Storage: data.json not found — will create on first save');
            return null;
        }

        // downloadToBuffer() is the most reliable stream-to-Buffer API in the Node.js SDK
        const buffer = await blockBlobClient.downloadToBuffer();
        const parsed = JSON.parse(buffer.toString('utf-8'));

        console.log(
            `Azure Blob Storage: loaded ${Object.keys(parsed.entries || {}).length} entries, ` +
            `${(parsed.employees || []).length} employees`
        );
        return parsed;
    } catch (err) {
        console.error('Azure Blob Storage loadData error:', err.message);
        return null;
    }
}

/**
 * Save application data to Azure Blob Storage.
 * Overwrites the existing blob unconditionally (last-write-wins).
 * Should be called through the debounced wrapper in server.js.
 *
 * @param {object} data - Full in-memory data snapshot to persist
 * @returns {Promise<boolean>} true on success, false on failure
 */
async function saveData(data) {
    if (!isConfigured()) return false;
    try {
        const container = await getContainerClient();
        const blockBlobClient = container.getBlockBlobClient(BLOB_NAME);
        const content = Buffer.from(JSON.stringify(data, null, 2), 'utf-8');
        await blockBlobClient.upload(content, content.length, {
            blobHTTPHeaders: { blobContentType: 'application/json' },
            // upload() implicitly overwrites any existing blob of the same name
        });
        return true;
    } catch (err) {
        console.error('Azure Blob Storage saveData error:', err.message);
        return false;
    }
}

module.exports = { isConfigured, loadData, saveData };
