// Generated by GitHub Copilot
import React, { useState, useRef } from 'react';
import { useAuth } from '../context/AuthContext';
import { useAppContext } from '../context/AppContext';
import api from '../utils/api';
import * as XLSX from 'xlsx';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import Alert from '@mui/material/Alert';
import Tooltip from '@mui/material/Tooltip';
import AddIcon from '@mui/icons-material/Add';
import UploadFileIcon from '@mui/icons-material/UploadFile';

/**
 * Add Team form with manual entry and Excel upload for bulk team creation.
 * Excel should have columns: Team Name, Lead Name.
 */
export default function AddTeamForm({ entryId, onTeamAdded }) {
    const { empId } = useAuth();
    const { addToast } = useAppContext();
    const fileInputRef = useRef(null);

    const [teamName, setTeamName] = useState('');
    const [leadName, setLeadName] = useState('');
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!teamName.trim()) { setError('Team Name is required'); return; }
        if (!leadName.trim()) { setError('Lead Name is required'); return; }
        setLoading(true);
        try {
            await api.addTeam(entryId, {
                teamName: teamName.trim(), leadName: leadName.trim(),
                totalCount: 0, createdBy: empId,
            });
            setTeamName(''); setLeadName(''); setError('');
            addToast(`Team "${teamName.trim()}" added`, 'success');
            onTeamAdded();
        } catch (err) {
            setError(err.message);
            addToast(err.message, 'error');
        }
        setLoading(false);
    };

    /** Parse Excel file for Team Name + Lead Name columns and bulk-add teams */
    const handleExcelUpload = (e) => {
        const file = e.target.files[0];
        if (!file) return;
        const reader = new FileReader();
        reader.onload = async (evt) => {
            try {
                const data = new Uint8Array(evt.target.result);
                const wb = XLSX.read(data, { type: 'array' });
                const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { defval: '' });
                if (rows.length === 0) { addToast('Excel file is empty', 'error'); return; }

                const firstRow = rows[0];
                const teamKey = Object.keys(firstRow).find(k =>
                    k.toLowerCase().includes('team'));
                if (!teamKey) { addToast('Excel must have a "Team Name" column', 'error'); return; }

                const leadKey = Object.keys(firstRow).find(k =>
                    k.toLowerCase().includes('lead'));

                const teams = [];
                rows.forEach(row => {
                    const tn = String(row[teamKey] || '').trim();
                    if (!tn) return;
                    const ln = leadKey ? String(row[leadKey] || '').trim() : 'TBD';
                    teams.push({ teamName: tn, leadName: ln || 'TBD' });
                });

                if (teams.length === 0) { addToast('No valid team rows found', 'error'); return; }

                const result = await api.bulkAddTeams(entryId, teams, empId);
                const msgs = [];
                if (result.added?.length > 0) msgs.push(`${result.added.length} team(s) added`);
                if (result.skipped?.length > 0) msgs.push(`${result.skipped.length} skipped (duplicate)`);
                addToast(msgs.join(', ') || 'Upload complete', msgs.length > 0 ? 'success' : 'info');
                onTeamAdded();
            } catch (err) {
                addToast(err.message || 'Failed to parse Excel', 'error');
            }
        };
        reader.readAsArrayBuffer(file);
        e.target.value = '';
    };

    return (
        <Card sx={{ mb: 3, borderRadius: 2, bgcolor: '#1a1744', border: '1px solid #312e81' }}>
            <CardContent sx={{ py: 2, px: 3 }}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 1.5 }}>
                    <Typography variant="subtitle2" fontWeight={700} sx={{ flex: 1, color: '#e0e7ff' }}>
                        ➕ Add Team
                    </Typography>
                    <Tooltip title="Upload Teams from Excel (.xlsx, .csv) — columns: Team Name, Lead Name">
                        <Button size="small" startIcon={<UploadFileIcon />}
                            onClick={() => fileInputRef.current?.click()}
                            sx={{ textTransform: 'none', color: '#a5b4fc' }}>
                            Upload Teams
                        </Button>
                    </Tooltip>
                    <input ref={fileInputRef} type="file" hidden accept=".xlsx,.xls,.csv"
                        onChange={handleExcelUpload} aria-label="Upload teams from Excel" />
                </Box>
                <form onSubmit={handleSubmit} noValidate>
                    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr auto' }, gap: 1.5, alignItems: 'start' }}>
                        <TextField size="small" label="Team Name *" value={teamName}
                            onChange={e => { setTeamName(e.target.value); setError(''); }}
                            placeholder="Enter team name" />
                        <TextField size="small" label="Lead Name *" value={leadName}
                            onChange={e => { setLeadName(e.target.value); setError(''); }}
                            placeholder="Enter lead name" />
                        <Button type="submit" variant="contained" startIcon={<AddIcon />}
                            disabled={loading} size="small"
                            sx={{ bgcolor: '#4f46e5', '&:hover': { bgcolor: '#4338ca' }, textTransform: 'none', height: 40 }}>
                            {loading ? '...' : 'Add Team'}
                        </Button>
                    </Box>
                    {error && <Alert severity="error" sx={{ mt: 1 }}>{error}</Alert>}
                </form>
            </CardContent>
        </Card>
    );
}
