// Generated by GitHub Copilot
import React from 'react';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogContentText from '@mui/material/DialogContentText';
import DialogActions from '@mui/material/DialogActions';
import Button from '@mui/material/Button';
import WarningAmberIcon from '@mui/icons-material/WarningAmber';
import Box from '@mui/material/Box';

/**
 * Reusable YES / NO confirmation dialog (Material UI).
 * @param {boolean} open
 * @param {string} title
 * @param {string} message
 * @param {Function} onYes
 * @param {Function} onNo
 */
export default function ConfirmDialog({ open, title, message, onYes, onNo }) {
    return (
        <Dialog open={open} onClose={onNo} maxWidth="xs" fullWidth>
            <DialogTitle sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <WarningAmberIcon color="warning" /> {title}
            </DialogTitle>
            <DialogContent>
                <DialogContentText>{message}</DialogContentText>
            </DialogContent>
            <DialogActions>
                <Button onClick={onNo} color="inherit">NO</Button>
                <Button onClick={onYes} variant="contained" color="error" autoFocus>YES</Button>
            </DialogActions>
        </Dialog>
    );
}
