// Generated by GitHub Copilot
import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { useAppContext } from '../context/AppContext';
import api from '../utils/api';
import { getTodayStr } from '../utils/helpers';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import MenuItem from '@mui/material/MenuItem';
import Alert from '@mui/material/Alert';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';

/**
 * "Create New Release Details" form.
 * Fields: Release Owner (dropdown), Date (no past dates), Sanity Sheet upload.
 */
export default function CreateEntryForm() {
    const { empId } = useAuth();
    const { addToast, setLoading, navigateToEntry, setEntries } = useAppContext();

    const [owners, setOwners] = useState([]);
    const [releaseOwner, setReleaseOwner] = useState('');
    const [date, setDate] = useState('');
    const [file, setFile] = useState(null);
    const [error, setError] = useState('');
    const [submitting, setSubmitting] = useState(false);

    const today = getTodayStr();

    useEffect(() => { api.getReleaseOwners().then(setOwners).catch(() => { }); }, []);

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!releaseOwner) { setError('Release Owner is required'); return; }
        if (!date) { setError('Date is required'); return; }
        setSubmitting(true);
        setLoading(true);
        try {
            const fd = new FormData();
            fd.append('releaseOwner', releaseOwner);
            fd.append('date', date);
            fd.append('createdBy', empId);
            if (file) fd.append('sanityFile', file);
            const entry = await api.createEntry(fd);
            const list = await api.getEntries();
            setEntries(list);
            addToast(`Release created for ${date}`, 'success');
            navigateToEntry(entry.id);
        } catch (err) {
            setError(err.message);
            addToast(err.message, 'error');
        }
        setSubmitting(false);
        setLoading(false);
    };

    return (
        <Box sx={{ display: 'flex', justifyContent: 'center', pt: 4 }}>
            <Card sx={{ maxWidth: 500, width: '100%', borderRadius: 3, bgcolor: '#1a1744', border: '1px solid #312e81' }}>
                <CardContent sx={{ p: 4 }}>
                    <Typography variant="h6" fontWeight={700} gutterBottom sx={{ color: '#e0e7ff' }}>
                        📋 Create New Release Details
                    </Typography>
                    <form onSubmit={handleSubmit} noValidate>
                        <TextField select fullWidth label="Release Owner" value={releaseOwner}
                            onChange={e => { setReleaseOwner(e.target.value); setError(''); }}
                            size="small" sx={{ mb: 2 }} required>
                            <MenuItem value="">-- Select Release Owner --</MenuItem>
                            {owners.map(o => (
                                <MenuItem key={o.id} value={o.name}>{o.name} ({o.id})</MenuItem>
                            ))}
                        </TextField>

                        <TextField fullWidth type="date" label="Date" value={date}
                            onChange={e => { setDate(e.target.value); setError(''); }}
                            InputLabelProps={{ shrink: true }}
                            inputProps={{ min: today }}
                            size="small" sx={{
                                mb: 2,
                                '& input::-webkit-calendar-picker-indicator': {
                                    filter: 'invert(1)',
                                    cursor: 'pointer',
                                },
                            }} required />

                        <Button variant="outlined" component="label" startIcon={<CloudUploadIcon />}
                            sx={{ mb: 2, textTransform: 'none' }}>
                            {file ? file.name : 'Sanity Sheet Upload'}
                            <input type="file" hidden accept=".xlsx,.xls,.csv,.pdf"
                                onChange={e => setFile(e.target.files[0])} />
                        </Button>

                        {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}

                        <Button type="submit" variant="contained" fullWidth disabled={submitting}
                            sx={{ bgcolor: '#4f46e5', '&:hover': { bgcolor: '#4338ca' }, textTransform: 'none' }}>
                            {submitting ? 'Creating...' : '✅ Create'}
                        </Button>
                    </form>
                </CardContent>
            </Card>
        </Box>
    );
}
