// Generated by GitHub Copilot
import React, { useState, useEffect, useCallback } from 'react';
import { useAppContext } from '../context/AppContext';
import api from '../utils/api';
import ConfirmDialog from './ConfirmDialog';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import Checkbox from '@mui/material/Checkbox';
import Chip from '@mui/material/Chip';
import Table from '@mui/material/Table';
import TableHead from '@mui/material/TableHead';
import TableBody from '@mui/material/TableBody';
import TableRow from '@mui/material/TableRow';
import TableCell from '@mui/material/TableCell';
import Alert from '@mui/material/Alert';
import RestoreIcon from '@mui/icons-material/Restore';
import DeleteForeverIcon from '@mui/icons-material/DeleteForever';
import DeleteSweepIcon from '@mui/icons-material/DeleteSweep';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';

/**
 * Deleted Items screen - shows all soft-deleted entries, teams, and line items.
 * Features: Recover individual items, permanent delete, select all + delete all.
 * @param {{ onRefresh: Function }} props
 */
export default function DeletedItems({ onRefresh }) {
    const { addToast, navigateHome } = useAppContext();
    const [items, setItems] = useState([]);
    const [loading, setLoading] = useState(true);
    const [selected, setSelected] = useState(new Set());
    const [confirmDeleteAll, setConfirmDeleteAll] = useState(false);
    const [confirmDelete, setConfirmDelete] = useState(null);

    const loadItems = useCallback(async () => {
        setLoading(true);
        try {
            const data = await api.getDeletedItems();
            setItems(data);
        } catch { setItems([]); }
        setLoading(false);
    }, []);

    useEffect(() => { loadItems(); }, [loadItems]);

    const handleRecover = async (item) => {
        try {
            await api.recoverDeletedItem(item.id);
            addToast(`Recovered: ${getItemLabel(item)}`, 'success');
            loadItems();
            if (onRefresh) onRefresh();
        } catch (err) {
            addToast(err.message, 'error');
        }
    };

    const handlePermanentDelete = async (item) => {
        try {
            await api.permanentDeleteItem(item.id);
            addToast(`Permanently deleted: ${getItemLabel(item)}`, 'success');
            loadItems();
        } catch (err) {
            addToast(err.message, 'error');
        }
        setConfirmDelete(null);
    };

    const handleDeleteAll = async () => {
        try {
            if (selected.size > 0 && selected.size < items.length) {
                // Delete only selected
                const promises = [...selected].map(id => api.permanentDeleteItem(id));
                await Promise.all(promises);
                addToast(`${selected.size} item(s) permanently deleted`, 'success');
            } else {
                await api.deleteAllDeletedItems();
                addToast('All deleted items permanently removed', 'success');
            }
            setSelected(new Set());
            loadItems();
        } catch (err) {
            addToast(err.message, 'error');
        }
        setConfirmDeleteAll(false);
    };

    const toggleSelect = (id) => {
        setSelected(prev => {
            const next = new Set(prev);
            if (next.has(id)) next.delete(id); else next.add(id);
            return next;
        });
    };

    const toggleSelectAll = () => {
        if (selected.size === items.length) {
            setSelected(new Set());
        } else {
            setSelected(new Set(items.map(i => i.id)));
        }
    };

    /** Get a human-readable label for a deleted item */
    const getItemLabel = (item) => {
        if (item.type === 'entry') return `Entry: ${item.parentInfo?.date || 'Unknown'}`;
        if (item.type === 'team') return `Team: ${item.parentInfo?.teamName || item.data?.teamName || 'Unknown'}`;
        if (item.type === 'lineItem') return `Member: ${item.parentInfo?.memberName || item.data?.name || 'Unknown'}`;
        return 'Unknown';
    };

    const getTypeColor = (type) => {
        if (type === 'entry') return 'error';
        if (type === 'team') return 'primary';
        return 'default';
    };

    return (
        <Box>
            {/* Header */}
            <Box sx={{ display: 'flex', alignItems: 'center', mb: 2, gap: 1.5 }}>
                <IconButton size="small" onClick={navigateHome} title="Back to Home">
                    <ArrowBackIcon />
                </IconButton>
                <Typography variant="h6" fontWeight={700} sx={{ flex: 1 }}>
                    🗑️ Deleted Items ({items.length})
                </Typography>
                {items.length > 0 && (
                    <Button variant="contained" color="error" size="small"
                        startIcon={<DeleteSweepIcon />}
                        onClick={() => setConfirmDeleteAll(true)}
                        sx={{ textTransform: 'none' }}>
                        {selected.size > 0 && selected.size < items.length
                            ? `Delete Selected (${selected.size})`
                            : 'Delete All'}
                    </Button>
                )}
            </Box>

            {loading ? (
                <Typography variant="body2" color="text.disabled" sx={{ textAlign: 'center', py: 4 }}>
                    Loading...
                </Typography>
            ) : items.length === 0 ? (
                <Card sx={{ borderRadius: 2 }}>
                    <CardContent sx={{ textAlign: 'center', py: 5 }}>
                        <DeleteSweepIcon sx={{ fontSize: 48, color: '#d1d5db', mb: 1 }} />
                        <Typography variant="body1" color="text.secondary">
                            No deleted items. Items you delete will appear here.
                        </Typography>
                    </CardContent>
                </Card>
            ) : (
                <Card sx={{ borderRadius: 2 }}>
                    <Table size="small">
                        <TableHead>
                            <TableRow>
                                <TableCell padding="checkbox">
                                    <Checkbox
                                        checked={selected.size === items.length && items.length > 0}
                                        indeterminate={selected.size > 0 && selected.size < items.length}
                                        onChange={toggleSelectAll}
                                        aria-label="Select all deleted items"
                                    />
                                </TableCell>
                                <TableCell sx={{ fontWeight: 700, fontSize: 12 }}>Type</TableCell>
                                <TableCell sx={{ fontWeight: 700, fontSize: 12 }}>Name</TableCell>
                                <TableCell sx={{ fontWeight: 700, fontSize: 12 }}>Details</TableCell>
                                <TableCell sx={{ fontWeight: 700, fontSize: 12 }}>Deleted At</TableCell>
                                <TableCell sx={{ fontWeight: 700, fontSize: 12 }}>Actions</TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            {items.map(item => (
                                <TableRow key={item.id} hover
                                    sx={{ bgcolor: selected.has(item.id) ? 'action.selected' : 'inherit' }}>
                                    <TableCell padding="checkbox">
                                        <Checkbox checked={selected.has(item.id)}
                                            onChange={() => toggleSelect(item.id)}
                                            aria-label={`Select ${getItemLabel(item)}`} />
                                    </TableCell>
                                    <TableCell>
                                        <Chip label={item.type} size="small"
                                            color={getTypeColor(item.type)} variant="outlined" />
                                    </TableCell>
                                    <TableCell>
                                        <Typography variant="body2" fontWeight={600}>
                                            {getItemLabel(item)}
                                        </Typography>
                                    </TableCell>
                                    <TableCell>
                                        {item.type === 'entry' && (
                                            <Typography variant="caption" color="text.secondary">
                                                Owner: {item.data?.releaseOwner}, Teams: {item.data?.teams?.length || 0}
                                            </Typography>
                                        )}
                                        {item.type === 'team' && (
                                            <Typography variant="caption" color="text.secondary">
                                                Lead: {item.data?.leadName}, Members: {item.data?.lineItems?.length || 0}, Date: {item.parentInfo?.date}
                                            </Typography>
                                        )}
                                        {item.type === 'lineItem' && (
                                            <Typography variant="caption" color="text.secondary">
                                                Team: {item.parentInfo?.teamName}, Level: {item.data?.careerLevel || '—'},
                                                {' '}{item.data?.allowanceCompoff}
                                            </Typography>
                                        )}
                                    </TableCell>
                                    <TableCell>
                                        <Typography variant="caption" color="text.secondary">
                                            {new Date(item.deletedAt).toLocaleString()}
                                        </Typography>
                                    </TableCell>
                                    <TableCell>
                                        <Box sx={{ display: 'flex', gap: 0.5 }}>
                                            <Button size="small" variant="outlined" color="success"
                                                startIcon={<RestoreIcon />}
                                                onClick={() => handleRecover(item)}
                                                sx={{ textTransform: 'none', fontSize: 12 }}>
                                                Recover
                                            </Button>
                                            <IconButton size="small" color="error"
                                                onClick={() => setConfirmDelete(item)}
                                                title="Permanently delete"
                                                aria-label={`Permanently delete ${getItemLabel(item)}`}>
                                                <DeleteForeverIcon fontSize="small" />
                                            </IconButton>
                                        </Box>
                                    </TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </Card>
            )}

            <ConfirmDialog open={confirmDeleteAll} title="Delete All"
                message={selected.size > 0 && selected.size < items.length
                    ? `Permanently delete ${selected.size} selected item(s)? This cannot be undone.`
                    : `Permanently delete all ${items.length} item(s)? This cannot be undone.`}
                onYes={handleDeleteAll} onNo={() => setConfirmDeleteAll(false)} />

            <ConfirmDialog open={!!confirmDelete} title="Permanent Delete"
                message={`Permanently delete "${confirmDelete ? getItemLabel(confirmDelete) : ''}"? This cannot be undone.`}
                onYes={() => confirmDelete && handlePermanentDelete(confirmDelete)}
                onNo={() => setConfirmDelete(null)} />
        </Box>
    );
}
