// Generated by GitHub Copilot
import React, { useState, useEffect } from 'react';
import { useAppContext } from '../context/AppContext';
import { useAuth } from '../context/AuthContext';
import Breadcrumb from './Breadcrumb';
import SummaryHeader from './SummaryHeader';
import AddTeamForm from './AddTeamForm';
import TeamCard from './TeamCard';
import TeamDetail from './TeamDetail';
import HistoryScreen from './HistoryScreen';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import ComputerIcon from '@mui/icons-material/Computer';
import AddIcon from '@mui/icons-material/Add';
import HistoryIcon from '@mui/icons-material/History';
import RefreshIcon from '@mui/icons-material/Refresh';
import ListAltIcon from '@mui/icons-material/ListAlt';
import HomeIcon from '@mui/icons-material/Home';

/**
 * Orchestrator for a single date entry.
 * Shows summary + teams list, OR delegates to TeamDetail when a team is selected.
 * @param {{ onRefresh: Function }} props
 */
export default function EntryDetail({ onRefresh }) {
    const { currentEntry, selectedTeamId, view, setView, navigateToResources } = useAppContext();
    const { isLeadOnly, empId } = useAuth();
    const [showHistory, setShowHistory] = useState(false);

    // Reset history view when switching entries
    useEffect(() => { setShowHistory(false); }, [currentEntry?.id]);

    // No entry selected — show welcome
    if (!currentEntry) {
        return (
            <Box>
                <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2 }}>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5, color: '#a5b4fc' }}>
                        <HomeIcon sx={{ fontSize: 15 }} />
                        <Typography sx={{ fontSize: 12, color: '#a5b4fc', fontWeight: 600 }}>Home</Typography>
                    </Box>
                    <Button
                        variant="outlined"
                        size="small"
                        startIcon={<ListAltIcon />}
                        onClick={navigateToResources}
                        sx={{
                            textTransform: 'none', fontWeight: 600, fontSize: 13,
                            color: '#c084fc', borderColor: '#7c3aed', borderRadius: 1.5, px: 1.5,
                            '&:hover': { bgcolor: '#7c3aed', color: '#fff', borderColor: '#7c3aed' },
                        }}
                    >
                        Resources List
                    </Button>
                </Box>
                <Box sx={{
                    display: 'flex', flexDirection: 'column', alignItems: 'center',
                    justifyContent: 'center', height: '50vh', textAlign: 'center', color: '#a5b4fc'
                }}>
                    <ComputerIcon sx={{ fontSize: 56, mb: 1, opacity: 0.4 }} />
                    <Typography variant="h6" sx={{ color: '#c7d2fe' }}>Welcome to Weekend Support Tracker</Typography>
                    <Typography variant="body2" sx={{ mb: 2, color: '#a5b4fc' }}>Select an entry from the sidebar, or create a new one.</Typography>
                    <Button variant="contained" startIcon={<AddIcon />} onClick={() => setView('create')}
                        sx={{ bgcolor: '#4f46e5', '&:hover': { bgcolor: '#4338ca' }, textTransform: 'none' }}>
                        Create New Release
                    </Button>
                </Box>
            </Box>
        );
    }

    const teams = currentEntry.teams || [];

    return (
        <Box>
            {/* Top bar: Breadcrumb on left, Refresh + History buttons on right */}
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2, flexWrap: 'wrap', gap: 1 }}>
                <Breadcrumb showHistory={showHistory} onBackFromHistory={() => setShowHistory(false)} />
                <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
                    <Button
                        variant="outlined"
                        size="small"
                        startIcon={<RefreshIcon />}
                        onClick={onRefresh}
                        sx={{
                            textTransform: 'none', fontWeight: 600, fontSize: 13,
                            color: '#34d399', borderColor: '#059669', borderRadius: 1.5, px: 1.5,
                            '&:hover': { bgcolor: '#059669', color: '#fff', borderColor: '#059669' },
                        }}
                    >
                        Refresh
                    </Button>
                    <Button
                        variant={showHistory ? 'contained' : 'outlined'}
                        size="small"
                        startIcon={<HistoryIcon />}
                        onClick={() => setShowHistory(true)}
                        sx={{
                            textTransform: 'none', fontWeight: 600, fontSize: 13,
                            color: showHistory ? '#fff' : '#fbbf24',
                            borderColor: '#d97706',
                            bgcolor: showHistory ? '#d97706' : 'transparent',
                            borderRadius: 1.5, px: 1.5,
                            '&:hover': { bgcolor: '#d97706', color: '#fff', borderColor: '#d97706' },
                        }}
                    >
                        History
                    </Button>
                    {!isLeadOnly && (
                    <Button
                        variant="outlined"
                        size="small"
                        startIcon={<ListAltIcon />}
                        onClick={navigateToResources}
                        sx={{
                            textTransform: 'none', fontWeight: 600, fontSize: 13,
                            color: '#c084fc',
                            borderColor: '#7c3aed',
                            borderRadius: 1.5, px: 1.5,
                            '&:hover': { bgcolor: '#7c3aed', color: '#fff', borderColor: '#7c3aed' },
                        }}
                    >
                        Resources List
                    </Button>
                    )}
                </Box>
            </Box>

            {showHistory ? (
                <HistoryScreen entryId={currentEntry.id} onBack={() => setShowHistory(false)} />
            ) : view === 'team' && selectedTeamId ? (
                <TeamDetail entryId={currentEntry.id} teamId={selectedTeamId} onRefresh={onRefresh} />
            ) : (
                <>
                    {/* Pass full entry object so SummaryHeader can read releaseOwner, createdBy etc. */}
                    <SummaryHeader entry={currentEntry} onRefresh={onRefresh} />
                    <AddTeamForm entryId={currentEntry.id} onTeamAdded={onRefresh} />

                    <Typography variant="subtitle2" fontWeight={700} sx={{ mb: 1.5, color: '#e0e7ff' }}>
                        📋 Teams
                    </Typography>
                    {teams.length === 0 ? (
                        <Box sx={{ textAlign: 'center', py: 4, color: '#a5b4fc', border: '2px dashed #312e81', borderRadius: 2 }}>
                            <Typography variant="body2">No teams added yet for this entry.</Typography>
                        </Box>
                    ) : (
                        teams.map(t => (
                            <TeamCard key={t.id} team={t} entryId={currentEntry.id} onRefresh={onRefresh} />
                        ))
                    )}
                </>
            )}
        </Box>
    );
}
