// Generated by GitHub Copilot
import React from 'react';
import { useAppContext } from '../context/AppContext';
import Breadcrumb from './Breadcrumb';
import SummaryHeader from './SummaryHeader';
import AddTeamForm from './AddTeamForm';
import TeamCard from './TeamCard';
import TeamDetail from './TeamDetail';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import ComputerIcon from '@mui/icons-material/Computer';
import AddIcon from '@mui/icons-material/Add';

/**
 * Orchestrator for a single date entry.
 * Shows summary + teams list, OR delegates to TeamDetail when a team is selected.
 * @param {{ onRefresh: Function }} props
 */
export default function EntryDetail({ onRefresh }) {
    const { currentEntry, selectedTeamId, view, setView } = useAppContext();

    // No entry selected — show welcome
    if (!currentEntry) {
        return (
            <Box sx={{
                display: 'flex', flexDirection: 'column', alignItems: 'center',
                justifyContent: 'center', height: '55vh', textAlign: 'center', color: '#a5b4fc'
            }}>
                <ComputerIcon sx={{ fontSize: 56, mb: 1, opacity: 0.4 }} />
                <Typography variant="h6" sx={{ color: '#c7d2fe' }}>Welcome to Weekend Support Tracker</Typography>
                <Typography variant="body2" sx={{ mb: 2, color: '#a5b4fc' }}>Select an entry from the sidebar, or create a new one.</Typography>
                <Button variant="contained" startIcon={<AddIcon />} onClick={() => setView('create')}
                    sx={{ bgcolor: '#4f46e5', '&:hover': { bgcolor: '#4338ca' }, textTransform: 'none' }}>
                    Create New Release
                </Button>
            </Box>
        );
    }

    const teams = currentEntry.teams || [];

    return (
        <Box>
            <Breadcrumb />

            {view === 'team' && selectedTeamId ? (
                <TeamDetail entryId={currentEntry.id} teamId={selectedTeamId} onRefresh={onRefresh} />
            ) : (
                <>
                    {/* Pass full entry object so SummaryHeader can read releaseOwner, createdBy etc. */}
                    <SummaryHeader entry={currentEntry} onRefresh={onRefresh} />
                    <AddTeamForm entryId={currentEntry.id} onTeamAdded={onRefresh} />

                    <Typography variant="subtitle2" fontWeight={700} sx={{ mb: 1.5, color: '#e0e7ff' }}>
                        📋 Teams
                    </Typography>
                    {teams.length === 0 ? (
                        <Box sx={{ textAlign: 'center', py: 4, color: '#a5b4fc', border: '2px dashed #312e81', borderRadius: 2 }}>
                            <Typography variant="body2">No teams added yet for this entry.</Typography>
                        </Box>
                    ) : (
                        teams.map(t => (
                            <TeamCard key={t.id} team={t} entryId={currentEntry.id} onRefresh={onRefresh} />
                        ))
                    )}
                </>
            )}
        </Box>
    );
}
