// Generated by GitHub Copilot
import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { useAppContext } from '../context/AppContext';
import ConfirmDialog from './ConfirmDialog';
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Chip from '@mui/material/Chip';
import Box from '@mui/material/Box';
import ComputerIcon from '@mui/icons-material/Computer';
import LogoutIcon from '@mui/icons-material/Logout';

/**
 * Top header bar – "Weekend Production Support Details", user badge, logout with confirmation.
 */
export default function Header() {
    const { empId, logout } = useAuth();
    const { navigateHome } = useAppContext();
    const [logoutConfirm, setLogoutConfirm] = useState(false);

    const handleLogout = () => {
        setLogoutConfirm(false);
        logout();
    };

    return (
        <>
            <AppBar position="static" sx={{ bgcolor: '#1e1b4b', color: '#fff', boxShadow: '0 2px 8px rgba(0,0,0,.25)' }}>
                <Toolbar sx={{ minHeight: 56 }}>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, cursor: 'pointer' }}
                        onClick={navigateHome}>
                        <ComputerIcon sx={{ color: '#a5b4fc' }} />
                        <Typography variant="subtitle1" fontWeight={700} noWrap>
                            Weekend Production Support Details
                        </Typography>
                    </Box>
                    <Box sx={{ flex: 1, display: 'flex', justifyContent: 'center' }}>
                        <Typography variant="h6" fontWeight={800} sx={{ color: '#a5b4fc', letterSpacing: 1 }}>
                            MyISP
                        </Typography>
                    </Box>
                    <Chip label={empId} size="small" sx={{ mr: 1, fontWeight: 600, bgcolor: '#312e81', color: '#e0e7ff' }}
                        avatar={<Box sx={{
                            width: 24, height: 24, borderRadius: '50%', bgcolor: '#7c3aed',
                            color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center',
                            fontSize: 12, fontWeight: 700
                        }}>{empId.charAt(0).toUpperCase()}</Box>} />
                    <Button size="small" startIcon={<LogoutIcon />}
                        onClick={() => setLogoutConfirm(true)}
                        sx={{ textTransform: 'none', color: '#c7d2fe' }}>
                        Logout
                    </Button>
                </Toolbar>
            </AppBar>
            <ConfirmDialog
                open={logoutConfirm}
                title="Confirm Logout"
                message="Are you sure you want to logout?"
                onYes={handleLogout}
                onNo={() => setLogoutConfirm(false)}
            />
        </>
    );
}
