// Generated by GitHub Copilot
import React, { useEffect, useState } from 'react';
import { useAppContext } from '../context/AppContext';
import { formatDateLabel } from '../utils/helpers';
import api from '../utils/api';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Table from '@mui/material/Table';
import TableHead from '@mui/material/TableHead';
import TableBody from '@mui/material/TableBody';
import TableRow from '@mui/material/TableRow';
import TableCell from '@mui/material/TableCell';
import Chip from '@mui/material/Chip';
import CircularProgress from '@mui/material/CircularProgress';
import PersonIcon from '@mui/icons-material/Person';
import CalendarTodayIcon from '@mui/icons-material/CalendarToday';
import UploadFileIcon from '@mui/icons-material/UploadFile';

/**
 * Displays the change history of a release entry.
 * Tracks: Owner change, Date change, Sanity sheet upload.
 */
export default function HistoryScreen({ entryId, onBack }) {
    const { addToast } = useAppContext();
    const [history, setHistory] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        if (!entryId) return;
        const load = async () => {
            setLoading(true);
            try {
                const data = await api.getEntryHistory(entryId);
                setHistory(data);
            } catch (err) {
                addToast(err.message || 'Failed to load history', 'error');
            }
            setLoading(false);
        };
        load();
    }, [entryId, addToast]);

    const getTypeLabel = (type) => {
        switch (type) {
            case 'ownerChange': return 'Owner Changed';
            case 'dateChange': return 'Date Changed';
            case 'sanityUpload': return 'Sanity Sheet Uploaded';
            default: return type;
        }
    };

    const getTypeIcon = (type) => {
        switch (type) {
            case 'ownerChange': return <PersonIcon sx={{ fontSize: 14 }} />;
            case 'dateChange': return <CalendarTodayIcon sx={{ fontSize: 14 }} />;
            case 'sanityUpload': return <UploadFileIcon sx={{ fontSize: 14 }} />;
            default: return null;
        }
    };

    const getTypeColor = (type) => {
        switch (type) {
            case 'ownerChange': return 'primary';
            case 'dateChange': return 'warning';
            case 'sanityUpload': return 'success';
            default: return 'default';
        }
    };

    const formatTimestamp = (ts) => {
        const d = new Date(ts);
        return d.toLocaleString('en-US', {
            year: 'numeric', month: 'short', day: 'numeric',
            hour: '2-digit', minute: '2-digit', hour12: true,
        });
    };

    const formatValue = (type, value) => {
        if (!value) return '—';
        if (type === 'dateChange') return formatDateLabel(value);
        if (type === 'sanityUpload') {
            const parts = value.split('-');
            return parts.length > 1 ? parts.slice(1).join('-') : value;
        }
        return value;
    };

    return (
        <Box>
            {loading ? (
                <Box sx={{ display: 'flex', justifyContent: 'center', py: 6 }}>
                    <CircularProgress size={32} />
                </Box>
            ) : history.length === 0 ? (
                <Box sx={{
                    textAlign: 'center', py: 6, color: '#a5b4fc',
                    border: '2px dashed #312e81', borderRadius: 2,
                }}>
                    <Typography variant="body1" sx={{ mb: 1 }}>No changes recorded yet</Typography>
                    <Typography variant="body2" sx={{ opacity: 0.7 }}>
                        Changes to Owner, Date, or Sanity Sheet will appear here.
                    </Typography>
                </Box>
            ) : (
                <Box sx={{ borderRadius: 2, overflow: 'hidden', border: '1px solid #312e81' }}>
                    <Table size="small">
                        <TableHead>
                            <TableRow sx={{ bgcolor: '#1e1b4b' }}>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>#</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>Type</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>Old Value</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>New Value</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>Changed By</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>Date &amp; Time</TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            {history.map((h, i) => (
                                <TableRow key={h.id}
                                    sx={{
                                        '&:nth-of-type(odd)': { bgcolor: '#1a1744' },
                                        '&:nth-of-type(even)': { bgcolor: '#151234' },
                                        '&:hover': { bgcolor: '#252149' },
                                    }}>
                                    <TableCell sx={{ color: '#a5b4fc', fontSize: 12 }}>{i + 1}</TableCell>
                                    <TableCell>
                                        <Chip
                                            icon={getTypeIcon(h.type)}
                                            label={getTypeLabel(h.type)}
                                            size="small"
                                            color={getTypeColor(h.type)}
                                            variant="outlined"
                                            sx={{ fontSize: 11 }}
                                        />
                                    </TableCell>
                                    <TableCell sx={{ color: '#f87171', fontSize: 12, textDecoration: 'line-through', opacity: 0.8 }}>
                                        {formatValue(h.type, h.oldValue)}
                                    </TableCell>
                                    <TableCell sx={{ color: '#34d399', fontSize: 12, fontWeight: 600 }}>
                                        {formatValue(h.type, h.newValue)}
                                    </TableCell>
                                    <TableCell sx={{ color: '#e0e7ff', fontSize: 12 }}>{h.changedBy}</TableCell>
                                    <TableCell sx={{ color: '#a5b4fc', fontSize: 11 }}>{formatTimestamp(h.timestamp)}</TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </Box>
            )}
        </Box>
    );
}
