// Generated by GitHub Copilot
import React, { useEffect, useState, useMemo } from 'react';
import { useAppContext } from '../context/AppContext';
import { formatDateLabel } from '../utils/helpers';
import api from '../utils/api';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Table from '@mui/material/Table';
import TableHead from '@mui/material/TableHead';
import TableBody from '@mui/material/TableBody';
import TableRow from '@mui/material/TableRow';
import TableCell from '@mui/material/TableCell';
import Chip from '@mui/material/Chip';
import CircularProgress from '@mui/material/CircularProgress';
import Button from '@mui/material/Button';
import MenuItem from '@mui/material/MenuItem';
import Select from '@mui/material/Select';
import FormControl from '@mui/material/FormControl';
import InputLabel from '@mui/material/InputLabel';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';
import PersonIcon from '@mui/icons-material/Person';
import CalendarTodayIcon from '@mui/icons-material/CalendarToday';
import UploadFileIcon from '@mui/icons-material/UploadFile';
import SaveIcon from '@mui/icons-material/Save';
import DeleteForeverIcon from '@mui/icons-material/DeleteForever';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';

/**
 * Displays the change history of a release entry.
 * Tracks: Owner change, Date change, Sanity sheet upload, Team saves.
 * Supports Clear All history and date-wise deletion.
 */
export default function HistoryScreen({ entryId, onBack }) {
    const { addToast } = useAppContext();
    const [history, setHistory] = useState([]);
    const [loading, setLoading] = useState(true);
    const [confirmClearOpen, setConfirmClearOpen] = useState(false);
    const [selectedDate, setSelectedDate] = useState('');
    const [confirmDateOpen, setConfirmDateOpen] = useState(false);

    const loadHistory = async () => {
        if (!entryId) return;
        setLoading(true);
        try {
            const data = await api.getEntryHistory(entryId);
            setHistory(data);
        } catch (err) {
            addToast(err.message || 'Failed to load history', 'error');
        }
        setLoading(false);
    };

    useEffect(() => { loadHistory(); }, [entryId]); // eslint-disable-line react-hooks/exhaustive-deps

    /** Unique calendar dates present in history, sorted newest first */
    const availableDates = useMemo(() => {
        const seen = new Set();
        const dates = [];
        history.forEach(h => {
            const d = new Date(h.timestamp).toISOString().slice(0, 10);
            if (!seen.has(d)) { seen.add(d); dates.push(d); }
        });
        return dates.sort((a, b) => b.localeCompare(a));
    }, [history]);

    const handleClearAll = async () => {
        try {
            await api.clearEntryHistory(entryId);
            setHistory([]);
            addToast('History cleared', 'success');
        } catch (err) {
            addToast(err.message || 'Failed to clear history', 'error');
        }
        setConfirmClearOpen(false);
    };

    const handleDeleteByDate = async () => {
        if (!selectedDate) return;
        try {
            const result = await api.deleteHistoryByDate(entryId, selectedDate);
            addToast(`Deleted ${result.deleted || 0} record(s) for ${formatISODate(selectedDate)}`, 'success');
            await loadHistory();
            setSelectedDate('');
        } catch (err) {
            addToast(err.message || 'Failed to delete history by date', 'error');
        }
        setConfirmDateOpen(false);
    };

    const getTypeLabel = (type) => {
        switch (type) {
            case 'ownerChange': return 'Owner Changed';
            case 'dateChange': return 'Date Changed';
            case 'sanityUpload': return 'Sanity Sheet Uploaded';
            case 'teamSave': return 'Team Saved';
            default: return type;
        }
    };

    const getTypeIcon = (type) => {
        switch (type) {
            case 'ownerChange': return <PersonIcon sx={{ fontSize: 14 }} />;
            case 'dateChange': return <CalendarTodayIcon sx={{ fontSize: 14 }} />;
            case 'sanityUpload': return <UploadFileIcon sx={{ fontSize: 14 }} />;
            case 'teamSave': return <SaveIcon sx={{ fontSize: 14 }} />;
            default: return null;
        }
    };

    const getTypeColor = (type) => {
        switch (type) {
            case 'ownerChange': return 'primary';
            case 'dateChange': return 'warning';
            case 'sanityUpload': return 'success';
            case 'teamSave': return 'secondary';
            default: return 'default';
        }
    };

    const formatTimestamp = (ts) => {
        const d = new Date(ts);
        return d.toLocaleString('en-US', {
            year: 'numeric', month: 'short', day: 'numeric',
            hour: '2-digit', minute: '2-digit', hour12: true,
        });
    };

    const formatISODate = (iso) => {
        const d = new Date(iso + 'T00:00:00');
        return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
    };

    const formatValue = (type, value) => {
        if (value === '' || value === undefined || value === null) return '—';
        if (type === 'dateChange') return formatDateLabel(value);
        if (type === 'sanityUpload') {
            const parts = value.split('-');
            return parts.length > 1 ? parts.slice(1).join('-') : value;
        }
        if (type === 'teamSave') {
            // oldValue = previous member count, newValue = team name
            const num = parseInt(value, 10);
            if (!isNaN(num)) return `${num} member${num !== 1 ? 's' : ''}`;
        }
        return value;
    };

    return (
        <Box>
            {/* Toolbar: date-wise delete + clear all */}
            {!loading && history.length > 0 && (
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 2, flexWrap: 'wrap' }}>
                    {/* Date-wise Delete */}
                    <FormControl size="small" sx={{ minWidth: 180 }}>
                        <InputLabel sx={{ fontSize: 12 }}>Delete by Date</InputLabel>
                        <Select
                            value={selectedDate}
                            label="Delete by Date"
                            onChange={e => setSelectedDate(e.target.value)}
                            sx={{ fontSize: 12 }}
                        >
                            {availableDates.map(d => (
                                <MenuItem key={d} value={d} sx={{ fontSize: 12 }}>
                                    {formatISODate(d)}
                                </MenuItem>
                            ))}
                        </Select>
                    </FormControl>
                    <Button
                        size="small"
                        variant="outlined"
                        startIcon={<DeleteOutlineIcon />}
                        disabled={!selectedDate}
                        onClick={() => setConfirmDateOpen(true)}
                        sx={{
                            textTransform: 'none', fontSize: 12,
                            color: '#f87171', borderColor: '#ef4444',
                            '&:hover': { bgcolor: '#ef4444', color: '#fff', borderColor: '#ef4444' },
                        }}
                    >
                        Delete Selected Date
                    </Button>
                    <Box sx={{ flex: 1 }} />
                    {/* Clear All */}
                    <Button
                        size="small"
                        variant="contained"
                        startIcon={<DeleteForeverIcon />}
                        onClick={() => setConfirmClearOpen(true)}
                        sx={{
                            textTransform: 'none', fontSize: 12,
                            bgcolor: '#b91c1c',
                            '&:hover': { bgcolor: '#991b1b' },
                        }}
                    >
                        Clear All History
                    </Button>
                </Box>
            )}

            {loading ? (
                <Box sx={{ display: 'flex', justifyContent: 'center', py: 6 }}>
                    <CircularProgress size={32} />
                </Box>
            ) : history.length === 0 ? (
                <Box sx={{
                    textAlign: 'center', py: 6, color: '#a5b4fc',
                    border: '2px dashed #312e81', borderRadius: 2,
                }}>
                    <Typography variant="body1" sx={{ mb: 1 }}>No changes recorded yet</Typography>
                    <Typography variant="body2" sx={{ opacity: 0.7 }}>
                        Changes to Owner, Date, or Sanity Sheet will appear here.
                    </Typography>
                </Box>
            ) : (
                <Box sx={{ borderRadius: 2, overflow: 'hidden', border: '1px solid #312e81' }}>
                    <Table size="small">
                        <TableHead>
                            <TableRow sx={{ bgcolor: '#1e1b4b' }}>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>#</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>Type</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>Old Value</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>New Value</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>Changed By</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>Date &amp; Time</TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            {history.map((h, i) => (
                                <TableRow key={h.id}
                                    sx={{
                                        '&:nth-of-type(odd)': { bgcolor: '#1a1744' },
                                        '&:nth-of-type(even)': { bgcolor: '#151234' },
                                        '&:hover': { bgcolor: '#252149' },
                                    }}>
                                    <TableCell sx={{ color: '#a5b4fc', fontSize: 12 }}>{i + 1}</TableCell>
                                    <TableCell>
                                        <Chip
                                            icon={getTypeIcon(h.type)}
                                            label={getTypeLabel(h.type)}
                                            size="small"
                                            color={getTypeColor(h.type)}
                                            variant="outlined"
                                            sx={{ fontSize: 11 }}
                                        />
                                    </TableCell>
                                    <TableCell sx={{ color: '#f87171', fontSize: 12, textDecoration: h.type !== 'teamSave' ? 'line-through' : 'none', opacity: 0.8 }}>
                                        {formatValue(h.type, h.oldValue)}
                                    </TableCell>
                                    <TableCell sx={{ color: '#34d399', fontSize: 12, fontWeight: 600 }}>
                                        {formatValue(h.type, h.newValue)}
                                    </TableCell>
                                    <TableCell sx={{ color: '#e0e7ff', fontSize: 12 }}>{h.changedBy}</TableCell>
                                    <TableCell sx={{ color: '#a5b4fc', fontSize: 11 }}>{formatTimestamp(h.timestamp)}</TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </Box>
            )}

            {/* Confirm: Clear All History */}
            <Dialog open={confirmClearOpen} onClose={() => setConfirmClearOpen(false)} maxWidth="xs" fullWidth>
                <DialogTitle>Clear All History?</DialogTitle>
                <DialogContent>
                    <Typography variant="body2">
                        This will permanently delete all {history.length} history record(s) for this entry. This action cannot be undone.
                    </Typography>
                </DialogContent>
                <DialogActions>
                    <Button size="small" onClick={() => setConfirmClearOpen(false)}>Cancel</Button>
                    <Button size="small" variant="contained" onClick={handleClearAll}
                        sx={{ bgcolor: '#b91c1c', '&:hover': { bgcolor: '#991b1b' } }}>
                        Clear All
                    </Button>
                </DialogActions>
            </Dialog>

            {/* Confirm: Delete by Date */}
            <Dialog open={confirmDateOpen} onClose={() => setConfirmDateOpen(false)} maxWidth="xs" fullWidth>
                <DialogTitle>Delete History for {selectedDate ? formatISODate(selectedDate) : ''}?</DialogTitle>
                <DialogContent>
                    <Typography variant="body2">
                        All history records from <strong>{selectedDate ? formatISODate(selectedDate) : ''}</strong> will be permanently deleted. This action cannot be undone.
                    </Typography>
                </DialogContent>
                <DialogActions>
                    <Button size="small" onClick={() => setConfirmDateOpen(false)}>Cancel</Button>
                    <Button size="small" variant="contained" onClick={handleDeleteByDate}
                        sx={{ bgcolor: '#b91c1c', '&:hover': { bgcolor: '#991b1b' } }}>
                        Delete
                    </Button>
                </DialogActions>
            </Dialog>
        </Box>
    );
}
