// Generated by GitHub Copilot
import React, { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import api from '../utils/api';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import Chip from '@mui/material/Chip';
import Button from '@mui/material/Button';
import CircularProgress from '@mui/material/CircularProgress';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import UpdateIcon from '@mui/icons-material/Update';

/**
 * Last Updated screen – shows up to 5 most recent team-save events.
 * CL9 leads see only their own teams; CL8 and below see all.
 * @param {{ onBack: Function }} props
 */
export default function LastUpdatedScreen({ onBack }) {
    const { empId, isLeadOnly } = useAuth();
    const [updates, setUpdates] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    useEffect(() => {
        setLoading(true);
        // CL9 leads: filter by their own empId; others: no filter (see all)
        api.getLastUpdated(isLeadOnly ? empId : null)
            .then(data => { setUpdates(data || []); setLoading(false); })
            .catch(err => { setError(err.message || 'Failed to load'); setLoading(false); });
    }, [empId, isLeadOnly]);

    /** Format ISO timestamp to readable date+time */
    const formatTs = (ts) => {
        if (!ts) return '—';
        const d = new Date(ts);
        return d.toLocaleString('en-IN', {
            day: '2-digit', month: 'short', year: 'numeric',
            hour: '2-digit', minute: '2-digit', hour12: true,
        });
    };

    return (
        <Box>
            {/* Header */}
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 2.5 }}>
                <Button size="small" startIcon={<ArrowBackIcon />} onClick={onBack}
                    sx={{ textTransform: 'none', color: '#a5b4fc', '&:hover': { color: '#818cf8' } }}>
                    Back
                </Button>
                <UpdateIcon sx={{ color: '#818cf8', fontSize: 20 }} />
                <Typography variant="h6" fontWeight={700} sx={{ color: '#e0e7ff' }}>
                    Last Updated (Recent 5)
                </Typography>
            </Box>

            {loading && (
                <Box sx={{ display: 'flex', justifyContent: 'center', py: 6 }}>
                    <CircularProgress size={32} sx={{ color: '#818cf8' }} />
                </Box>
            )}

            {!loading && error && (
                <Typography color="error" sx={{ py: 2 }}>{error}</Typography>
            )}

            {!loading && !error && updates.length === 0 && (
                <Box sx={{ textAlign: 'center', py: 6, color: '#a5b4fc' }}>
                    <UpdateIcon sx={{ fontSize: 48, opacity: 0.3, mb: 1 }} />
                    <Typography variant="body2">No recent updates found.</Typography>
                </Box>
            )}

            {!loading && !error && updates.map((u, idx) => (
                <Card key={u.id || idx} sx={{ mb: 1.5, borderRadius: 2, bgcolor: '#1a1744', border: '1px solid #312e81' }}>
                    <CardContent sx={{ py: 1.5, display: 'flex', flexWrap: 'wrap', gap: 1.5, alignItems: 'center' }}>
                        <Box sx={{ flex: 1, minWidth: 180 }}>
                            <Typography variant="subtitle2" fontWeight={700} sx={{ color: '#e0e7ff', mb: 0.5 }}>
                                {u.teamName || '(unknown team)'}
                            </Typography>
                            <Typography variant="caption" sx={{ color: '#a5b4fc' }}>
                                Updated by <strong style={{ color: '#c7d2fe' }}>{u.changedBy || '—'}</strong>
                                &nbsp;· Entry date: <strong style={{ color: '#c7d2fe' }}>{u.entryDate || '—'}</strong>
                            </Typography>
                        </Box>
                        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.5, alignItems: 'flex-end' }}>
                            {u.leadName && (
                                <Chip label={`Lead: ${u.leadName}`} size="small" variant="outlined"
                                    sx={{ borderColor: '#4f46e5', color: '#c7d2fe', fontSize: 11 }} />
                            )}
                            <Typography variant="caption" sx={{ color: '#6b7280', fontSize: 11 }}>
                                {formatTs(u.timestamp)}
                            </Typography>
                        </Box>
                    </CardContent>
                </Card>
            ))}
        </Box>
    );
}
