// Generated by GitHub Copilot
import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import api from '../utils/api';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import InputAdornment from '@mui/material/InputAdornment';
import ComputerIcon from '@mui/icons-material/Computer';
import Alert from '@mui/material/Alert';
import CircularProgress from '@mui/material/CircularProgress';
import Visibility from '@mui/icons-material/Visibility';
import VisibilityOff from '@mui/icons-material/VisibilityOff';

/**
 * Login screen – validates enterprise ID (e.g. arun.thangapandian) + password
 * against the server-side allowed-users whitelist before granting access.
 * Password is the Accenture TFS / Azure DevOps password configured on the server.
 */
export default function LoginScreen() {
    const { login } = useAuth();
    const [empId, setEmpId] = useState('');
    const [password, setPassword] = useState('');
    const [showPassword, setShowPassword] = useState(false);
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!empId.trim()) { setError('Employee ID is required'); return; }
        if (!password) { setError('Password is required'); return; }
        setLoading(true);
        setError('');
        try {
            const result = await api.validateLogin(empId.trim(), password);
            login(empId.trim().toLowerCase(), result.careerLevel ?? null);
        } catch (err) {
            setError(err.message || 'Access denied');
        }
        setLoading(false);
    };

    return (
        <Box sx={{
            minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center',
            background: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 30%, #4f46e5 60%, #7c3aed 100%)',
        }}>
            <Card sx={{ maxWidth: 400, width: '100%', mx: 2, borderRadius: 3 }}>
                <CardContent sx={{ p: 5, textAlign: 'center' }}>
                    <ComputerIcon sx={{ fontSize: 56, color: '#4f46e5', mb: 1 }} />
                    <Typography variant="h5" fontWeight={700} gutterBottom>
                        Weekend Production Support
                    </Typography>
                    <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                        Sign in with your Employee ID and TFS password
                    </Typography>
                    <form onSubmit={handleSubmit} noValidate>
                        <TextField
                            fullWidth label="Employee ID" placeholder="e.g. arun.thangapandian"
                            value={empId} onChange={e => { setEmpId(e.target.value); setError(''); }}
                            autoFocus size="small" sx={{ mb: 2 }}
                            autoComplete="username"
                        />
                        <TextField
                            fullWidth label="Password" placeholder="Accenture TFS Password"
                            type={showPassword ? 'text' : 'password'}
                            value={password} onChange={e => { setPassword(e.target.value); setError(''); }}
                            size="small" sx={{ mb: 2 }}
                            autoComplete="current-password"
                            InputProps={{
                                endAdornment: (
                                    <InputAdornment position="end">
                                        <IconButton
                                            aria-label={showPassword ? 'Hide password' : 'Show password'}
                                            onClick={() => setShowPassword(p => !p)}
                                            edge="end" size="small">
                                            {showPassword ? <VisibilityOff fontSize="small" /> : <Visibility fontSize="small" />}
                                        </IconButton>
                                    </InputAdornment>
                                ),
                            }}
                        />
                        {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
                        <Button type="submit" variant="contained" fullWidth size="large"
                            disabled={loading}
                            sx={{ bgcolor: '#4f46e5', '&:hover': { bgcolor: '#4338ca' } }}>
                            {loading ? <CircularProgress size={24} color="inherit" /> : 'SIGN IN'}
                        </Button>
                    </form>
                </CardContent>
            </Card>
        </Box>
    );
}
