// Generated by GitHub Copilot
import React, { useState, useEffect, useRef } from 'react';
import { useAppContext } from '../context/AppContext';
import { useAuth } from '../context/AuthContext';
import { formatDateLabel } from '../utils/helpers';
import api from '../utils/api';
import * as XLSX from 'xlsx';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import Table from '@mui/material/Table';
import TableHead from '@mui/material/TableHead';
import TableBody from '@mui/material/TableBody';
import TableRow from '@mui/material/TableRow';
import TableCell from '@mui/material/TableCell';
import Breadcrumbs from '@mui/material/Breadcrumbs';
import BreadcrumbLink from '@mui/material/Link';
import CircularProgress from '@mui/material/CircularProgress';
import Chip from '@mui/material/Chip';
import Tooltip from '@mui/material/Tooltip';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import HomeIcon from '@mui/icons-material/Home';
import ListAltIcon from '@mui/icons-material/ListAlt';
import FileDownloadIcon from '@mui/icons-material/FileDownload';

/**
 * Resources List screen – manage the master employee resource file.
 * Shows upload history table: Name, Uploaded File, Uploaded Date & Time (recent first).
 * Upload button is here; NOT in the sidebar.
 */
export default function ResourcesListScreen() {
    const { navigateHome, navigateToEntry, currentEntry, addToast } = useAppContext();
    const { empId } = useAuth();
    const [uploads, setUploads] = useState([]);
    const [loading, setLoading] = useState(true);
    const fileInputRef = useRef(null);

    const loadHistory = async () => {
        setLoading(true);
        try {
            const data = await api.getResourceUploadHistory();
            setUploads(data);
        } catch {
            setUploads([]);
        }
        setLoading(false);
    };

    useEffect(() => { loadHistory(); }, []);

    const handleUpload = (e) => {
        const file = e.target.files[0];
        if (!file) return;
        const originalName = file.name;
        const reader = new FileReader();
        reader.onload = async (evt) => {
            try {
                const data = new Uint8Array(evt.target.result);
                const wb = XLSX.read(data, { type: 'array' });
                const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1, defval: '' });
                if (rows.length < 2) { addToast('Resource list file is empty', 'error'); return; }
                // Col B(idx1)=Name, Col C(idx2)=Enterprise ID, Col D(idx3)=Career Level, Col I(idx8)=Supervisor
                const list = rows.slice(1).map(r => ({
                    id: (String(r[2] || '').trim().toLowerCase()) || String(r[1] || '').trim().toLowerCase().replace(/\s+/g, '.'),
                    name: String(r[1] || '').trim(),
                    careerLevel: String(r[3] || '').trim(),
                    supervisor: String(r[8] || '').trim(),
                })).filter(emp => emp.name);
                if (list.length === 0) { addToast('No valid employee rows found', 'error'); return; }
                await api.uploadEmployeeList(list, empId, originalName);
                addToast(`Resource list uploaded: ${list.length} employees`, 'success');
                loadHistory();
            } catch (err) {
                addToast(err.message || 'Upload failed', 'error');
            }
        };
        reader.readAsArrayBuffer(file);
        e.target.value = '';
        const handleExportEmployees = async () => {
            try {
                const list = await api.getEmployees();
                if (!list || list.length === 0) { addToast('No employee data to export', 'warning'); return; }
                const header = ['ID', 'Name', 'Career Level', 'Supervisor'];
                const rows = [header, ...list.map(e => [e.id || '', e.name || '', e.careerLevel || '', e.supervisor || ''])];
                const csv = rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n');
                const blob = new Blob([csv], { type: 'text/csv' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `resource-list-${new Date().toISOString().split('T')[0]}.csv`;
                a.click();
                URL.revokeObjectURL(url);
                addToast('Employee list exported', 'success');
            } catch { addToast('Export failed', 'error'); }
        };
        const d = new Date(ts);
        return d.toLocaleString('en-US', {
            year: 'numeric', month: 'short', day: 'numeric',
            hour: '2-digit', minute: '2-digit', hour12: true,
        });
    };

    return (
        <Box>
            {/* Breadcrumb row + Upload button */}
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2, flexWrap: 'wrap', gap: 1 }}>
                <Breadcrumbs sx={{ fontSize: 13 }} aria-label="breadcrumb">
                    <BreadcrumbLink
                        underline="hover"
                        sx={{ display: 'flex', alignItems: 'center', gap: 0.5, cursor: 'pointer', color: '#a5b4fc' }}
                        onClick={navigateHome}
                    >
                        <HomeIcon sx={{ fontSize: 16 }} /> Home
                    </BreadcrumbLink>
                    {currentEntry && (
                        <BreadcrumbLink
                            underline="hover"
                            sx={{ cursor: 'pointer', color: '#a5b4fc' }}
                            onClick={() => navigateToEntry(currentEntry.id)}
                        >
                            {formatDateLabel(currentEntry.date)}
                        </BreadcrumbLink>
                    )}
                    <Typography
                        sx={{ color: '#e0e7ff', display: 'flex', alignItems: 'center', gap: 0.5 }}
                        fontSize={13}
                        fontWeight={600}
                    >
                        <ListAltIcon sx={{ fontSize: 16 }} /> Resources List
                    </Typography>
                </Breadcrumbs>

                <Button
                    variant="contained"
                    size="small"
                    startIcon={<CloudUploadIcon />}
                    onClick={() => fileInputRef.current?.click()}
                    sx={{
                        textTransform: 'none', fontWeight: 600, fontSize: 13,
                        bgcolor: '#4f46e5', '&:hover': { bgcolor: '#4338ca' },
                        borderRadius: 1.5, px: 2,
                    }}
                >
                    Upload Resource List
                </Button>
                <input
                    ref={fileInputRef}
                    type="file"
                    hidden
                    accept=".xlsx,.xls,.csv"
                    onChange={handleUpload}
                    aria-label="Upload resource list"
                />
            </Box>

            <Typography variant="subtitle2" fontWeight={700} sx={{ mb: 1.5, color: '#e0e7ff' }}>
                📋 Upload History
            </Typography>

            {loading ? (
                <Box sx={{ display: 'flex', justifyContent: 'center', py: 6 }}>
                    <CircularProgress size={32} />
                </Box>
            ) : uploads.length === 0 ? (
                <Box sx={{
                    textAlign: 'center', py: 6, color: '#a5b4fc',
                    border: '2px dashed #312e81', borderRadius: 2,
                }}>
                    <Typography variant="body1" sx={{ mb: 1 }}>No resource lists uploaded yet</Typography>
                    <Typography variant="body2" sx={{ opacity: 0.7 }}>
                        Click "Upload Resource List" above to upload the master resource file (.xlsx/.csv).
                    </Typography>
                </Box>
            ) : (
                <Box sx={{ borderRadius: 2, overflow: 'hidden', border: '1px solid #312e81' }}>
                    <Table size="small">
                        <TableHead>
                            <TableRow sx={{ bgcolor: '#1e1b4b' }}>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>#</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>Name</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>Uploaded File</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>Employees</TableCell>
                                <TableCell sx={{ fontWeight: 700, color: '#a5b4fc', fontSize: 12 }}>Uploaded Date &amp; Time</TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            {uploads.map((u, i) => (
                                <TableRow key={u.id}
                                    sx={{
                                        '&:nth-of-type(odd)': { bgcolor: '#1a1744' },
                                        '&:nth-of-type(even)': { bgcolor: '#151234' },
                                        '&:hover': { bgcolor: '#252149' },
                                    }}>
                                    <TableCell sx={{ color: '#a5b4fc', fontSize: 12 }}>{i + 1}</TableCell>
                                    <TableCell sx={{ color: '#e0e7ff', fontSize: 12, fontWeight: 600 }}>{u.uploadedBy}</TableCell>
                                    <TableCell sx={{ color: '#c7d2fe', fontSize: 12 }}>
                                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                                            <Chip
                                                label={u.filename}
                                                size="small"
                                                variant="outlined"
                                                sx={{ borderColor: '#4f46e5', color: '#c7d2fe', fontSize: 11, maxWidth: 220 }}
                                            />
                                            <Tooltip title="Export employee list as CSV">
                                                <IconButton size="small" onClick={handleExportEmployees}
                                                    sx={{ color: '#34d399', '&:hover': { color: '#059669' } }}>
                                                    <FileDownloadIcon sx={{ fontSize: 16 }} />
                                                </IconButton>
                                            </Tooltip>
                                        </Box>
                                    </TableCell>
                                    <TableCell sx={{ color: '#34d399', fontSize: 12 }}>{u.count}</TableCell>
                                    <TableCell sx={{ color: '#a5b4fc', fontSize: 11 }}>{formatTimestamp(u.uploadedAt)}</TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </Box>
            )}
        </Box>
    );
}
