// Generated by GitHub Copilot
import React, { useRef, useState } from 'react';
import { useAppContext } from '../context/AppContext';
import { useAuth } from '../context/AuthContext';
import api from '../utils/api';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import Chip from '@mui/material/Chip';
import Button from '@mui/material/Button';
import Tooltip from '@mui/material/Tooltip';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';
import Table from '@mui/material/Table';
import TableHead from '@mui/material/TableHead';
import TableBody from '@mui/material/TableBody';
import TableRow from '@mui/material/TableRow';
import TableCell from '@mui/material/TableCell';
import IconButton from '@mui/material/IconButton';
import GroupsIcon from '@mui/icons-material/Groups';
import PeopleIcon from '@mui/icons-material/People';
import PaidIcon from '@mui/icons-material/Paid';
import EventAvailableIcon from '@mui/icons-material/EventAvailable';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import DescriptionIcon from '@mui/icons-material/Description';
import FileDownloadIcon from '@mui/icons-material/FileDownload';
import CachedIcon from '@mui/icons-material/Cached';

/**
 * Summary cards at top of date details screen.
 * Cards are clickable — clicking opens a dialog with details + Export button.
 * All member dialogs include Lead column.
 * @param {{ entry: object, onRefresh: Function }} props
 */

// Generated by GitHub Copilot
/** Extract login time from time range string */
function getLoginTime(timeStr) {
    if (!timeStr || !timeStr.includes('-')) return '';
    return timeStr.split('-')[0].trim();
}

/** Extract logout time from time range string */
function getLogoutTime(timeStr) {
    if (!timeStr || !timeStr.includes('-')) return '';
    const parts = timeStr.split('-');
    return parts.length > 1 ? parts[1].trim() : '';
}

/** Determine support type based on total hours */
function getSupportType(totalHrsStr) {
    if (!totalHrsStr) return '';
    const num = parseFloat(totalHrsStr);
    if (isNaN(num)) return '';
    if (num >= 6) return 'On Call Primary Support';
    if (num >= 4) return 'On Call Secondary Support';
    return '';
}

/** Calculate total hours from time range for CSV export */
function calcTotalHoursCSV(timeStr) {
    if (!timeStr || !timeStr.includes('-')) return '';
    const parts = timeStr.split('-').map(s => s.trim());
    if (parts.length !== 2) return '';
    const parse12 = (s) => {
        const m = s.trim().match(/^(\d{1,2})(?::(\d{2}))?\s*(AM|PM)$/i);
        if (!m) return NaN;
        let h = parseInt(m[1], 10);
        const min = m[2] ? parseInt(m[2], 10) : 0;
        const period = m[3].toUpperCase();
        if (h === 12) h = 0;
        if (period === 'PM') h += 12;
        return h * 60 + min;
    };
    const start = parse12(parts[0]);
    const end = parse12(parts[1]);
    if (isNaN(start) || isNaN(end)) return '';
    let diff = end - start;
    if (diff <= 0) diff += 24 * 60;
    const hrs = diff / 60;
    return `${hrs % 1 === 0 ? hrs : hrs.toFixed(1)} hrs`;
}

export default function SummaryHeader({ entry, onRefresh }) {
    const { addToast } = useAppContext();
    const { empId, isLeadOnly } = useAuth();
    const fileInputRef = useRef(null);
    const reuploadInputRef = useRef(null);
    const [dialogOpen, setDialogOpen] = useState(null);

    if (!entry) return null;

    const teams = entry.teams || [];
    // CL9 leads see summary only for their own team
    const visibleTeams = isLeadOnly
        ? teams.filter(t => t.leadName.toLowerCase() === empId.toLowerCase())
        : teams;
    const totalTeams = visibleTeams.length;
    const allItems = visibleTeams.flatMap(t => (t.lineItems || []).map(li => ({ ...li, teamName: t.teamName, leadName: t.leadName })));
    const totalMembers = allItems.length;
    const allowanceItems = allItems.filter(li => li.allowanceCompoff === 'Allowance');
    const compoffItems = allItems.filter(li => li.allowanceCompoff === 'Compoff');

    const handleSanityUpload = async (e) => {
        const file = e.target.files[0];
        if (!file) return;
        try {
            const fd = new FormData();
            fd.append('sanityFile', file);
            fd.append('changedBy', empId || 'UNKNOWN');
            await api.uploadSanityFile(entry.id, fd);
            addToast('Sanity sheet uploaded successfully', 'success');
            if (onRefresh) onRefresh();
        } catch (err) {
            addToast(err.message || 'Upload failed', 'error');
        }
        e.target.value = '';
    };

    /** Export dialog data as colorful Excel via backend */
    const handleExportDialog = async () => {
        try {
            const url = api.getDialogExportUrl(entry.id, dialogOpen);
            const response = await fetch(url);
            if (!response.ok) throw new Error('Export failed');
            const blob = await response.blob();
            const blobUrl = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = blobUrl;
            a.download = `${dialogOpen}-${entry.date}.xlsx`;
            a.click();
            URL.revokeObjectURL(blobUrl);
            addToast('Exported successfully', 'success');
        } catch (err) {
            addToast(err.message || 'Export failed', 'error');
        }
    };

    const renderDialogContent = () => {
        if (dialogOpen === 'teams') {
            return (
                <>
                    <DialogTitle sx={{ fontWeight: 700 }}>📋 Teams ({totalTeams})</DialogTitle>
                    <DialogContent dividers>
                        {teams.length === 0 ? (
                            <Typography color="text.secondary">No teams</Typography>
                        ) : (
                            <Table size="small">
                                <TableHead>
                                    <TableRow>
                                        <TableCell sx={{ fontWeight: 700 }}>#</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Team Name</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Lead</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Members</TableCell>
                                    </TableRow>
                                </TableHead>
                                <TableBody>
                                    {teams.map((t, i) => (
                                        <TableRow key={t.id}>
                                            <TableCell>{i + 1}</TableCell>
                                            <TableCell>{t.teamName}</TableCell>
                                            <TableCell>{t.leadName}</TableCell>
                                            <TableCell>{(t.lineItems || []).length}</TableCell>
                                        </TableRow>
                                    ))}
                                </TableBody>
                            </Table>
                        )}
                    </DialogContent>
                </>
            );
        }
        if (dialogOpen === 'members') {
            return (
                <>
                    <DialogTitle sx={{ fontWeight: 700 }}>👥 All Members ({totalMembers})</DialogTitle>
                    <DialogContent dividers>
                        {allItems.length === 0 ? (
                            <Typography color="text.secondary">No members</Typography>
                        ) : (
                            <Table size="small">
                                <TableHead>
                                    <TableRow>
                                        <TableCell sx={{ fontWeight: 700 }}>#</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Name</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Career Level</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Supervisor</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Team</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Lead</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Hrs</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Type</TableCell>
                                    </TableRow>
                                </TableHead>
                                <TableBody>
                                    {allItems.map((li, i) => (
                                        <TableRow key={li.id}>
                                            <TableCell>{i + 1}</TableCell>
                                            <TableCell>{li.name}</TableCell>
                                            <TableCell>{li.careerLevel || '—'}</TableCell>
                                            <TableCell>{li.supervisor || '—'}</TableCell>
                                            <TableCell>{li.teamName}</TableCell>
                                            <TableCell>{li.leadName}</TableCell>
                                            <TableCell sx={{ whiteSpace: 'nowrap' }}>{calcTotalHoursCSV(li.time) || '—'}</TableCell>
                                            <TableCell>
                                                <Chip label={li.allowanceCompoff} size="small"
                                                    color={li.allowanceCompoff === 'Allowance' ? 'success' : 'warning'} />
                                            </TableCell>
                                        </TableRow>
                                    ))}
                                </TableBody>
                            </Table>
                        )}
                    </DialogContent>
                </>
            );
        }
        if (dialogOpen === 'allowance') {
            return (
                <>
                    <DialogTitle sx={{ fontWeight: 700 }}>💰 Shift Allowance ({allowanceItems.length})</DialogTitle>
                    <DialogContent dividers>
                        {allowanceItems.length === 0 ? (
                            <Typography color="text.secondary">No members with Shift Allowance</Typography>
                        ) : (
                            <Table size="small">
                                <TableHead>
                                    <TableRow>
                                        <TableCell sx={{ fontWeight: 700 }}>#</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Name</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Career Level</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Supervisor</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Team</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Lead</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Login Time</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Logout Time</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Hrs</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Support type to be charged in myte</TableCell>
                                    </TableRow>
                                </TableHead>
                                <TableBody>
                                    {allowanceItems.map((li, i) => {
                                        const totalHrs = calcTotalHoursCSV(li.time);
                                        return (
                                            <TableRow key={li.id}>
                                                <TableCell>{i + 1}</TableCell>
                                                <TableCell>{li.name}</TableCell>
                                                <TableCell>{li.careerLevel || '—'}</TableCell>
                                                <TableCell>{li.supervisor || '—'}</TableCell>
                                                <TableCell>{li.teamName}</TableCell>
                                                <TableCell>{li.leadName}</TableCell>
                                                <TableCell sx={{ whiteSpace: 'nowrap' }}>{getLoginTime(li.time) || '—'}</TableCell>
                                                <TableCell sx={{ whiteSpace: 'nowrap' }}>{getLogoutTime(li.time) || '—'}</TableCell>
                                                <TableCell sx={{ whiteSpace: 'nowrap' }}>{totalHrs || '—'}</TableCell>
                                                <TableCell sx={{ whiteSpace: 'nowrap', color: getSupportType(totalHrs) === 'On Call Primary Support' ? '#34d399' : getSupportType(totalHrs) === 'On Call Secondary Support' ? '#fbbf24' : 'inherit' }}>
                                                    {getSupportType(totalHrs) || '—'}
                                                </TableCell>
                                            </TableRow>
                                        );
                                    })}
                                </TableBody>
                            </Table>
                        )}
                    </DialogContent>
                </>
            );
        }
        if (dialogOpen === 'compoff') {
            return (
                <>
                    <DialogTitle sx={{ fontWeight: 700 }}>✅ Comp-off ({compoffItems.length})</DialogTitle>
                    <DialogContent dividers>
                        {compoffItems.length === 0 ? (
                            <Typography color="text.secondary">No members with Comp-off</Typography>
                        ) : (
                            <Table size="small">
                                <TableHead>
                                    <TableRow>
                                        <TableCell sx={{ fontWeight: 700 }}>#</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Name</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Career Level</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Supervisor</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Team</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Lead</TableCell>
                                        <TableCell sx={{ fontWeight: 700 }}>Hrs</TableCell>
                                    </TableRow>
                                </TableHead>
                                <TableBody>
                                    {compoffItems.map((li, i) => (
                                        <TableRow key={li.id}>
                                            <TableCell>{i + 1}</TableCell>
                                            <TableCell>{li.name}</TableCell>
                                            <TableCell>{li.careerLevel || '—'}</TableCell>
                                            <TableCell>{li.supervisor || '—'}</TableCell>
                                            <TableCell>{li.teamName}</TableCell>
                                            <TableCell>{li.leadName}</TableCell>
                                            <TableCell sx={{ whiteSpace: 'nowrap' }}>{calcTotalHoursCSV(li.time) || '—'}</TableCell>
                                        </TableRow>
                                    ))}
                                </TableBody>
                            </Table>
                        )}
                    </DialogContent>
                </>
            );
        }
        return null;
    };

    return (
        <Box sx={{ mb: 3 }}>
            {/* Release Owner + Created By meta + Sanity Sheet */}
            <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', mb: 2, alignItems: 'center' }}>
                <Chip label={`Release Owner: ${entry.releaseOwner}`} size="small"
                    sx={{ bgcolor: '#312e81', color: '#e0e7ff' }} />
                <Chip label={`Created By: ${entry.createdBy}`} size="small" sx={{ bgcolor: '#312e81', color: '#e0e7ff' }} />
                {entry.sanityFile ? (
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                        <Tooltip title="View uploaded sanity sheet">
                            <Chip icon={<DescriptionIcon />} label="Sanity Sheet"
                                size="small" clickable color="primary" component="a"
                                href={process.env.NODE_ENV === 'production' ? `/uploads/${entry.sanityFile}` : `http://${window.location.hostname}:5000/uploads/${entry.sanityFile}`}
                                target="_blank" rel="noreferrer" />
                        </Tooltip>
                        {!isLeadOnly && (
                            <Tooltip title="Re-upload Sanity Sheet">
                                <IconButton size="small" onClick={() => reuploadInputRef.current?.click()}
                                    sx={{ color: '#a5b4fc', '&:hover': { color: '#818cf8' } }}>
                                    <CachedIcon fontSize="small" />
                                </IconButton>
                            </Tooltip>
                        )}
                        {!isLeadOnly && (
                            <input ref={reuploadInputRef} type="file" hidden accept=".xlsx,.xls,.csv,.pdf"
                                onChange={handleSanityUpload} aria-label="Re-upload sanity sheet" />
                        )}
                    </Box>
                ) : (
                    !isLeadOnly ? (
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                            <Tooltip title="Upload Sanity Sheet (.xlsx, .xls, .csv, .pdf)">
                                <Button size="small" variant="outlined" startIcon={<CloudUploadIcon />}
                                    onClick={() => fileInputRef.current?.click()}
                                    sx={{ textTransform: 'none', ml: 0.5, color: '#a5b4fc', borderColor: '#4f46e5' }}>
                                    Upload Sanity Sheet
                                </Button>
                            </Tooltip>
                            <Tooltip title="Re-upload Sanity Sheet">
                                <IconButton size="small" onClick={() => fileInputRef.current?.click()}
                                    sx={{ color: '#a5b4fc', '&:hover': { color: '#818cf8' } }}>
                                    <CachedIcon fontSize="small" />
                                </IconButton>
                            </Tooltip>
                            <input ref={fileInputRef} type="file" hidden accept=".xlsx,.xls,.csv,.pdf"
                                onChange={handleSanityUpload} aria-label="Upload sanity sheet" />
                        </Box>
                    ) : null
                )}
            </Box>

            {/* Summary cards — clickable */}
            <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 2 }}>
                <Card sx={{ borderTop: '4px solid #4f46e5', borderRadius: 2, cursor: 'pointer', bgcolor: '#1a1744', '&:hover': { boxShadow: 4, transform: 'translateY(-2px)' }, transition: 'all .2s' }}
                    onClick={() => setDialogOpen('teams')}>
                    <CardContent sx={{ textAlign: 'center', py: 2 }}>
                        <GroupsIcon sx={{ color: '#818cf8', fontSize: 28, mb: 0.5 }} />
                        <Typography variant="h4" fontWeight={800} sx={{ color: '#e0e7ff' }}>{totalTeams}</Typography>
                        <Typography variant="caption" color="#a5b4fc" fontWeight={600}
                            sx={{ textTransform: 'uppercase', letterSpacing: '.03em' }}>
                            Total Teams
                        </Typography>
                    </CardContent>
                </Card>
                <Card sx={{ borderTop: '4px solid #0891b2', borderRadius: 2, cursor: 'pointer', bgcolor: '#1a1744', '&:hover': { boxShadow: 4, transform: 'translateY(-2px)' }, transition: 'all .2s' }}
                    onClick={() => setDialogOpen('members')}>
                    <CardContent sx={{ textAlign: 'center', py: 2 }}>
                        <PeopleIcon sx={{ color: '#22d3ee', fontSize: 28, mb: 0.5 }} />
                        <Typography variant="h4" fontWeight={800} sx={{ color: '#e0e7ff' }}>{totalMembers}</Typography>
                        <Typography variant="caption" color="#a5b4fc" fontWeight={600}
                            sx={{ textTransform: 'uppercase', letterSpacing: '.03em' }}>
                            Total Members
                        </Typography>
                    </CardContent>
                </Card>
                <Card sx={{ borderTop: '4px solid #059669', borderRadius: 2, cursor: 'pointer', bgcolor: '#1a1744', '&:hover': { boxShadow: 4, transform: 'translateY(-2px)' }, transition: 'all .2s' }}
                    onClick={() => setDialogOpen('allowance')}>
                    <CardContent sx={{ textAlign: 'center', py: 2 }}>
                        <PaidIcon sx={{ color: '#34d399', fontSize: 28, mb: 0.5 }} />
                        <Typography variant="h4" fontWeight={800} sx={{ color: '#e0e7ff' }}>{allowanceItems.length}</Typography>
                        <Typography variant="caption" color="#a5b4fc" fontWeight={600}
                            sx={{ textTransform: 'uppercase', letterSpacing: '.03em' }}>
                            Shift Allowance
                        </Typography>
                    </CardContent>
                </Card>
                <Card sx={{ borderTop: '4px solid #d97706', borderRadius: 2, cursor: 'pointer', bgcolor: '#1a1744', '&:hover': { boxShadow: 4, transform: 'translateY(-2px)' }, transition: 'all .2s' }}
                    onClick={() => setDialogOpen('compoff')}>
                    <CardContent sx={{ textAlign: 'center', py: 2 }}>
                        <EventAvailableIcon sx={{ color: '#fbbf24', fontSize: 28, mb: 0.5 }} />
                        <Typography variant="h4" fontWeight={800} sx={{ color: '#e0e7ff' }}>{compoffItems.length}</Typography>
                        <Typography variant="caption" color="#a5b4fc" fontWeight={600}
                            sx={{ textTransform: 'uppercase', letterSpacing: '.03em' }}>
                            Comp-off
                        </Typography>
                    </CardContent>
                </Card>
            </Box>

            {/* Detail Dialog */}
            <Dialog open={!!dialogOpen} onClose={() => setDialogOpen(null)}
                maxWidth="md" fullWidth
                PaperProps={{ sx: { borderRadius: 2 } }}>
                {renderDialogContent()}
                <DialogActions>
                    <Button startIcon={<FileDownloadIcon />} onClick={handleExportDialog}
                        sx={{ textTransform: 'none' }}>
                        Export
                    </Button>
                    <Button onClick={() => setDialogOpen(null)} sx={{ textTransform: 'none' }}>Close</Button>
                </DialogActions>
            </Dialog>
        </Box>
    );
}
