// Generated by GitHub Copilot
import React, { useState } from 'react';
import { useAppContext } from '../context/AppContext';
import { useAuth } from '../context/AuthContext';
import api from '../utils/api';
import ConfirmDialog from './ConfirmDialog';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import Chip from '@mui/material/Chip';
import Collapse from '@mui/material/Collapse';
import Table from '@mui/material/Table';
import TableHead from '@mui/material/TableHead';
import TableBody from '@mui/material/TableBody';
import TableRow from '@mui/material/TableRow';
import TableCell from '@mui/material/TableCell';
import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';
import Button from '@mui/material/Button';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import ExpandLessIcon from '@mui/icons-material/ExpandLess';
import DeleteIcon from '@mui/icons-material/Delete';
import EditIcon from '@mui/icons-material/Edit';
import CheckIcon from '@mui/icons-material/Check';
import CloseIcon from '@mui/icons-material/Close';

/**
 * Team card with expand/collapse and inline edit.
 * Clicking team name navigates to Team Details screen.
 * Edit icon allows editing Team Name and Lead Name inline.
 */
export default function TeamCard({ team, entryId, onRefresh }) {
    const { navigateToTeam, addToast, employees } = useAppContext();
    const { isLeadOnly, empId } = useAuth();
    // CL9 lead: they can only interact with their own team
    const isMyTeam = team.leadName.toLowerCase() === (empId || '').toLowerCase();
    const [expanded, setExpanded] = useState(false);
    const [confirmDelete, setConfirmDelete] = useState(false);
    const [editing, setEditing] = useState(false);
    const [editTeamName, setEditTeamName] = useState(team.teamName);
    const [editLeadName, setEditLeadName] = useState(team.leadName);
    const [saving, setSaving] = useState(false);

    // Lead suggestions: CL 9 and below (supervisors/leads)
    const leadOptions = employees.filter(e => {
        const cl = parseInt(String(e.careerLevel || '').replace(/[^0-9]/g, ''), 10);
        return !isNaN(cl) && cl <= 9;
    });

    const getLeadSuggestions = (input) => {
        if (!input || input.length < 2) return [];
        const q = input.toLowerCase();
        return leadOptions
            .filter(e => e.name.toLowerCase().includes(q) || e.id.toLowerCase().includes(q))
            .slice(0, 10);
    };

    const totalResources = (team.lineItems || []).length;

    const handleDelete = async () => {
        try {
            await api.deleteTeam(entryId, team.id);
            addToast(`Team "${team.teamName}" deleted`, 'success');
            onRefresh();
        } catch (err) { addToast(err.message, 'error'); }
        setConfirmDelete(false);
    };

    const handleEditSave = async () => {
        if (!editTeamName.trim() || !editLeadName.trim()) {
            addToast('Team Name and Lead Name are required', 'error');
            return;
        }
        setSaving(true);
        try {
            await api.updateTeam(entryId, team.id, {
                teamName: editTeamName.trim(),
                leadName: editLeadName.trim(),
            });

            // If lead changed, replace line items with new lead's subordinates
            if (editLeadName.trim().toLowerCase() !== team.leadName.toLowerCase()) {
                const leadRecord = employees.find(e =>
                    e.name.toLowerCase() === editLeadName.trim().toLowerCase() ||
                    e.id.toLowerCase() === editLeadName.trim().toLowerCase()
                );
                const supervisorId = leadRecord ? leadRecord.id.toLowerCase() : editLeadName.trim().toLowerCase();
                const supervisorName = leadRecord ? leadRecord.name.toLowerCase() : editLeadName.trim().toLowerCase();

                const subordinates = employees.filter(e => {
                    const sv = (e.supervisor || '').toLowerCase().trim();
                    if (!sv) return false;
                    return sv === supervisorId || sv === supervisorName;
                }).filter(e => {
                    const cl = parseInt(String(e.careerLevel || '').replace(/[^0-9]/g, ''), 10);
                    return !isNaN(cl) && cl >= 9;
                });

                const items = subordinates.map(e => ({
                    name: e.name,
                    careerLevel: e.careerLevel || '',
                    supervisor: e.supervisor || '',
                    allowanceCompoff: 'Compoff',
                    time: '11:00 AM - ',
                    notes: '',
                }));
                await api.saveAllLineItems(entryId, team.id, items);
                addToast(`Team updated — ${subordinates.length} resource(s) loaded for new lead`, 'success');
            } else {
                addToast(`Team "${editTeamName.trim()}" updated`, 'success');
            }

            setEditing(false);
            onRefresh();
        } catch (err) { addToast(err.message, 'error'); }
        setSaving(false);
    };

    const handleEditCancel = () => {
        setEditTeamName(team.teamName);
        setEditLeadName(team.leadName);
        setEditing(false);
    };

    return (
        <Card sx={{ mb: 1.5, borderRadius: 2, border: '1px solid #312e81', bgcolor: '#1a1744' }}>
            {/* Header row */}
            <Box sx={{ display: 'flex', alignItems: 'center', px: 2, py: 1.5, cursor: 'pointer', '&:hover': { bgcolor: '#241f5c' } }}
                onClick={() => !editing && setExpanded(p => !p)}>
                <IconButton size="small" sx={{ mr: 1, color: '#a5b4fc' }}>
                    {expanded ? <ExpandLessIcon fontSize="small" /> : <ExpandMoreIcon fontSize="small" />}
                </IconButton>
                <Box sx={{ flex: 1, minWidth: 0 }}>
                    {editing ? (
                        <Box sx={{ display: 'flex', gap: 1.5, alignItems: 'center', flexWrap: 'wrap' }}
                            onClick={e => e.stopPropagation()}>
                            <TextField size="small" label="Team Name" value={editTeamName}
                                onChange={e => setEditTeamName(e.target.value)}
                                sx={{ minWidth: 160 }} />
                            <Autocomplete
                                freeSolo
                                size="small"
                                options={getLeadSuggestions(editLeadName)}
                                getOptionLabel={o => typeof o === 'string' ? o : o.name}
                                inputValue={editLeadName}
                                onInputChange={(_, val) => setEditLeadName(val)}
                                onChange={(_, val) => { if (val && typeof val === 'object') setEditLeadName(val.name); }}
                                filterOptions={x => x}
                                renderOption={(props, o) => (
                                    <li {...props} key={o.id}>
                                        <Box>
                                            <Typography sx={{ fontSize: 12, fontWeight: 600 }}>{o.name}</Typography>
                                            <Typography sx={{ fontSize: 10, color: '#a5b4fc' }}>{o.careerLevel}{o.supervisor ? ` • ${o.supervisor}` : ''}</Typography>
                                        </Box>
                                    </li>
                                )}
                                renderInput={(params) => (
                                    <TextField {...params} size="small" label="Lead Name" placeholder="Type 2+ chars" sx={{ minWidth: 200 }} />
                                )}
                                sx={{ minWidth: 200 }}
                            />
                            <IconButton size="small" color="success" onClick={handleEditSave}
                                disabled={saving} title="Save">
                                <CheckIcon fontSize="small" />
                            </IconButton>
                            <IconButton size="small" color="error" onClick={handleEditCancel}
                                title="Cancel">
                                <CloseIcon fontSize="small" />
                            </IconButton>
                        </Box>
                    ) : (
                        <>
                            <Typography variant="subtitle2" fontWeight={700}
                                onClick={(e) => {
                                    e.stopPropagation();
                                    if (isLeadOnly && !isMyTeam) return;
                                    navigateToTeam(team.id);
                                }}
                                sx={{
                                    cursor: (isLeadOnly && !isMyTeam) ? 'default' : 'pointer',
                                    color: (isLeadOnly && !isMyTeam) ? '#6b7280' : '#e0e7ff',
                                    '&:hover': (isLeadOnly && !isMyTeam) ? {} : { color: '#818cf8', textDecoration: 'underline' }
                                }}>
                                {team.teamName}
                            </Typography>
                            <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', mt: 0.5 }}>
                                <Chip label={`Lead: ${team.leadName}`} size="small" variant="outlined" sx={{ borderColor: '#4f46e5', color: '#c7d2fe' }} />
                                <Chip label={`Date: ${team.createdDate}`} size="small" variant="outlined" sx={{ borderColor: '#4f46e5', color: '#c7d2fe' }} />
                                <Chip label={`Resources: ${totalResources}`} size="small" variant="outlined" sx={{ borderColor: '#4f46e5', color: '#c7d2fe' }} />
                                <Chip label={`Created By: ${team.createdBy}`} size="small" variant="outlined" sx={{ borderColor: '#4f46e5', color: '#c7d2fe' }} />
                            </Box>
                        </>
                    )}
                </Box>
                {/* Show edit/delete for full-access users, OR for CL9 leads viewing their own team */}
                {!editing && (isMyTeam || !isLeadOnly) && (
                    <Box sx={{ display: 'flex', gap: 0.5 }}>
                        <IconButton size="small" onClick={(e) => {
                            e.stopPropagation();
                            setEditTeamName(team.teamName);
                            setEditLeadName(team.leadName);
                            setEditing(true);
                        }} aria-label="Edit team" title="Edit team">
                            <EditIcon sx={{ fontSize: 18, color: '#a5b4fc' }} />
                        </IconButton>
                        <IconButton size="small" onClick={(e) => { e.stopPropagation(); setConfirmDelete(true); }}
                            aria-label="Delete team">
                            <DeleteIcon sx={{ fontSize: 18, color: '#a5b4fc' }} />
                        </IconButton>
                    </Box>
                )}
            </Box>

            {/* Expanded body */}
            <Collapse in={expanded}>
                <CardContent sx={{ pt: 0, bgcolor: '#0f0e2a', borderTop: '1px solid #312e81' }}>
                    {(team.lineItems || []).length === 0 ? (
                        <Typography variant="body2" sx={{ py: 2, textAlign: 'center', color: '#a5b4fc' }}>
                            No line items. Click team name to add members.
                        </Typography>
                    ) : (
                        <Table size="small" sx={{ mt: 1 }}>
                            <TableHead>
                                <TableRow>
                                    <TableCell sx={{ fontWeight: 700, fontSize: 12, color: '#c7d2fe' }}>#</TableCell>
                                    <TableCell sx={{ fontWeight: 700, fontSize: 12, color: '#c7d2fe' }}>Name</TableCell>
                                    <TableCell sx={{ fontWeight: 700, fontSize: 12, color: '#c7d2fe' }}>Compoff / Allowance</TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                {team.lineItems.map((li, i) => (
                                    <TableRow key={li.id}>
                                        <TableCell sx={{ color: '#e0e7ff' }}>{i + 1}</TableCell>
                                        <TableCell sx={{ color: '#e0e7ff' }}>{li.name}</TableCell>
                                        <TableCell>
                                            <Chip size="small" label={li.allowanceCompoff}
                                                color={li.allowanceCompoff === 'Allowance' ? 'success' : 'warning'} />
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    )}
                </CardContent>
            </Collapse>

            <ConfirmDialog open={confirmDelete} title="Delete Team"
                message={`Are you sure you want to delete team "${team.teamName}"?`}
                onYes={handleDelete} onNo={() => setConfirmDelete(false)} />
        </Card>
    );
}
