// Generated by GitHub Copilot
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useAppContext } from '../context/AppContext';
import api from '../utils/api';
import * as XLSX from 'xlsx';
import ConfirmDialog from './ConfirmDialog';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import Chip from '@mui/material/Chip';
import Table from '@mui/material/Table';
import TableHead from '@mui/material/TableHead';
import TableBody from '@mui/material/TableBody';
import TableRow from '@mui/material/TableRow';
import TableCell from '@mui/material/TableCell';
import MenuItem from '@mui/material/MenuItem';
import Select from '@mui/material/Select';
import Autocomplete from '@mui/material/Autocomplete';
import Alert from '@mui/material/Alert';
import Tooltip from '@mui/material/Tooltip';
import FilterListIcon from '@mui/icons-material/FilterList';
import AddIcon from '@mui/icons-material/Add';
import EditIcon from '@mui/icons-material/Edit';
import CheckIcon from '@mui/icons-material/Check';
import DeleteIcon from '@mui/icons-material/Delete';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import FileDownloadIcon from '@mui/icons-material/FileDownload';
import SaveIcon from '@mui/icons-material/Save';
import CancelIcon from '@mui/icons-material/Cancel';

// Generated by GitHub Copilot
/** Half-hour time options (12-hour format) for the dropdown pickers */
const TIME_OPTIONS = (() => {
    const opts = [];
    for (let h = 0; h < 24; h++) {
        for (const m of [0, 30]) {
            const hr12 = h === 0 ? 12 : h > 12 ? h - 12 : h;
            const period = h < 12 ? 'AM' : 'PM';
            const minStr = m === 0 ? '00' : '30';
            opts.push(`${hr12}:${minStr} ${period}`);
        }
    }
    return opts;
})();

/**
 * Parse a 12-hour time string to minutes from midnight.
 * Supports: "9:30 AM", "12:00 PM", "1 PM", etc.
 * @param {string} s
 * @returns {number} minutes from midnight, or NaN
 */
function parseTimeToMinutes(s) {
    if (!s) return NaN;
    const m = s.trim().match(/^(\d{1,2})(?::(\d{2}))?\s*(AM|PM)$/i);
    if (!m) return NaN;
    let h = parseInt(m[1], 10);
    const min = m[2] ? parseInt(m[2], 10) : 0;
    const period = m[3].toUpperCase();
    if (h === 12) h = 0;
    if (period === 'PM') h += 12;
    return h * 60 + min;
}

/**
 * Calculate total hours from a time range string like "9:30 AM - 5:00 PM".
 * @param {string} timeStr
 * @returns {string} e.g. "7.5 hrs" or ""
 */
function calcTotalHours(timeStr) {
    if (!timeStr || !timeStr.includes('-')) return '';
    const parts = timeStr.split('-').map(s => s.trim());
    if (parts.length !== 2) return '';
    const start = parseTimeToMinutes(parts[0]);
    const end = parseTimeToMinutes(parts[1]);
    if (isNaN(start) || isNaN(end)) return '';
    let diff = end - start;
    if (diff <= 0) diff += 24 * 60;
    const hrs = diff / 60;
    return `${hrs % 1 === 0 ? hrs : hrs.toFixed(1)} hrs`;
}

/**
 * Team Details screen with dropdown time pickers (half-hour intervals),
 * auto-calculated Total Hours, and hidden filter row under headers.
 * Career Level column removed per user request.
 */
export default function TeamDetail({ entryId, teamId, onRefresh }) {
    const { currentEntry, addToast, registerUnsavedCheck, unregisterUnsavedCheck, registerSaveCallback, unregisterSaveCallback, employees } = useAppContext();
    const team = currentEntry?.teams?.find(t => t.id === teamId);

    const [lineItems, setLineItems] = useState([]);
    const [savedSnapshot, setSavedSnapshot] = useState([]);
    const [newName, setNewName] = useState('');
    const [error, setError] = useState('');
    const [editingId, setEditingId] = useState(null);
    const [deleteTarget, setDeleteTarget] = useState(null);
    const [uploadError, setUploadError] = useState('');
    const [saving, setSaving] = useState(false);
    const [showFilters, setShowFilters] = useState(false);
    const [filters, setFilters] = useState({ name: '', careerLevel: '', supervisor: '', loginTime: '', logoutTime: '', allowanceCompoff: '' });
    const fileInputRef = useRef(null);

    const syncFromServer = useCallback(() => {
        if (team) {
            const snap = JSON.parse(JSON.stringify(team.lineItems || []));
            setLineItems(snap);
            setSavedSnapshot(JSON.parse(JSON.stringify(snap)));
        }
    }, [team]);

    useEffect(() => { syncFromServer(); }, [syncFromServer]);

    // Register unsaved-changes guard with AppContext navigation
    const hasChanges = JSON.stringify(lineItems) !== JSON.stringify(savedSnapshot);
    useEffect(() => {
        registerUnsavedCheck(() => JSON.stringify(lineItems) !== JSON.stringify(savedSnapshot));
        registerSaveCallback(handleSave);
        return () => { unregisterUnsavedCheck(); unregisterSaveCallback(); };
    }); // no deps — always reflects latest

    if (!team) return <Typography color="text.disabled" sx={{ py: 4, textAlign: 'center' }}>Team not found</Typography>;

    /** Only employees with career level 10 and above (numeric) */
    const eligibleEmployees = employees.filter(e => {
        const cl = parseInt(String(e.careerLevel || '').replace(/[^0-9]/g, ''), 10);
        return !isNaN(cl) && cl >= 10;
    });

    /** Lookup career level from employee directory by name or ID */
    const lookupCareerLevel = (name) => {
        const match = employees.find(e =>
            e.id.toLowerCase() === name.toLowerCase() ||
            e.name.toLowerCase() === name.toLowerCase());
        return match ? match.careerLevel : '';
    };

    /** Lookup full employee record by name or ID — only eligible (10+) */
    const lookupEmployee = (name) =>
        eligibleEmployees.find(e =>
            e.id.toLowerCase() === name.toLowerCase() ||
            e.name.toLowerCase() === name.toLowerCase());

    /** Employees filtered by 2+ char input for autocomplete — only 10+ career level */
    const getNameSuggestions = (input) => {
        if (!input || input.length < 2) return [];
        const q = input.toLowerCase();
        return eligibleEmployees
            .filter(e => e.name.toLowerCase().includes(q) || e.id.toLowerCase().includes(q))
            .slice(0, 10);
    };

    /** Parse stored time string into start/end parts */
    const parseTimeParts = (timeStr) => {
        if (!timeStr || !timeStr.includes('-')) return { start: '', end: '' };
        const parts = timeStr.split('-').map(s => s.trim());
        return { start: parts[0] || '', end: parts[1] || '' };
    };

    /** Build time string from start + end selections */
    const buildTimeStr = (start, end) => {
        if (!start && !end) return '';
        return `${start || ''} - ${end || ''}`.trim();
    };

    // ── Add Line Item ──
    const handleAdd = () => {
        if (!newName.trim()) { setError('Name is required'); return; }
        const trimmed = newName.trim();
        // Validate against resource list (10+ only)
        if (eligibleEmployees.length > 0) {
            const valid = eligibleEmployees.some(e =>
                e.name.toLowerCase() === trimmed.toLowerCase() ||
                e.id.toLowerCase() === trimmed.toLowerCase()
            );
            if (!valid) { setError('Enter valid Name'); return; }
        }
        const duplicate = lineItems.find(li => li.name.toLowerCase() === trimmed.toLowerCase());
        if (duplicate) { setError(`"${trimmed}" already exists in this team`); return; }
        const emp = lookupEmployee(trimmed);
        setLineItems(prev => [...prev, {
            id: `temp-${Date.now()}`, name: emp ? emp.name : trimmed,
            careerLevel: emp ? (emp.careerLevel || '') : '', supervisor: emp ? (emp.supervisor || '') : '',
            allowanceCompoff: 'Compoff', time: '',
        }]);
        setNewName('');
        setError('');
    };

    const updateField = (id, field, value) => {
        setLineItems(prev => prev.map(li => li.id === id ? { ...li, [field]: value } : li));
    };

    const handleDeleteConfirm = () => {
        if (!deleteTarget) return;
        setLineItems(prev => prev.filter(li => li.id !== deleteTarget.id));
        setDeleteTarget(null);
    };

    const handleSave = async () => {
        setSaving(true);
        try {
            const saved = await api.saveAllLineItems(entryId, teamId, lineItems);
            setSavedSnapshot(JSON.parse(JSON.stringify(saved)));
            setLineItems(JSON.parse(JSON.stringify(saved)));
            addToast('Changes saved successfully', 'success');
            onRefresh();
            setSaving(false);
            return true;
        } catch (err) { addToast(err.message, 'error'); setSaving(false); return false; }
    };

    const handleCancel = () => {
        setLineItems(JSON.parse(JSON.stringify(savedSnapshot)));
        setEditingId(null);
        addToast('Changes discarded', 'info');
    };

    // ── Excel Upload (supports AM/PM time columns) ──
    const handleFileUpload = (e) => {
        const file = e.target.files[0];
        if (!file) return;
        setUploadError('');
        const reader = new FileReader();
        reader.onload = (evt) => {
            try {
                const data = new Uint8Array(evt.target.result);
                const wb = XLSX.read(data, { type: 'array' });
                const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { defval: '' });
                if (rows.length === 0) { setUploadError('Excel file is empty'); return; }

                const firstRow = rows[0];
                const hasName = Object.keys(firstRow).some(k => k.toLowerCase().includes('name'));
                if (!hasName) { setUploadError('Excel must have a "Name" column'); return; }

                const newItems = [];
                const overwritten = [];
                const skippedLowLevel = [];
                rows.forEach((row, idx) => {
                    const nameKey = Object.keys(row).find(k => k.toLowerCase().includes('name'));
                    const name = String(row[nameKey] || '').trim();
                    if (!name) return;
                    const clKey = Object.keys(row).find(k =>
                        k.toLowerCase().includes('career') || k.toLowerCase().includes('level'));
                    let cl = clKey ? String(row[clKey] || '').trim() : '';
                    // Auto-lookup from resource list (10+ only)
                    const empRecord = lookupEmployee(name);
                    if (!cl && empRecord) cl = empRecord.careerLevel || '';
                    // Skip employees with career level 9 and below
                    const clNum = parseInt(String(cl || '').replace(/[^0-9]/g, ''), 10);
                    if (!isNaN(clNum) && clNum <= 9) { skippedLowLevel.push(name); return; }
                    // Also skip if not found at all in eligible (10+) resource list
                    if (employees.length > 0 && !empRecord) { skippedLowLevel.push(name); return; }
                    const svKey = Object.keys(row).find(k => k.toLowerCase().includes('supervisor'));
                    let sv = svKey ? String(row[svKey] || '').trim() : '';
                    if (!sv && empRecord) sv = empRecord.supervisor || '';
                    const acKey = Object.keys(row).find(k =>
                        k.toLowerCase().includes('allowance') || k.toLowerCase().includes('compoff'));
                    let ac = 'Compoff';
                    if (acKey) {
                        const val = String(row[acKey] || '').trim().toLowerCase();
                        if (val.includes('allowance')) ac = 'Allowance';
                    }
                    // Support "Time", "Login Time"/"Logout Time", or "Start Time"/"End Time" columns
                    const timeKey = Object.keys(row).find(k => k.toLowerCase() === 'time');
                    const loginTimeKey = Object.keys(row).find(k =>
                        k.toLowerCase().includes('login') || k.toLowerCase().includes('start'));
                    const logoutTimeKey = Object.keys(row).find(k =>
                        k.toLowerCase().includes('logout') || k.toLowerCase().includes('end'));
                    let time = '';
                    if (timeKey) {
                        time = String(row[timeKey] || '').trim();
                    } else if (loginTimeKey && logoutTimeKey) {
                        const st = String(row[loginTimeKey] || '').trim();
                        const et = String(row[logoutTimeKey] || '').trim();
                        if (st && et) time = `${st} - ${et}`;
                        else if (st) time = `${st} - `;
                        else if (et) time = ` - ${et}`;
                    } else if (loginTimeKey) {
                        const st = String(row[loginTimeKey] || '').trim();
                        if (st) time = `${st} - `;
                    } else if (logoutTimeKey) {
                        const et = String(row[logoutTimeKey] || '').trim();
                        if (et) time = ` - ${et}`;
                    }

                    const existingIdx = lineItems.findIndex(li =>
                        li.name.toLowerCase() === name.toLowerCase());
                    if (existingIdx !== -1) {
                        lineItems[existingIdx] = {
                            ...lineItems[existingIdx], name,
                            careerLevel: cl || lineItems[existingIdx].careerLevel,
                            supervisor: sv || lineItems[existingIdx].supervisor || '',
                            allowanceCompoff: ac,
                            time: time || lineItems[existingIdx].time || '',
                        };
                        overwritten.push(name);
                    } else {
                        newItems.push({ id: `upload-${Date.now()}-${idx}`, name, careerLevel: cl, supervisor: sv, allowanceCompoff: ac, time: time || '' });
                    }
                });

                if (newItems.length === 0 && overwritten.length === 0) { setUploadError('No valid rows found. Ensure employees have career level 10 or above.'); return; }
                setLineItems(() => {
                    const updated = [...lineItems];
                    return [...updated.filter(li => !newItems.some(ni => ni.id === li.id)), ...newItems];
                });
                const msgs = [];
                if (newItems.length > 0) msgs.push(`${newItems.length} added`);
                if (overwritten.length > 0) msgs.push(`${overwritten.length} overwritten`);
                if (skippedLowLevel.length > 0) msgs.push(`${skippedLowLevel.length} skipped (career level < 10)`);
                addToast(`Excel import: ${msgs.join(', ')}`, 'success');
            } catch {
                setUploadError('Failed to parse Excel file');
                addToast('Excel parse error', 'error');
            }
        };
        reader.readAsArrayBuffer(file);
        e.target.value = '';
    };

    const handleExport = () => { window.open(api.getTeamExportUrl(entryId, teamId), '_blank'); };
    const filteredItems = lineItems.filter(li => {
        if (filters.name && !li.name.toLowerCase().includes(filters.name.toLowerCase())) return false;
        if (filters.careerLevel && !(li.careerLevel || '').toLowerCase().includes(filters.careerLevel.toLowerCase())) return false;
        if (filters.supervisor && !(li.supervisor || '').toLowerCase().includes(filters.supervisor.toLowerCase())) return false;
        const { start, end } = parseTimeParts(li.time);
        if (filters.loginTime && !(start.toLowerCase().includes(filters.loginTime.toLowerCase()))) return false;
        if (filters.logoutTime && !(end.toLowerCase().includes(filters.logoutTime.toLowerCase()))) return false;
        if (filters.allowanceCompoff && filters.allowanceCompoff !== 'All' && li.allowanceCompoff !== filters.allowanceCompoff) return false;
        return true;
    });

    const setFilter = (key, val) => setFilters(prev => ({ ...prev, [key]: val }));

    return (
        <Box>
            {/* Top bar: Created By + Upload + Export */}
            <Card sx={{ mb: 2, borderRadius: 2, bgcolor: '#1a1744', border: '1px solid #312e81' }}>
                <CardContent sx={{ py: 1.5, display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 1 }}>
                    <Box sx={{ flex: 1, display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                        <Chip label={`Created By: ${team.createdBy}`} size="small" sx={{ bgcolor: '#312e81', color: '#e0e7ff' }} />
                        <Chip label={`Team: ${team.teamName}`} size="small" variant="outlined" sx={{ borderColor: '#4f46e5', color: '#c7d2fe' }} />
                        <Chip label={`Lead: ${team.leadName}`} size="small" variant="outlined" sx={{ borderColor: '#4f46e5', color: '#c7d2fe' }} />
                    </Box>
                    <Tooltip title="Upload (.xlsx, .csv)">
                        <Button size="small" startIcon={<CloudUploadIcon />}
                            onClick={() => fileInputRef.current?.click()}
                            sx={{ textTransform: 'none' }}>
                            Upload
                        </Button>
                    </Tooltip>
                    <input ref={fileInputRef} type="file" hidden accept=".xlsx,.xls,.csv"
                        onChange={handleFileUpload} aria-label="Upload file" />
                    <Tooltip title="Export to CSV">
                        <Button size="small" startIcon={<FileDownloadIcon />} onClick={handleExport}
                            sx={{ textTransform: 'none' }}>
                            Export
                        </Button>
                    </Tooltip>
                </CardContent>
            </Card>

            {uploadError && <Alert severity="error" sx={{ mb: 2 }}>{uploadError}</Alert>}

            {/* Add Line Item */}
            <Card sx={{ mb: 2, borderRadius: 2, bgcolor: '#1a1744', border: '1px solid #312e81' }}>
                <CardContent sx={{ py: 1.5, display: 'flex', gap: 1.5, alignItems: 'flex-start' }}>
                    <Autocomplete
                        freeSolo
                        size="small"
                        options={getNameSuggestions(newName)}
                        getOptionLabel={o => typeof o === 'string' ? o : o.name}
                        inputValue={newName}
                        onInputChange={(_, val) => { setNewName(val); setError(''); }}
                        onChange={(_, val) => {
                            if (val && typeof val === 'object') {
                                setNewName(val.name);
                            }
                        }}
                        filterOptions={(x) => x}
                        renderOption={(props, o) => (
                            <li {...props} key={o.id}>
                                <Box>
                                    <Typography sx={{ fontSize: 12, fontWeight: 600 }}>{o.name}</Typography>
                                    <Typography sx={{ fontSize: 10, color: '#a5b4fc' }}>{o.careerLevel}{o.supervisor ? ` • Supervisor: ${o.supervisor}` : ''}</Typography>
                                </Box>
                            </li>
                        )}
                        renderInput={(params) => (
                            <TextField {...params} label="Name *" placeholder="Type 2+ chars to search"
                                onKeyDown={e => e.key === 'Enter' && (e.preventDefault(), handleAdd())}
                                sx={{ flex: 1 }} />
                        )}
                        sx={{ flex: 1 }}
                        ListboxProps={{ sx: { maxHeight: 240 } }}
                    />
                    <Button variant="contained" startIcon={<AddIcon />} onClick={handleAdd} size="small"
                        sx={{ bgcolor: '#4f46e5', '&:hover': { bgcolor: '#4338ca' }, textTransform: 'none', height: 40 }}>
                        Add
                    </Button>
                </CardContent>
                {error && <Alert severity="error" sx={{ mx: 2, mb: 1 }}>{error}</Alert>}
            </Card>

            {/* Supported for the day Table */}
            <Card sx={{ mb: 2, borderRadius: 2, bgcolor: '#1a1744', border: '1px solid #312e81' }}>
                <CardContent>
                    <Box sx={{ display: 'flex', alignItems: 'center', mb: 1 }}>
                        <Typography variant="subtitle2" fontWeight={700} sx={{ flex: 1, color: '#e0e7ff' }}>
                            📋 Supported for the day ({lineItems.length})
                        </Typography>
                        <Tooltip title={showFilters ? 'Hide filters' : 'Show filters'}>
                            <IconButton size="small" onClick={() => setShowFilters(p => !p)}
                                sx={{ color: showFilters ? '#818cf8' : '#a5b4fc' }}>
                                <FilterListIcon fontSize="small" />
                            </IconButton>
                        </Tooltip>
                    </Box>
                    {lineItems.length > 0 ? (
                        <Box>
                            <Table size="small" sx={{ tableLayout: 'fixed', width: '100%' }}>
                                <TableHead>
                                    <TableRow>
                                        <TableCell sx={{ fontWeight: 700, fontSize: 11, p: '4px 6px', width: 26 }}>#</TableCell>
                                        <TableCell sx={{ fontWeight: 700, fontSize: 11, p: '4px 6px', width: '16%' }}>Name</TableCell>
                                        <TableCell sx={{ fontWeight: 700, fontSize: 11, p: '4px 6px', width: '13%' }}>Career Level</TableCell>
                                        <TableCell sx={{ fontWeight: 700, fontSize: 11, p: '4px 6px', width: '11%' }}>Supervisor</TableCell>
                                        <TableCell sx={{ fontWeight: 700, fontSize: 11, p: '4px 6px', width: '13%' }}>Login</TableCell>
                                        <TableCell sx={{ fontWeight: 700, fontSize: 11, p: '4px 6px', width: '13%' }}>Logout</TableCell>
                                        <TableCell sx={{ fontWeight: 700, fontSize: 11, p: '4px 6px', width: '7%' }}>Hrs</TableCell>
                                        <TableCell sx={{ fontWeight: 700, fontSize: 11, p: '4px 6px', width: '10%' }}>Type</TableCell>
                                        <TableCell sx={{ fontWeight: 700, fontSize: 11, p: '4px 6px', width: 52 }}>Actions</TableCell>
                                    </TableRow>
                                    {/* Filter row — toggled by filter icon */}
                                    {showFilters && (
                                        <TableRow>
                                            <TableCell sx={{ p: '2px 4px' }} />
                                            <TableCell sx={{ p: '2px 4px' }}>
                                                <TextField size="small" variant="standard" placeholder="Filter..."
                                                    value={filters.name} onChange={e => setFilter('name', e.target.value)}
                                                    InputProps={{ sx: { fontSize: 11 } }} fullWidth />
                                            </TableCell>
                                            <TableCell sx={{ p: '2px 4px' }}>
                                                <TextField size="small" variant="standard" placeholder="Filter..."
                                                    value={filters.careerLevel} onChange={e => setFilter('careerLevel', e.target.value)}
                                                    InputProps={{ sx: { fontSize: 11 } }} fullWidth />
                                            </TableCell>
                                            <TableCell sx={{ p: '2px 4px' }}>
                                                <TextField size="small" variant="standard" placeholder="Filter..."
                                                    value={filters.supervisor} onChange={e => setFilter('supervisor', e.target.value)}
                                                    InputProps={{ sx: { fontSize: 11 } }} fullWidth />
                                            </TableCell>
                                            <TableCell sx={{ p: '2px 4px' }}>
                                                <TextField size="small" variant="standard" placeholder="Filter..."
                                                    value={filters.loginTime} onChange={e => setFilter('loginTime', e.target.value)}
                                                    InputProps={{ sx: { fontSize: 11 } }} fullWidth />
                                            </TableCell>
                                            <TableCell sx={{ p: '2px 4px' }}>
                                                <TextField size="small" variant="standard" placeholder="Filter..."
                                                    value={filters.logoutTime} onChange={e => setFilter('logoutTime', e.target.value)}
                                                    InputProps={{ sx: { fontSize: 11 } }} fullWidth />
                                            </TableCell>
                                            <TableCell sx={{ p: '2px 4px' }} />
                                            <TableCell sx={{ p: '2px 4px' }}>
                                                <Select size="small" variant="standard" value={filters.allowanceCompoff}
                                                    onChange={e => setFilter('allowanceCompoff', e.target.value)}
                                                    displayEmpty sx={{ fontSize: 11, width: '100%' }}>
                                                    <MenuItem value="" sx={{ fontSize: 11 }}>All</MenuItem>
                                                    <MenuItem value="Compoff" sx={{ fontSize: 11 }}>Compoff</MenuItem>
                                                    <MenuItem value="Allowance" sx={{ fontSize: 11 }}>Allowance</MenuItem>
                                                </Select>
                                            </TableCell>
                                            <TableCell sx={{ p: '2px 4px' }} />
                                        </TableRow>
                                    )}
                                </TableHead>
                                <TableBody>
                                    {filteredItems.map((li, i) => {
                                        const { start, end } = parseTimeParts(li.time);
                                        return (
                                            <TableRow key={li.id}>
                                                <TableCell sx={{ p: '4px 6px', fontSize: 11 }}>{lineItems.indexOf(li) + 1}</TableCell>
                                                <TableCell sx={{ p: '4px 6px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                                                    {editingId === li.id ? (
                                                        <TextField size="small" value={li.name} variant="standard"
                                                            onChange={e => updateField(li.id, 'name', e.target.value)}
                                                            InputProps={{ sx: { fontSize: 11 } }} fullWidth />
                                                    ) : <Typography sx={{ fontSize: 11, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{li.name}</Typography>}
                                                </TableCell>
                                                <TableCell sx={{ p: '4px 4px' }}>
                                                    <Typography sx={{
                                                        fontSize: 12, fontWeight: 600,
                                                        color: '#c7d2fe', px: '6px', py: '4px',
                                                        textAlign: 'center',
                                                    }}>
                                                        {li.careerLevel || '—'}
                                                    </Typography>
                                                </TableCell>
                                                <TableCell sx={{ p: '4px 4px' }}>
                                                    <TextField size="small" value={li.supervisor || ''} variant="outlined"
                                                        placeholder="Supervisor"
                                                        onChange={e => updateField(li.id, 'supervisor', e.target.value)}
                                                        InputProps={{ sx: { fontSize: 11, py: 0 } }}
                                                        inputProps={{ style: { padding: '4px 6px', fontSize: 11 } }}
                                                        sx={{ width: '100%' }} />
                                                </TableCell>
                                                <TableCell sx={{ p: '4px 2px' }}>
                                                    <Autocomplete
                                                        freeSolo size="small" options={TIME_OPTIONS}
                                                        value={start || ''}
                                                        onInputChange={(_, val) => updateField(li.id, 'time', buildTimeStr(val || '', end))}
                                                        renderInput={(params) => (
                                                            <TextField {...params} size="small" placeholder="HH:MM AM"
                                                                inputProps={{ ...params.inputProps, style: { padding: '3px 4px', fontSize: 11 } }}
                                                                InputProps={{ ...params.InputProps, sx: { fontSize: 11, pr: '4px !important' } }} />
                                                        )}
                                                        ListboxProps={{ sx: { maxHeight: 200, fontSize: 11 } }}
                                                        disableClearable
                                                        sx={{ width: '100%' }}
                                                    />
                                                </TableCell>
                                                <TableCell sx={{ p: '4px 2px' }}>
                                                    <Autocomplete
                                                        freeSolo size="small" options={TIME_OPTIONS}
                                                        value={end || ''}
                                                        onInputChange={(_, val) => updateField(li.id, 'time', buildTimeStr(start, val || ''))}
                                                        renderInput={(params) => (
                                                            <TextField {...params} size="small" placeholder="HH:MM AM"
                                                                inputProps={{ ...params.inputProps, style: { padding: '3px 4px', fontSize: 11 } }}
                                                                InputProps={{ ...params.InputProps, sx: { fontSize: 11, pr: '4px !important' } }} />
                                                        )}
                                                        ListboxProps={{ sx: { maxHeight: 200, fontSize: 11 } }}
                                                        disableClearable
                                                        sx={{ width: '100%' }}
                                                    />
                                                </TableCell>
                                                <TableCell sx={{ p: '4px 6px' }}>
                                                    <Typography variant="body2" sx={{ fontSize: 11, fontWeight: 600, color: '#a5b4fc', whiteSpace: 'nowrap' }}>
                                                        {calcTotalHours(li.time) || '—'}
                                                    </Typography>
                                                </TableCell>
                                                <TableCell sx={{ p: '4px 4px' }}>
                                                    <Select size="small" value={li.allowanceCompoff || 'Compoff'}
                                                        onChange={e => updateField(li.id, 'allowanceCompoff', e.target.value)}
                                                        sx={{ fontSize: 11, width: '100%', '& .MuiSelect-select': { py: '4px', px: '6px' } }}>
                                                        <MenuItem value="Compoff" sx={{ fontSize: 11 }}>Compoff</MenuItem>
                                                        <MenuItem value="Allowance" sx={{ fontSize: 11 }}>Allowance</MenuItem>
                                                    </Select>
                                                </TableCell>
                                                <TableCell sx={{ p: '4px 2px' }}>
                                                    <Box sx={{ display: 'flex', gap: 0 }}>
                                                        <IconButton size="small"
                                                            onClick={() => setEditingId(editingId === li.id ? null : li.id)}
                                                            title={editingId === li.id ? 'Done' : 'Edit'}>
                                                            {editingId === li.id ? <CheckIcon sx={{ fontSize: 15 }} color="success" /> : <EditIcon sx={{ fontSize: 15 }} />}
                                                        </IconButton>
                                                        <IconButton size="small" onClick={() => setDeleteTarget(li)}
                                                            aria-label={`Delete ${li.name}`}>
                                                            <DeleteIcon sx={{ fontSize: 15 }} />
                                                        </IconButton>
                                                    </Box>
                                                </TableCell>
                                            </TableRow>
                                        );
                                    })}
                                </TableBody>
                            </Table>
                        </Box>
                    ) : (
                        <Typography variant="body2" color="text.disabled" sx={{ py: 3, textAlign: 'center' }}>
                            No entries yet. Use the form above or upload a file.
                        </Typography>
                    )}
                </CardContent>
            </Card>

            {/* Save / Cancel */}
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                <Button variant="contained" startIcon={<SaveIcon />} onClick={handleSave}
                    disabled={saving || !hasChanges} size="small"
                    sx={{ bgcolor: '#4f46e5', '&:hover': { bgcolor: '#4338ca' }, textTransform: 'none' }}>
                    {saving ? 'Saving...' : 'Save'}
                </Button>
                <Button variant="outlined" startIcon={<CancelIcon />} onClick={handleCancel}
                    disabled={!hasChanges} size="small" sx={{ textTransform: 'none' }}>
                    Cancel
                </Button>
                {hasChanges && (
                    <Typography variant="caption" color="warning.main" fontWeight={600}
                        sx={{ animation: 'pulse 1.5s infinite' }}>
                        ● Unsaved changes
                    </Typography>
                )}
            </Box>

            <ConfirmDialog open={!!deleteTarget} title="Delete Line Item"
                message={`Are you sure you want to delete "${deleteTarget?.name}"?`}
                onYes={handleDeleteConfirm} onNo={() => setDeleteTarget(null)} />
        </Box>
    );
}
