// Generated by GitHub Copilot
import React from 'react';
import { useAppContext } from '../context/AppContext';
import Snackbar from '@mui/material/Snackbar';
import MuiAlert from '@mui/material/Alert';

/**
 * Toast notification container – renders stacked toasts from context.
 */
export default function Toast() {
    const { toasts, dismissToast } = useAppContext();

    return (
        <>
            {toasts.map((t, i) => (
                <Snackbar key={t.id} open anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
                    sx={{ bottom: `${(i * 60) + 24}px !important` }}
                    onClose={() => dismissToast(t.id)}>
                    <MuiAlert severity={t.type === 'error' ? 'error' : t.type === 'info' ? 'info' : 'success'}
                        elevation={6} variant="filled" onClose={() => dismissToast(t.id)}
                        sx={{ minWidth: 280 }}>
                        {t.message}
                    </MuiAlert>
                </Snackbar>
            ))}
        </>
    );
}
