// Generated by GitHub Copilot
import React, { createContext, useContext, useState, useCallback } from 'react';

const AppContext = createContext();

/**
 * Global application state: entries list, selected entry/team, navigation, toasts.
 */
export function AppProvider({ children }) {
    const [entries, setEntries] = useState([]);
    const [sidebarOpen, setSidebarOpen] = useState(true);
    const [selectedEntryId, setSelectedEntryId] = useState(null);
    const [selectedTeamId, setSelectedTeamId] = useState(null);
    const [currentEntry, setCurrentEntry] = useState(null);
    const [view, setView] = useState('landing'); // 'landing'|'create'|'detail'|'team'|'deleted'
    const [loading, setLoading] = useState(false);
    const [toasts, setToasts] = useState([]);

    const addToast = useCallback((message, type = 'success') => {
        const id = Date.now();
        setToasts(prev => [...prev, { id, message, type }]);
        setTimeout(() => setToasts(prev => prev.filter(t => t.id !== id)), 3500);
    }, []);

    const dismissToast = useCallback((id) => {
        setToasts(prev => prev.filter(t => t.id !== id));
    }, []);

    const navigateToEntry = (entryId) => {
        setSelectedEntryId(entryId);
        setSelectedTeamId(null);
        setView('detail');
    };

    const navigateToTeam = (teamId) => {
        setSelectedTeamId(teamId);
        setView('team');
    };

    const navigateHome = () => {
        setSelectedEntryId(null);
        setSelectedTeamId(null);
        setCurrentEntry(null);
        setView('landing');
    };

    const navigateToDeleted = () => {
        setSelectedEntryId(null);
        setSelectedTeamId(null);
        setCurrentEntry(null);
        setView('deleted');
    };

    return (
        <AppContext.Provider value={{
            entries, setEntries,
            sidebarOpen, setSidebarOpen,
            selectedEntryId, setSelectedEntryId,
            selectedTeamId, setSelectedTeamId,
            currentEntry, setCurrentEntry,
            view, setView,
            loading, setLoading,
            toasts, addToast, dismissToast,
            navigateToEntry, navigateToTeam, navigateHome, navigateToDeleted,
        }}>
            {children}
        </AppContext.Provider>
    );
}

export function useAppContext() {
    return useContext(AppContext);
}
