// Generated by GitHub Copilot
import React, { createContext, useContext, useState, useCallback, useEffect, useRef } from 'react';

const AppContext = createContext();

/**
 * Global application state: entries list, selected entry/team, navigation, toasts.
 * Includes unsaved-changes guard: register a hasChanges callback via registerUnsavedCheck.
 */
export function AppProvider({ children }) {
    const [entries, setEntries] = useState([]);
    const [sidebarOpen, setSidebarOpen] = useState(true);
    const [selectedEntryId, setSelectedEntryId] = useState(() => sessionStorage.getItem('selectedEntryId') || null);
    const [selectedTeamId, setSelectedTeamId] = useState(() => sessionStorage.getItem('selectedTeamId') || null);
    const [currentEntry, setCurrentEntry] = useState(null);
    const [view, setView] = useState(() => sessionStorage.getItem('view') || 'landing');
    const [loading, setLoading] = useState(false);
    const [toasts, setToasts] = useState([]);
    // Unsaved-changes guard
    const [pendingNav, setPendingNav] = useState(null); // { action: fn } — deferred navigation
    const unsavedCheckRef = useRef(null); // registered by TeamDetail: () => boolean

    const registerUnsavedCheck = useCallback((fn) => { unsavedCheckRef.current = fn; }, []);
    const unregisterUnsavedCheck = useCallback(() => { unsavedCheckRef.current = null; }, []);

    /** Wrap any navigation: if unsaved changes, show guard dialog instead */
    const guardedNav = useCallback((action) => {
        if (unsavedCheckRef.current && unsavedCheckRef.current()) {
            setPendingNav({ action });
        } else {
            action();
        }
    }, []);

    const confirmPendingNav = useCallback(() => {
        if (pendingNav) { pendingNav.action(); }
        setPendingNav(null);
        unsavedCheckRef.current = null;
    }, [pendingNav]);

    const cancelPendingNav = useCallback(() => { setPendingNav(null); }, []);

    // Persist navigation state to sessionStorage so page survives browser refresh
    useEffect(() => {
        if (selectedEntryId) sessionStorage.setItem('selectedEntryId', selectedEntryId);
        else sessionStorage.removeItem('selectedEntryId');
    }, [selectedEntryId]);
    useEffect(() => {
        if (selectedTeamId) sessionStorage.setItem('selectedTeamId', selectedTeamId);
        else sessionStorage.removeItem('selectedTeamId');
    }, [selectedTeamId]);
    useEffect(() => {
        sessionStorage.setItem('view', view);
    }, [view]);

    const addToast = useCallback((message, type = 'success') => {
        const id = Date.now();
        setToasts(prev => [...prev, { id, message, type }]);
        setTimeout(() => setToasts(prev => prev.filter(t => t.id !== id)), 3500);
    }, []);

    const dismissToast = useCallback((id) => {
        setToasts(prev => prev.filter(t => t.id !== id));
    }, []);

    const navigateToEntry = (entryId) => {
        guardedNav(() => {
            setSelectedEntryId(entryId);
            setSelectedTeamId(null);
            setView('detail');
        });
    };

    const navigateToTeam = (teamId) => {
        guardedNav(() => {
            setSelectedTeamId(teamId);
            setView('team');
        });
    };

    const navigateHome = () => {
        guardedNav(() => {
            setSelectedEntryId(null);
            setSelectedTeamId(null);
            setCurrentEntry(null);
            setView('landing');
        });
    };

    const navigateToDeleted = () => {
        guardedNav(() => {
            setSelectedEntryId(null);
            setSelectedTeamId(null);
            setCurrentEntry(null);
            setView('deleted');
        });
    };

    const navigateToResources = () => {
        guardedNav(() => {
            setSelectedTeamId(null);
            setView('resources');
        });
    };

    return (
        <AppContext.Provider value={{
            entries, setEntries,
            sidebarOpen, setSidebarOpen,
            selectedEntryId, setSelectedEntryId,
            selectedTeamId, setSelectedTeamId,
            currentEntry, setCurrentEntry,
            view, setView,
            loading, setLoading,
            toasts, addToast, dismissToast,
            navigateToEntry, navigateToTeam, navigateHome, navigateToDeleted, navigateToResources,
            pendingNav, confirmPendingNav, cancelPendingNav,
            registerUnsavedCheck, unregisterUnsavedCheck,
        }}>
            {children}
        </AppContext.Provider>
    );
}

export function useAppContext() {
    return useContext(AppContext);
}
