// Generated by GitHub Copilot
import React, { createContext, useContext, useState, useEffect } from 'react';

const AuthContext = createContext();

/**
 * Authentication provider – stores empId in localStorage.
 * Login does NOT create any entries; only stores employee identity.
 */
export function AuthProvider({ children }) {
    const [empId, setEmpId] = useState(() => localStorage.getItem('empId') || '');

    useEffect(() => {
        if (empId) localStorage.setItem('empId', empId);
        else localStorage.removeItem('empId');
    }, [empId]);

    const login = (id) => setEmpId(id.trim());
    const logout = () => { setEmpId(''); localStorage.removeItem('empId'); };

    return (
        <AuthContext.Provider value={{ empId, isLoggedIn: !!empId, login, logout }}>
            {children}
        </AuthContext.Provider>
    );
}

export function useAuth() {
    return useContext(AuthContext);
}
