// Generated by GitHub Copilot
import React, { createContext, useContext, useState, useEffect } from 'react';

const AuthContext = createContext();

/**
 * Authentication provider – stores empId and careerLevel in localStorage.
 * Career level 9 = Lead (team-level restricted view/edit).
 * Career level 7 and 8 = full admin access.
 */
export function AuthProvider({ children }) {
    const [empId, setEmpId] = useState(() => localStorage.getItem('empId') || '');
    const [careerLevel, setCareerLevel] = useState(() => {
        const stored = localStorage.getItem('careerLevel');
        return stored !== null ? parseInt(stored, 10) : null;
    });

    useEffect(() => {
        if (empId) localStorage.setItem('empId', empId);
        else localStorage.removeItem('empId');
    }, [empId]);

    useEffect(() => {
        if (careerLevel !== null) localStorage.setItem('careerLevel', String(careerLevel));
        else localStorage.removeItem('careerLevel');
    }, [careerLevel]);

    /** Career level 9 = Lead: can view all releases but only edit their own teams */
    const isLeadOnly = careerLevel !== null && careerLevel === 9;
    /** Career level 7 and 8 = full admin access to all features */
    const isFullAccess = careerLevel === null || (careerLevel >= 7 && careerLevel <= 8);

    const login = (id, cl) => {
        setEmpId(id.trim());
        setCareerLevel(cl !== undefined && cl !== null ? parseInt(cl, 10) : null);
    };
    const logout = () => {
        setEmpId('');
        setCareerLevel(null);
        localStorage.removeItem('empId');
        localStorage.removeItem('careerLevel');
        sessionStorage.clear();
    };

    return (
        <AuthContext.Provider value={{ empId, careerLevel, isLoggedIn: !!empId, isLeadOnly, isFullAccess, login, logout }}>
            {children}
        </AuthContext.Provider>
    );
}

export function useAuth() {
    return useContext(AuthContext);
}
