// Generated by GitHub Copilot
import React, { useEffect, useCallback, useMemo } from 'react';
import { AuthProvider, useAuth } from './context/AuthContext';
import { AppProvider, useAppContext } from './context/AppContext';
import api from './utils/api';
import LoginScreen from './components/LoginScreen';
import Header from './components/Header';
import Sidebar from './components/Sidebar';
import CreateEntryForm from './components/CreateEntryForm';
import EntryDetail from './components/EntryDetail';
import DeletedItems from './components/DeletedItems';
import ResourcesListScreen from './components/ResourcesListScreen';
import Toast from './components/Toast';
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
import LinearProgress from '@mui/material/LinearProgress';
import { ThemeProvider, createTheme } from '@mui/material/styles';

/**
 * Main application shell.
 * Sidebar + main content with routing via context state.
 */
function AppContent() {
    const { isLoggedIn } = useAuth();
    const {
        setEntries, selectedEntryId, setCurrentEntry,
        view, loading, setLoading,
    } = useAppContext();

    const loadEntries = useCallback(async () => {
        try { const list = await api.getEntries(); setEntries(list); }
        catch { /* ignore */ }
    }, [setEntries]);

    useEffect(() => { if (isLoggedIn) loadEntries(); }, [isLoggedIn, loadEntries]);

    const loadEntry = useCallback(async () => {
        if (!selectedEntryId) { setCurrentEntry(null); return; }
        setLoading(true);
        try { const entry = await api.getEntry(selectedEntryId); setCurrentEntry(entry); }
        catch { setCurrentEntry(null); }
        setLoading(false);
    }, [selectedEntryId, setCurrentEntry, setLoading]);

    useEffect(() => { loadEntry(); }, [loadEntry]);

    const refresh = () => { loadEntry(); loadEntries(); };

    if (!isLoggedIn) return <LoginScreen />;

    return (
        <Box sx={{ height: '100vh', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
            <Header />
            <Box sx={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
                <Sidebar />
                <Box component="main" sx={{ flex: 1, overflowY: 'auto', p: 3, bgcolor: '#0f0e2a' }}>
                    {loading && <LinearProgress sx={{ mb: 2 }} />}
                    {view === 'create' ? (
                        <CreateEntryForm />
                    ) : view === 'deleted' ? (
                        <DeletedItems onRefresh={refresh} />
                    ) : view === 'resources' ? (
                        <ResourcesListScreen />
                    ) : (
                        <EntryDetail onRefresh={refresh} />
                    )}
                </Box>
            </Box>
            <Toast />
        </Box>
    );
}

/**
 * Root component with providers.
 */
/**
 * MUI dark theme — ensures ALL text, inputs, labels, table cells, radios,
 * selects, checkboxes etc. are light-colored on the dark background.
 */
const darkTheme = createTheme({
    palette: {
        mode: 'dark',
        primary: { main: '#818cf8', light: '#a5b4fc', dark: '#4f46e5' },
        secondary: { main: '#c084fc' },
        background: { default: '#0f0e2a', paper: '#1a1744' },
        text: { primary: '#e0e7ff', secondary: '#a5b4fc' },
        divider: '#312e81',
    },
    typography: {
        fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    },
    components: {
        MuiCard: { styleOverrides: { root: { backgroundImage: 'none' } } },
        MuiTableCell: { styleOverrides: { root: { borderBottomColor: '#312e81' } } },
        MuiOutlinedInput: { styleOverrides: { notchedOutline: { borderColor: '#4f46e5' } } },
    },
});

export default function App() {
    return (
        <ThemeProvider theme={darkTheme}>
            <AuthProvider>
                <AppProvider>
                    <CssBaseline />
                    <AppContent />
                </AppProvider>
            </AuthProvider>
        </ThemeProvider>
    );
}
