// Generated by GitHub Copilot
import React, { useEffect, useCallback, useMemo } from 'react';
import { AuthProvider, useAuth } from './context/AuthContext';
import { AppProvider, useAppContext } from './context/AppContext';
import api from './utils/api';
import LoginScreen from './components/LoginScreen';
import Header from './components/Header';
import Sidebar from './components/Sidebar';
import CreateEntryForm from './components/CreateEntryForm';
import EntryDetail from './components/EntryDetail';
import DeletedItems from './components/DeletedItems';
import ResourcesListScreen from './components/ResourcesListScreen';
import Toast from './components/Toast';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
import LinearProgress from '@mui/material/LinearProgress';
import { ThemeProvider, createTheme } from '@mui/material/styles';

/**
 * Main application shell.
 * Sidebar + main content with routing via context state.
 */
function AppContent() {
    const { isLoggedIn } = useAuth();
    const {
        setEntries, selectedEntryId, setCurrentEntry,
        view, loading, setLoading,
        pendingNav, confirmPendingNav, cancelPendingNav, saveAndContinuePendingNav,
        loadEmployees,
        hasUnsavedChanges,
    } = useAppContext();

    const loadEntries = useCallback(async () => {
        try { const list = await api.getEntries(); setEntries(list); }
        catch { /* ignore */ }
    }, [setEntries]);

    useEffect(() => { if (isLoggedIn) { loadEntries(); loadEmployees(); } }, [isLoggedIn, loadEntries, loadEmployees]);

    // Poll every 30s to sync multi-user changes (entries list + employees)
    useEffect(() => {
        if (!isLoggedIn) return;
        const id = setInterval(() => { loadEntries(); loadEmployees(); }, 30000);
        return () => clearInterval(id);
    }, [isLoggedIn, loadEntries, loadEmployees]);

    const loadEntry = useCallback(async () => {
        if (!selectedEntryId) { setCurrentEntry(null); return; }
        setLoading(true);
        try { const entry = await api.getEntry(selectedEntryId); setCurrentEntry(entry); }
        catch { setCurrentEntry(null); }
        setLoading(false);
    }, [selectedEntryId, setCurrentEntry, setLoading]);

    useEffect(() => { loadEntry(); }, [loadEntry]);

    // Poll current entry every 20s — but only when no unsaved local changes
    useEffect(() => {
        if (!selectedEntryId) return;
        const id = setInterval(() => {
            if (!hasUnsavedChanges()) loadEntry();
        }, 20000);
        return () => clearInterval(id);
    }, [selectedEntryId, loadEntry, hasUnsavedChanges]);

    const refresh = () => { loadEntry(); loadEntries(); };

    if (!isLoggedIn) return <LoginScreen />;

    return (
        <Box sx={{ height: '100vh', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
            <Header />
            <Box sx={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
                <Sidebar />
                <Box component="main" sx={{ flex: 1, overflowY: 'auto', p: 3, bgcolor: '#0f0e2a' }}>
                    {loading && <LinearProgress sx={{ mb: 2 }} />}
                    {view === 'create' ? (
                        <CreateEntryForm />
                    ) : view === 'deleted' ? (
                        <DeletedItems onRefresh={refresh} />
                    ) : view === 'resources' ? (
                        <ResourcesListScreen />
                    ) : (
                        <EntryDetail onRefresh={refresh} />
                    )}
                </Box>
            </Box>
            <Toast />
            {/* Unsaved changes navigation guard */}
            <Dialog open={!!pendingNav} onClose={cancelPendingNav} maxWidth="xs" fullWidth
                PaperProps={{ sx: { borderRadius: 2, bgcolor: '#1a1744', border: '1px solid #4f46e5' } }}>
                <DialogTitle sx={{ fontWeight: 700, color: '#fbbf24', fontSize: 16 }}>⚠️ Unsaved Changes</DialogTitle>
                <DialogContent>
                    <Typography sx={{ color: '#e0e7ff', fontSize: 14 }}>
                        You have unsaved changes. What would you like to do?
                    </Typography>
                </DialogContent>
                <DialogActions sx={{ px: 3, pb: 2, gap: 1, flexWrap: 'wrap' }}>
                    <Button size="small" variant="outlined"
                        onClick={cancelPendingNav}
                        sx={{ textTransform: 'none', borderColor: '#4f46e5', color: '#a5b4fc' }}>
                        Cancel
                    </Button>
                    <Button size="small" variant="contained" color="success"
                        onClick={saveAndContinuePendingNav}
                        sx={{ textTransform: 'none' }}>
                        Save &amp; Continue
                    </Button>
                    <Button size="small" variant="outlined" color="error"
                        onClick={confirmPendingNav}
                        sx={{ textTransform: 'none' }}>
                        Discard &amp; Continue
                    </Button>
                </DialogActions>
            </Dialog>
        </Box>
    );
}

/**
 * Root component with providers.
 */
/**
 * MUI dark theme — ensures ALL text, inputs, labels, table cells, radios,
 * selects, checkboxes etc. are light-colored on the dark background.
 */
const darkTheme = createTheme({
    palette: {
        mode: 'dark',
        primary: { main: '#818cf8', light: '#a5b4fc', dark: '#4f46e5' },
        secondary: { main: '#c084fc' },
        background: { default: '#0f0e2a', paper: '#1a1744' },
        text: { primary: '#e0e7ff', secondary: '#a5b4fc' },
        divider: '#312e81',
    },
    typography: {
        fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    },
    components: {
        MuiCard: { styleOverrides: { root: { backgroundImage: 'none' } } },
        MuiTableCell: { styleOverrides: { root: { borderBottomColor: '#312e81' } } },
        MuiOutlinedInput: { styleOverrides: { notchedOutline: { borderColor: '#4f46e5' } } },
    },
});

export default function App() {
    return (
        <ThemeProvider theme={darkTheme}>
            <AuthProvider>
                <AppProvider>
                    <CssBaseline />
                    <AppContent />
                </AppProvider>
            </AuthProvider>
        </ThemeProvider>
    );
}
