// Generated by GitHub Copilot
// In production (same origin), use relative /api path.
// In development, point to backend on port 5000.
const BASE = process.env.NODE_ENV === 'production'
    ? '/api'
    : `http://${window.location.hostname}:5000/api`;

/**
 * Shared fetch helper with JSON error handling.
 * @param {string} url - API endpoint URL
 * @param {object} opts - fetch options
 * @returns {Promise<any>} Parsed JSON response
 */
async function request(url, opts = {}) {
    const res = await fetch(url, opts);
    const text = await res.text();
    let json;
    try { json = JSON.parse(text); } catch {
        throw new Error(res.ok ? 'Invalid server response' : `Server error (${res.status})`);
    }
    if (!res.ok) throw new Error(json.error || 'Request failed');
    return json;
}

const api = {
    validateLogin: (empId) =>
        request(`${BASE}/auth/validate`, {
            method: 'POST', headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ empId }),
        }),
    getReleaseOwners: () => request(`${BASE}/options/release-owners`),
    getCareerLevels: () => request(`${BASE}/options/career-levels`),
    lookupEmployee: (q) => request(`${BASE}/options/employee-lookup?q=${encodeURIComponent(q)}`),
    getEmployees: () => request(`${BASE}/options/employees`),

    getEntries: () => request(`${BASE}/entries`),
    getEntry: (id) => request(`${BASE}/entries/${id}`),
    createEntry: (formData) =>
        fetch(`${BASE}/entries`, { method: 'POST', body: formData })
            .then(async r => { const j = await r.json(); if (!r.ok) throw new Error(j.error); return j; }),
    deleteEntry: (id) => request(`${BASE}/entries/${id}`, { method: 'DELETE' }),
    updateEntry: (id, data) =>
        request(`${BASE}/entries/${id}`, {
            method: 'PUT', headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data),
        }),

    addTeam: (entryId, data) =>
        request(`${BASE}/entries/${entryId}/teams`, {
            method: 'POST', headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data),
        }),
    deleteTeam: (entryId, teamId) =>
        request(`${BASE}/entries/${entryId}/teams/${teamId}`, { method: 'DELETE' }),
    updateTeam: (entryId, teamId, data) =>
        request(`${BASE}/entries/${entryId}/teams/${teamId}`, {
            method: 'PUT', headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data),
        }),
    uploadSanityFile: (entryId, formData) =>
        fetch(`${BASE}/entries/${entryId}/sanity-upload`, { method: 'POST', body: formData })
            .then(async r => { const j = await r.json(); if (!r.ok) throw new Error(j.error); return j; }),

    addLineItem: (entryId, teamId, data) =>
        request(`${BASE}/entries/${entryId}/teams/${teamId}/line-items`, {
            method: 'POST', headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data),
        }),
    saveAllLineItems: (entryId, teamId, items) =>
        request(`${BASE}/entries/${entryId}/teams/${teamId}/line-items`, {
            method: 'PUT', headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ items }),
        }),
    bulkAddLineItems: (entryId, teamId, items) =>
        request(`${BASE}/entries/${entryId}/teams/${teamId}/bulk-line-items`, {
            method: 'POST', headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ items }),
        }),

    getEntryHistory: (entryId) => request(`${BASE}/entries/${entryId}/history`),

    uploadEmployeeList: (employees, uploadedBy, filename) =>
        request(`${BASE}/options/employees`, {
            method: 'POST', headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ employees, uploadedBy: uploadedBy || 'UNKNOWN', filename: filename || 'unknown' }),
        }),

    getResourceUploadHistory: () => request(`${BASE}/options/resource-upload-history`),

    getExportUrl: (entryId) => `${BASE}/entries/${entryId}/export`,
    getTeamExportUrl: (entryId, teamId) => `${BASE}/entries/${entryId}/teams/${teamId}/export`,

    bulkAddTeams: (entryId, teams, createdBy) =>
        request(`${BASE}/entries/${entryId}/bulk-teams`, {
            method: 'POST', headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ teams, createdBy }),
        }),

    getDeletedItems: () => request(`${BASE}/deleted-items`),
    recoverDeletedItem: (id) => request(`${BASE}/deleted-items/${id}/recover`, { method: 'POST' }),
    permanentDeleteItem: (id) => request(`${BASE}/deleted-items/${id}`, { method: 'DELETE' }),
    deleteAllDeletedItems: () => request(`${BASE}/deleted-items`, { method: 'DELETE' }),
};

export default api;
