// Generated by GitHub Copilot

/**
 * Format "YYYY-MM-DD" → "May 9th" style label for sidebar display.
 * @param {string} dateStr - ISO date string
 * @returns {string} Formatted date label
 */
export function formatDateLabel(dateStr) {
    const date = new Date(dateStr + 'T00:00:00');
    const months = [
        'January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December',
    ];
    const day = date.getDate();
    return `${months[date.getMonth()]} ${day}${ordinal(day)}`;
}

function ordinal(d) {
    if (d > 3 && d < 21) return 'th';
    switch (d % 10) {
        case 1: return 'st';
        case 2: return 'nd';
        case 3: return 'rd';
        default: return 'th';
    }
}

/** Today as YYYY-MM-DD */
export function getTodayStr() {
    return new Date().toISOString().split('T')[0];
}

/**
 * Check if a user is the lead of a team by comparing enterprise ID and full name.
 * Handles various formats: "shini.vv", "Shini V V", "Krishnan, Pirtheebaa", etc.
 * @param {string} userEmpId - Logged-in user's enterprise ID (e.g., "pirtheebaa.krishnan")
 * @param {string} teamLeadName - Team's lead name field (could be ID or full name)
 * @param {Array} employees - Employee list from resource file
 * @returns {boolean} True if user is the lead of this team
 */
export function isUserTeamLead(userEmpId, teamLeadName, employees = []) {
    if (!userEmpId || !teamLeadName) return false;

    const empIdLower = userEmpId.toLowerCase().trim();
    const leadLower = teamLeadName.toLowerCase().trim();

    // Direct match on enterprise ID
    if (leadLower === empIdLower) return true;

    // Extract name parts from enterprise ID (e.g., "pirtheebaa.krishnan" → ["pirtheebaa", "krishnan"])
    const empIdParts = empIdLower.split('.').map(p => p.trim()).filter(p => p);

    // Extract name parts from team lead name
    // Handle formats: "Krishnan, Pirtheebaa" or "Pirtheebaa Krishnan" or "P Krishnan"
    let leadNameParts = [];
    if (leadLower.includes(',')) {
        // "Last, First" format
        leadNameParts = leadLower.split(',').map(p => p.trim()).filter(p => p);
    } else {
        // "First Last" format
        leadNameParts = leadLower.split(/\s+/).filter(p => p);
    }

    // Normalize parts by removing dots, commas, and splitting by spaces
    const normalizeText = (text) => {
        return text.toLowerCase()
            .replace(/[.,]/g, ' ')
            .split(/\s+/)
            .map(p => p.trim())
            .filter(p => p.length > 1); // Filter out single chars like "a"
    };

    const empIdNormalized = normalizeText(empIdLower);
    const leadNormalized = normalizeText(leadLower);

    // Check if all enterprise ID parts are present in lead name (strict matching - parts must be substantial)
    // Require at least 3 characters overlap to avoid false matches like "a" in "krishnan"
    const empIdInLead = empIdNormalized.length > 0 && empIdNormalized.every(part =>
        leadNormalized.some(leadPart => {
            // For short parts (< 4 chars), require exact match
            if (part.length < 4 || leadPart.length < 4) {
                return part === leadPart;
            }
            // For longer parts, allow partial match but require significant overlap
            const longer = part.length > leadPart.length ? part : leadPart;
            const shorter = part.length > leadPart.length ? leadPart : part;
            return longer.includes(shorter) && shorter.length >= 4;
        })
    );

    if (empIdInLead && empIdNormalized.length > 0) return true;

    // Find logged-in user's full name from employee list
    const userEmployee = employees.find(e =>
        e.id && e.id.toLowerCase().trim() === empIdLower
    );

    if (userEmployee && userEmployee.name) {
        const userNameLower = userEmployee.name.toLowerCase().trim();
        // Direct match on full name
        if (leadLower === userNameLower) return true;

        // Normalized match with strict checking
        const userNameNormalized = normalizeText(userNameLower);
        const userNameInLead = userNameNormalized.length > 0 && userNameNormalized.every(part =>
            leadNormalized.some(leadPart => {
                if (part.length < 4 || leadPart.length < 4) {
                    return part === leadPart;
                }
                const longer = part.length > leadPart.length ? part : leadPart;
                const shorter = part.length > leadPart.length ? leadPart : part;
                return longer.includes(shorter) && shorter.length >= 4;
            })
        );
        if (userNameInLead && userNameNormalized.length > 0) return true;
    }

    // Reverse check: find lead in employee list and compare IDs
    const leadEmployee = employees.find(e => {
        if (!e.id || !e.name) return false;
        const leadIdLower = e.id.toLowerCase().trim();
        const leadNameLower = e.name.toLowerCase().trim();
        const eIdNormalized = normalizeText(leadIdLower);
        const eNameNormalized = normalizeText(leadNameLower);

        const idMatch = leadNormalized.length > 0 && leadNormalized.every(part =>
            eIdNormalized.some(ePart => {
                if (part.length < 4 || ePart.length < 4) {
                    return part === ePart;
                }
                const longer = part.length > ePart.length ? part : ePart;
                const shorter = part.length > ePart.length ? ePart : part;
                return longer.includes(shorter) && shorter.length >= 4;
            })
        );
        const nameMatch = leadNormalized.length > 0 && leadNormalized.every(part =>
            eNameNormalized.some(ePart => {
                if (part.length < 4 || ePart.length < 4) {
                    return part === ePart;
                }
                const longer = part.length > ePart.length ? part : ePart;
                const shorter = part.length > ePart.length ? ePart : part;
                return longer.includes(shorter) && shorter.length >= 4;
            })
        );

        return (idMatch && leadNormalized.length > 0) || (nameMatch && leadNormalized.length > 0);
    });

    if (leadEmployee && leadEmployee.id) {
            const leadIdLower = leadEmployee.id.toLowerCase().trim();
            if (leadIdLower === empIdLower) return true;

            // Check if lead's ID parts match user's ID parts
            const leadIdNormalized = normalizeText(leadIdLower);
            const partsMatch = empIdNormalized.every(part =>
                leadIdNormalized.some(leadPart =>
                    leadPart.includes(part) || part.includes(leadPart)
                )
            );
            if (partsMatch && empIdNormalized.length > 0) return true;
        }

        return false;
    }
