// Generated by GitHub Copilot

/**
 * Format "YYYY-MM-DD" → "May 9th" style label for sidebar display.
 * @param {string} dateStr - ISO date string
 * @returns {string} Formatted date label
 */
export function formatDateLabel(dateStr) {
    const date = new Date(dateStr + 'T00:00:00');
    const months = [
        'January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December',
    ];
    const day = date.getDate();
    return `${months[date.getMonth()]} ${day}${ordinal(day)}`;
}

function ordinal(d) {
    if (d > 3 && d < 21) return 'th';
    switch (d % 10) {
        case 1: return 'st';
        case 2: return 'nd';
        case 3: return 'rd';
        default: return 'th';
    }
}

/** Today as YYYY-MM-DD */
export function getTodayStr() {
    return new Date().toISOString().split('T')[0];
}

/**
 * Check if a user is the lead of a team by comparing enterprise ID and full name.
 * Handles various formats: "shini.vv", "Shini V V", "shini v v", etc.
 * @param {string} userEmpId - Logged-in user's enterprise ID (e.g., "shini.vv")
 * @param {string} teamLeadName - Team's lead name field (could be ID or full name)
 * @param {Array} employees - Employee list from resource file
 * @returns {boolean} True if user is the lead of this team
 */
export function isUserTeamLead(userEmpId, teamLeadName, employees = []) {
    if (!userEmpId || !teamLeadName) return false;
    
    const empIdLower = userEmpId.toLowerCase().trim();
    const leadLower = teamLeadName.toLowerCase().trim();
    
    // Direct match on enterprise ID
    if (leadLower === empIdLower) return true;
    
    // Find logged-in user's full name from employee list
    const userEmployee = employees.find(e => 
        e.id && e.id.toLowerCase().trim() === empIdLower
    );
    
    if (userEmployee && userEmployee.name) {
        const userNameLower = userEmployee.name.toLowerCase().trim();
        // Match on full name
        if (leadLower === userNameLower) return true;
    }
    
    // Reverse check: find lead in employee list and compare IDs
    const leadEmployee = employees.find(e => {
        if (!e.id || !e.name) return false;
        const leadIdLower = e.id.toLowerCase().trim();
        const leadNameLower = e.name.toLowerCase().trim();
        return leadIdLower === leadLower || leadNameLower === leadLower;
    });
    
    if (leadEmployee && leadEmployee.id) {
        const leadIdLower = leadEmployee.id.toLowerCase().trim();
        if (leadIdLower === empIdLower) return true;
    }
    
    return false;
}
