// Generated by GitHub Copilot

/**
 * Format "YYYY-MM-DD" → "May 9th" style label for sidebar display.
 * @param {string} dateStr - ISO date string
 * @returns {string} Formatted date label
 */
export function formatDateLabel(dateStr) {
    const date = new Date(dateStr + 'T00:00:00');
    const months = [
        'January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December',
    ];
    const day = date.getDate();
    return `${months[date.getMonth()]} ${day}${ordinal(day)}`;
}

function ordinal(d) {
    if (d > 3 && d < 21) return 'th';
    switch (d % 10) {
        case 1: return 'st';
        case 2: return 'nd';
        case 3: return 'rd';
        default: return 'th';
    }
}

/** Today as YYYY-MM-DD */
export function getTodayStr() {
    return new Date().toISOString().split('T')[0];
}
